### ISSUE TITLE
Last couple of lines absent from left pane in one-to-one view of trails

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1002]
The one-to-one view of trails looks like this:

![image](https://user-images.githubusercontent.com/43101723/129629059-8d0f4730-a5b9-4128-b7be-abf05b6a8f1a.png)

Although the pane is scrolled all the way down, the second last line is barely visible and the last is not visible. I think this is because the left pane has slightly narrower rows, and this difference accumulates.

**Comment by kayaulai** [comment]
Just realised that this doesn't always happen

**Comment by terrydubois** [comment]
Looks like this is an issue when the user's font is set to Chinese or Japanese. It appears to happen in all 1-to-1 panes. Hopefully an easy fix :o

**Comment by kayaulai** [comment]
Oh I changed the interface to English between the two posts so I can confirm that!
