### ISSUE TITLE
Clicking on a row of the left side of a one-to-many table doesn't always scroll the main screen

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1006]
In my case, only the entries up to the second last entry of the first track chain managed to scroll. All other track entries failed to scroll, although the entry is still focused on the main screen when I scroll down/up to it.

Edit: It's worked for a few near the end too.

Rez file is attached, though it may not reproduce easily.

[three-parting-2569_0.20.rez.zip](https://github.com/johnwdubois/rezonator/files/7002069/three-parting-2569_0.20.rez.zip)

**Comment by terrydubois** [comment]
Ah, looks like the Chain tab 1-to-many does not scroll the mainscreen if the entry is a chunk.
