### ISSUE TITLE
Hide Chunk boxes (menu option)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1012]
1. Give the user the following menu option:
Menu > View > Chunk > Hide chunk boxes
2. When Chunks are created automatically (e.g. in IGT import), select this option automatically.
3. For example, in the following screenshot, all the black boxes could be hidden, giving the user a cleaner visualization of the text in the main screen. 
4. NOTE: All Chunk information is still preserved and displayed to the user in the Chunk tab of the Nav window, so hiding the chunk boxes is not a big loss for IGT users.

![Hide chunk boxes - menu option](https://user-images.githubusercontent.com/22628444/129952434-c5d39e18-46d8-44bf-bb05-5f13c21be727.PNG)

**Comment by kittynugget** [comment]
with this setting on, should we also allow the user to make new chunks? @johnwdubois
