### ISSUE TITLE
Timestamps for Link and vLink

### ISSUE THREAD

**Issue by terrydubois** [johnwdubois/rezonator#102]
**Is your feature request related to a problem?**
We need to keep track of how long it takes users to create links and chains.

**Describe the solution you'd like**
We need time stamps for links and vLinks (a.k.a. vizLinks).
1. For the Link grid, capture the sourceTimeOn and goalTimeOn for when the user clicks on source and the goal, respectively.
2. For the vLink grid, capture the same information for when the link is first displayed.

**Comment by johnwdubois** [comment]
This duplicates #107 .
