### ISSUE TITLE
GridView facelift 1

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#103]
**Is your feature request related to a problem?**
1. The GridView is hard to see and hard to use. The font is too small, columns are not sized efficiently for their contents, etc.
2. Also, the names for the various grids in the gridView display are verbose, taking up too much space on the screen. They should be as simple as possible.
 
**Solution, Phase 1: Simplify names of grids**
1. For each grid used in Rezonator, give a name that is short, distinctive, and to the point. 
2. Change the labels on the tabs in the GridView, replacing the old names with the new names.
3. The new names should also be used for saving to CSV files, for consistency. 
4. As much as possible, the new names should also be used in code (for variable names, etc); or at least, a comment should be entered next to any old names, showing the correspondence of the old name to the new name. 
5. The following table shows the new names to be used for grids (e.g. on the GridView tabs), plus the old names they replace. 
6. For any new grids created, please keep the names as simple as possible, in line with the names given here.
7. If possible, arrange the tabs in the GridView in the order shown here.

New Name    |    Old Name
---    |    ---
Unit         |    unitGrid
Line     |    lineGrid
Word       |    wordGrid
vizWord   |    dynamicWordGrid
Stack     |    stackChainGrid
StackUnit     |    unitInStack
Clique        |    cliqueGrid
vizClique    |    cliqueDisplayGrid
Pick            |    filterGrid
Search       |    searchGrid
Hit             |    hitGrid
Race          |    raceGrid

**Solution, Phase 2: Make the GridView more readable**
The goal is to make a few simple changes that will improve the readability of the GridView. No need for a major beautification project right now, just basic readability.
1. Increase the font size and line height. (If it's easy to implement the user option to increase/decrease font size etc in a scalable way, that's a plus; but if not, just hard-code it for now. The default should probably be a fairly large font.)
2. Allow the user to toggle easily between displaying one grid or two grids.
2. Allow the user to use the whole width of the screen, when displaying just one grid. (With the expanded Word table (CSV) having 37 columns or so, we need room to display a lot more columns in the Word table, just to give one example.)
 4. Use more of the height of the screen. Right now, half of the screen height is wasted.
5. Consider sizing the columns more efficiently, according to their expected contents. One way to do this:
- create a grid (or variable, array, or whatever) that assigns to each column a certain proportion of the total width. 
- in this grid, each column gets a decimal value between 0 and 1. This should be set by us, based on the expected contents of the cell (e.g. a lineID consisting of a single integer that will have only 1-4 digits, vs. a list of Track chain wordID's that could get very long).
- Multiply this value times total pixels available (= total width of the table as displayed) to get the width of the column
- The total should be less than or equal to 1 (i.e. you can't assign more than 100% of the space available).
- Pick one "residual" column to receive whatever width is not allotted to other columns; that is, even if no value is specified for the column that holds the list of Track chain wordID's, this column could occupy half or more of the table width (however much remains after the others get their share, i.e. 1-_x_).
6. No need to display the vertical lines that separate the columns. The contents of the column are enough to convey this information.

**Comment by Georgio-Klironomos** [comment]
Currently the gridView text size is set to the same scale as the main view text, should these be separate scales? (this could allow us to give the gridView a larger base text size)
