### ISSUE TITLE
Chunks don't align properly

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1030]
**Bug** 
Chunks don't align properly.

**To Reproduce**
1. Make a 3-word chunk as the first Track in a Trail.
2. For the 2nd Track, pick a single word, higher up in the conversation (earlier).
3. See that the chunk doesn't align properly.
   
![Chunks dont align properly](https://user-images.githubusercontent.com/22628444/130603953-dba19f0f-e25a-4324-80c4-1224b8c49c27.PNG)

**Comment by terrydubois** [comment]
After trying this for a bit: this seems to happen when you have a situation like the one pictured. That is: 1 or more RezChains are made over a set of units, and then later in those same exact units another RezChain is made with a chunk in it. The chunk is marked as a stretch and will not attempt alignment.
