### ISSUE TITLE
SideLink for Track chains (see #82)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#105]
**Is your feature request related to a problem?**
Track chains can benefit from the same kind of sideLink treatment that is used for Rez chains (see #82 ). 

**Describe the solution you'd like**
If a link in a Track chain connects two words on the same line, treat this problem similarly to the way a sideLink is drawn in a Rez chain, as follows:
1. When drawing the lines for a Track chain, if two words in the same line belong to the same TrackChain, the leftmost word is considered to be the "main" word, and is placed on the "main line" of the Track chain.
2. If any additional words (in this Track chain) appear in the same line, they are considered to be a sideLink. (Copy the code used to solve  #82 , as a model for implementing sideLinks for Track chains.)
3. The line drawn for the sideLink of a Track chain should be slightly curvy, going just under the words of the line.
4. In the continuation of the Track chain to the next line below, be sure to start from the leftmost word (of the TrackChain, when two words are in the same TrackChain) when drawing the link to connect to the next word in the chain.

**Comment by terrydubois** [comment]
Words in side-links of Rez & Track chains do not return to their correct position when moving back. Check void and bring words back in side-links.
