### ISSUE TITLE
Continuation linkLine should be vertical after a SideLink

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#106]
**Is your feature request related to a problem?**
_After_ a sideLink is drawn in a Rez chain chain (see #82 ), the next linkLine of the chain should not be diagonal -- it doesn't look right. Make it vertical, if possible.

**Describe the solution you'd like**
1. This applies **after** a sideLink has occurred.
2. To avoid drawing a diagonal linkLine, the linkLine going to the _next_ line of the Rez chain should start from the leftmost word of the sideLink.
3. That is, the continuation linkLine that goes to the next word in the Rez chain (assuming this word is not another sideLink, but appears in a lower line) should normally be vertical, beginning from the leftmost word of the sideLink (in the upper line).

**Additional context**
The same approach can be used to draw the continuation line (after a sideLink) for a Track chain (not just for a Rez chain).

**Comment by terrydubois** [comment]
This has been implemented on Rez chains. Now implement it for Track chains.
