### ISSUE TITLE
TimeStamps for Link and vizLink

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#107]
**Is your feature request related to a problem?**
We need to keep track of how long it takes users to create links and chains.    
To keep track of user activity, it would be good to have timeStamps for when the user clicks on words to make a link in a Rez chain, Track chain, Stack, etc.

**Describe the solution you'd like**
We need time stamps for Links and vizLinks.
1. When the user clicks on a word (to start the creation of a Link), record the time (measured in seconds from the beginning of the current Rezonator session) and save in a field (column) called sourceClickTime, in the Link table.
2. When the user clicks on the next word (completing the creation of the Link), record the time and save it in a field called goalClickTime in the Link table.

**Future development: VizLink**
1. In the vizLink table, record timestamp information, reflecting the time when Rezonator draws the link, making it visible to the user. The goal is to know when the user was able to see the vizLink. This can be called sourceDrawTime and goalDrawTime.
2. If the link is drawn instantaneously, the sourceDrawTime and goalDrawTime may be identical (or nearly so). But for some purposes, we may draw the linkLine slowly (for certain games, visualizations, etc.), so there could be an interesting difference. 
3. Note that both the Link and vizLink grids will contain some kind of timestamp information, but the values for sourceClickTime and goalClickTime (in the Link table) vs. vs. sourceDrawTime and goalDrawTime (in the vizLink table) will differ.
  
**Additional context**
- This information should be saved into the CSV files for Link and vizLink as well. 
- Ultimately we will have to relate these timestamps (relative time) to the date and time when the user's Rezonator session begins (absolute time), which we will also want to record, for each session in Rezonator.

**Comment by johnwdubois** [comment]
I updated the comment to make clear the need for a separate field for sourceClickTime and goalClickTime.

**Comment by terrydubois** [comment]
Add column in linkGrid for kill time.
Default time for goalClickTime should be the same as sourceClickTime.
This ticket may come back to address the vizLink times.
