### ISSUE TITLE
Avoid spaces in field names

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1192]
**Background**
When exporting/saving a file that will be used in rezonateR, field names that have spaces in their labels (strings) can cause problems in rezonateR.
For example, when importing a Elan tab-delimited file, Rezonator (and/or GameMaker) automatically assigns file names like: 
- "Col 0", "Col 1", "Col 2", "Col 3", "Col 4"....

**Fix**
Avoid spaces in field names when saving them.
1. Automatically assign file names with no spaces, like: 
- "Col_0", "Col_1", "Col_2" ....
2. Alternatively, let users name the columns during the input process.
3. Substitute 1 underscore for each whitespace (= 1 or more internal spaces in sequence). 
4. Leading or trailing spaces, if they exist, should just be stripped out.

**Comment by johnwdubois** [comment]
1. When the user creates a new field name, the text input box, should check for whitespace (space or tab) and not allow it. 
2.  Show the user a message "Will be created as " [replacing whitespace with underscore]
3. Check to make sure that all Rezonator-internal field names do not have spaces (substituting underscore if necessary).

**Comment by johnwdubois** [comment]
Ryan, can you clarify where these field names with spaces are coming from? Corpus data, user input, or Rezonator itself? Can you give examples of cases that have caused problems?

**Comment by kayaulai** [comment]
This was a while ago so I don't really remember what the context of it actually was, but for example, Elan import creates columns like 'col 1' 'col 2' 'col 8'. Certainly the Rezonator-created columns don't have this problem!
