### ISSUE TITLE
Add zero outside of chunk

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1266]
Right now, it is difficult to add a zero that does not belong to a chunk, because adding a zero automatically puts it in the same chunk.

When adding a zero while left-clicking, it would be helpful to have an option to add the zero on the left of the chunk, without being part  of the chunk. This should be added to the current option of putting it inside the chunk, rather than removing the current behaviour, since both behaviours can be useful depending on situation.

For example:

[Have been] there yesterday.

Let's say I want to add a zero to the left of the chunk 'have been'; in this case, this option would be useful.

Alternatively, add a feature to change chunk extent, so that the zero can be removed from the chunk:

https://github.com/johnwdubois/rezonator/issues/387
#387 
#480 

This will be useful for other potential problems related to chunks as well. For example, when there are nested chunks, and the zero should be inside one but outside the other. It wouldn't be worth making a new feature for each of these edge cases, so being able to change chunk extent will be very useful.

**Comment by johnwdubois** [comment]
Lets do this in the simplest way possible. I'm guessing that might be... 
1.  First, implement #480 by letting the user select, for an existing chunk, the (new) first and last token.
2. ?

**Comment by johnwdubois** [comment]
By default, when the user is in a chunk (or rather, focused on a token that is at the edge of the chunk, i.e. leftmost token in the chunk), create the zero outside the chunk.
