### ISSUE TITLE
When splitting a single-token track or rez, offer to turn it into a chunk

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1267]
At the moment, splitting a single-token track or rez will mean that part of it goes outside of the track or rez.

A better approach would be to turn the entry into a chunk, so that both parts of the new token will be within a single entry.

**Comment by johnwdubois** [comment]
The simplest solution is:
When the user is in a rez or track chain, and splits a token in 2, just make both parts into a chunk, without asking the user.

**Comment by johnwdubois** [comment]
Splitting a token into chunk should not place token in chain:
![splitting token into chunk should not place token in chain](https://user-images.githubusercontent.com/22628444/199052946-f2ff7254-e010-4c52-b809-8e99ce4c73e6.jpg)

![splitting token into chunk should not place token in chain 2](https://user-images.githubusercontent.com/22628444/199052940-20f4c1ab-1aa0-42e5-85f3-cf24f8eb5be1.jpg)
