### ISSUE TITLE
Crash when deleting a chunk and then adding a chunk in its place

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1268]
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_newLink
############################################################################################
gml_Script_scr_newLink (line -1)
gml_Script_scr_createChunk
gml_Script_scr_mouseRect
gml_Object_obj_control_Draw_0

Right now I can't reproduce this. I'll add more details when I get more.

**Comment by terrydubois** [comment]
I haven't been able to find this crash through some testing (creating and deleting chunks in chains).

**Comment by terrydubois** [comment]
I may have found this bug by creating a chunk in a rez chain:


___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_chain:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
 at gml_Script_scr_newLink (line 145) -                      var unitInCliqueID = unitSubMap[? "inClique"];
############################################################################################
gml_Script_scr_newLink (line 145)
gml_Script_scr_drawChunks (line 335) -                                    scr_newLink(obj_control.hoverChunkID);
gml_Object_obj_chain_Draw_0 (line 4) -        scr_drawChunks();
