### ISSUE TITLE
Don't lose the user's checkbox information [min]

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1276]
**Background**
Right now it is frustratingly easy for the user to accidentally lose their accumulated checkbox information. For example, the user checks several checkboxes to carefully assemble a subset of 12 different units (or stacks, trails, etc.), intending to do something useful with them. But just one more click on an item somewhere in the left pane makes all that work disappear.

**What to do**
1. Don't lose the user's accumulated checkbox information (checkmarks they have carefully placed in a subset of the visible checkboxes).
2. Adding or removing checks from checkboxes should work like this: The only way to clear all the current checkmarks is to...
- click on "all" at the top of the checkbox column
- click again to clear all of the checkboxes
- start over by selecting the one item you are now interested in.
3. Of course, if you click directly on a (single) checkbox that currently has a checkmark in it, this should remove the checkmark.
4. Make all of the checkbox systems work like this, starting with:
- stack 
- rez
- trail

**Comment by terrydubois** [comment]
We can accomplish this by mimicking Github Desktop's selection/checkbox system.

**Comment by johnwdubois** [comment]
1. Selecting the "more" menu on an individual stack (in the left pane of the stack tab) should ...
- not affect its checkbox (whether checked or unchecked)
- not affect any other checkboxes that are already checked
- have only a local effect on that stack (e.g. rename it)
