### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#129]
**Is your feature request related to a problem?**
We need a standard strategy for testing Rezonator, to make sure that all user-accessible Rezonator functions work as expected: 
- without bugs, and 
- responding to user actions with intuitive results.

**Describe the solution you'd like**
1. Create a plan for testing Rezonator. 
2. If there is a good way to automate some of this, without spending too much time on it, consider doing so. 
3. You may decide to test the following (and combinations/interactions of these):
- making links (Rez, Track, Stack)
- making Cliques (by making Rez chains)
- deleting links (Rez, Track, Stack); including deleting all links in a chain
- Delete a word from middle, end, or start of a chain. 
- Delete a word, and then add it back to same chain. 
- Delete all words from a chain. 
- add a word that's already in a Rez chain to a Track chain; delete the word from one but not the other, etc.
- Recreate chain with the same words. 
- For a word that appears in two chains, delete it from one but not the other.
- reactivate 1: Return to a "finished" chain, by clicking on an already-chained word to add more words to the same chain. (Pickwhip should start from the word you click on.)
- reactivate 2: In Rez mode, click on a word, then Esc (Marks the new chain as dead.) Click it again, to reactivate it as the first word of a new chain.
- navigation in both Main screen and Nav window (especially pageup, pagedown, jump to start, jump to end, home, end)
- views (main screen, search screen, grid view)
- aligning (Rez and Track chains); watch for Race to Infinity
- filtering (Rez, Track, Stack, Clique)
- sorting (especially random sort, reverse sort)
- search (including multiple search)
- all keystrokes on the Help menu should work as advertised
- load two files, create links between them, do a random sort
- save and reload; click on all available options, etc. (make sure everything is retained after the reload, including Links, Chains, Search/Hit grid, Cliques, etc.) 

**Additional context**
1. Check out [GMAssert](https://marketplace.yoyogames.com/assets/8164/gmassert).    
2. Check out [Gamatas (Testing Automation Suite)](https://github.com/gm-core/gamatas).
This looks like it could allow us to create an automated routine to perform testing within GameMaker (but it's old, designed for GMS 1.4).
2. Be sure to test **interactions** between the above functions; for example, filter/unfilter with navigation keys and different sorts, etc.
3. Always test first and last lines of file, and first and last word in a line (both are common environments for errors).    
See also #139 .

**Comment by johnwdubois** [comment]
Check out [Gamatas (Testing Automation Suite)](https://github.com/gm-core/gamatas).
This looks like it will allow us to create an automated routine to perform testing within GameMaker.

**Comment by Georgio-Klironomos** [comment]
I'll be using this ticket as a space to record feedback form new users.

**Comment by Georgio-Klironomos** [comment]
https://docs.google.com/document/d/1aMFDyGkRWP9m4y9L0QYrNLPXrMiDp215SRu3oVUVNOs/edit?usp=sharing  Here's the transcription of the "Phrase Detectives" playtest, includes reactions and answers to my playtest questions by Brady and Terry.

**Comment by johnwdubois** [comment]
For testing, check out [GMAssert](https://marketplace.yoyogames.com/assets/8164/gmassert).    
This is made by FrostyCat, the author of GMLinear, so I imagine it's well made.

**Comment by Georgio-Klironomos** [comment]
The current testing checklist has already proved useful during FPS week by uprooting hidden bugs and crashes. We should continue to keep the checklist a daily practice and not be afraid to add to it.
