### ISSUE TITLE
Keyboard shortcut list in Help system

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1314]
**What to do** 
1. Show keyboard shortcut list in Help system
2. Keys to show
- t: Track tool
- r: Resonance tool
- DELETE: Remove from chain
- p: Filter current chain 
- CTRL-p: Filter all
- c: Show context (between)
- m: One-to-many
- n: Navigation pane (show/hide)
- j: Justify (left/right)
- k: Prose vs. grid display
- l: Text direction (RTL/LTR) 
- w: Word tips (show/hide)
- SHIFT-w: Select wordform display 
- CTRL-w: Edit list  of wordform options
- z: Insert zero before 
- SHIFT-z: Insert zero after
- f: Find next 
- CTRL-f: Find all
- g: Go to line
- v: Quit current view (return to main screen)
- ESC: Quit current view
- CTRL-s: Save file
   
**Screenshot**
"Keyboard shortcuts" should be listed as the first item in the Help list (right after "All").    
       
![Help menu](https://user-images.githubusercontent.com/22628444/210021795-caf8ec84-3fdf-4666-aef1-c18d82646f27.jpg)

**Comment by terrydubois** [comment]
- Shift-z has incorrect key (should be insert zero after)
- Surface should resize properly
- Use regular Noto Sans font
- Switch hotkeys: W and Shift-W
- "Select wordform display" --> "Wordform display"
