### ISSUE TITLE
Automatic field: TrackSeq [min]

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1316]
1. For each track, include a field automatically calculated by Rezonator:
- `TrackSeq` = sequential position of a track in its trail (1,2,3...)
- display this field in the first column, to the left of "GapUnits" (in right pane of Track tab)
- the functionality is similar to calculating GapUnits (so presumably the code is too) 
2. For each resonance, do the same:
- `RezSeq` = sequential position of a rez in its resonance chain
- display this field in a column to the left of "GapUnits" (in right pane of Resonance tab)

**Screenshot**
   
Current UI for trails:   
   
![Trail sequence needs to be added](https://user-images.githubusercontent.com/22628444/213268099-dd72478c-3a77-4aa4-93de-cf15c0709045.jpg)

**Comment by terrydubois** [comment]
Change TrackSeq to TrailSeq. Also add StackSeq.
