### ISSUE TITLE
Display fields in meaningful / original column order

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1317]
**Problem** 
In many Rezonator contexts, the fields are not displayed in meaningful (original) order. In general, the display of columns (and drop-down lists) should NOT be merely alphabetical.
   
**Fix**
1. For all fields in the user's data, display a meaningful column order. Often, this is the original column order, as found in the user's imported file. 
2. Column order for tokens (for Santa Barbara Corpus, e.g. in right pane of Unit tab):
- Order
- Place
- Text (so user can read the convo)
- Transcript 
- Kind
- POS
- others
3. Column order (Generic file) =
- Order
- Text field (so user can read the convo)
- Transcript field (if specified)
- Rezonator automatic fields
- imported fields
- Rezonator-critical fields (e.g. ID -- but this may not be needed at all)
4. Contexts to fix:
- Unit tab (right pane)
- Track tab (right pane)
- Resonance tab (right pane)
- Chunk tab (right pane)
- Search dialogue (drop-down list) 
- Other dialogues (drop-down list) 
- etc

**Screenshots**

The following screenshot shows a display of columns with a meaningful selection of columns, shown in a meaningful order. This should be the default.   
    
![Show fields in meaningful order 04](https://user-images.githubusercontent.com/22628444/210187089-50642148-7db7-497c-a9de-800775f82075.jpg)
   
The following screenshots show problematic order of columns and drop-down options (e.g. alphabetical). They should be replaced with a meaningful order.   
   
Problematic order in Unit tab   
   
![Show fields in meaningful order 03](https://user-images.githubusercontent.com/22628444/210187090-82664bd3-055a-482b-9ecc-05816cc030b5.jpg)
        
Problematic order in Track tab   
   
![Column order](https://user-images.githubusercontent.com/22628444/210106111-1194aa2e-ab3f-4cf4-b3eb-b448efe0f797.jpg)
   
Problematic order in Search drop-down menu   
   
![Show fields in meaningful order](https://user-images.githubusercontent.com/22628444/210186272-19a331cd-b88e-45b2-b332-ba4d9e6f870d.jpg)
   
Problematic order in Search drop-down menu plus Unit tab   
   
![Show fields in meaningful order 02](https://user-images.githubusercontent.com/22628444/210186275-bfab32f8-ae45-42e4-82f9-7610f1ba9dad.jpg)

**Comment by terrydubois** [comment]
To reproduce: do a search and save the file while the search is active. Then, reopen the file and the columns have been reverted to alphabetical order.
