### ISSUE TITLE
Escape from Search filter and Map view

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1321]
**Bug** 
It is hard to escape from (get out of) ...
- a filtered view of the main screen (e.g. once a search has been done)
- the so-called "Grid " view (= "Map" view, for developers only), if a user gets there by accident
Also, the behavior of the "v" key seems erratic currently, and the BACK arrow remains hard to find. 

**What to do**
The goal is to get back to familiar territory (e.g. by restoring the unfiltered view of the main screen).  Provide multiple paths to get "home" to the main screen.
1. Let the user escape from a Search filter (or other filter) by pressing "v" or "Esc".   
2. Pressing "n" for the Nav window should return to the "default" view (Main screen + Nav window on)
3. The BACK arrow should be made large and visible (with both black and white borders, for contrast against any background). 
4. Wherever the BACK button is present, pressing ESC should have the same function (i.e. go BACK)
5. In the same way, it should be easy to escape from the so-called "Grid " view (= "Map" view, for developers only).

**Additional development**
1. We should consider whether to avoid toggling back and forth with "v". 
2. Escaping from a Search should also -- perhaps -- "clear" the search from the main screen (i.e. stop showing hits in blue).

**Comment by terrydubois** [comment]
In the toolbar, add a Home button. This button will always return you to the "home" view, which is the full unit list.
