### ISSUE TITLE
Simplify option to show/hide Nav window

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1323]
Simplify the option to display (show/hide) the Navigation window 
1. Pressing "n" should simply toggle the display of the Navigation window on/off all at once (both panes).
2. There is no need to make available an option to turn on only one of the Navigation panes.  It's okay to disable this functionality.
3. The menu option (View > Navigation) should be simpler too. Selecting "Navigation" from the main menu should do the same action as pressing "n". Simplify the "View" menu as follows:
- Replace "Window > Nav" with just "Navigation" (not "Nav"). 
- Show a checkmark when appropriate. (Treat the "Navigation" option similar to "Word Tip".)
4. Add a button to show/hide Navigation pane
- create new icon: perhaps 2 panes side-by-side, similar to "1-to-many"?
- place button on the toolbar, just below "1-to-many" button, or...
- place button on the top bar, next to language drop-down
    
**Additional menu tweaks**
1. Change order of "View" menu options:
- Navigation
- Toolbar
- Word tip
- Justify
- Prose
- Text direction (add shortcut label "L")
- Arrowheads
- Chunks
- Chains 
2. Change "Hide" to "Chains" (which expands to "Track/Resonance/Stack", same as now)
3. Move the "Tools" option higher in the menu hierarchy:
- Change name from "Tools" to "Toolbar"
- Move to "View > Toolbar"
- Show checkmark when Toolbar is toggled to on/show (same as "Word Tip" etc.) 
4. Change the so-called "grid view" menu option 
- Move it from the "View" menu to the "Advanced" menu
- Change name of the function to "Map view"
- Change shortcut from "CTRL-g" to "ALT-SHIFT-m"".

**Screenshot**
   
Current "View" menu:   
   
![View menu](https://user-images.githubusercontent.com/22628444/210265888-3bfcac4a-1950-44a6-88fd-83f5af8a4015.jpg)

**Comment by terrydubois** [comment]
Still need to complete item 4.

**Comment by terrydubois** [comment]
- Change text "visible" -> "hide"
- Add show/hide eyeball button to Search tab, which toggles whether the searched term appears blue in the Main Screen.
- In Tools menubar dropdown, "Search" should not produce a submenu. It should just search. Also update hotkey Ctrl+F
