### ISSUE TITLE
Update web demo / HTML5 

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1337]
1. Update the HTML5/demo/itch.io release, bringing it into the main line of development for Windows and Mac (as much as possible).
2. Isolate and minimize any necessary differences in code & functionality between HTML5 and PC/Mac, to simplify future maintenance of HTML5 releases.
3. In the long run, seek native GML solutions for web, for:
- file handling
- audio playback

**Comment by terrydubois** [comment]
Still left to do:
- Add REZ files 1-10
- Use Noto Sans fonts with large range (try CJK)
- Disable file menu options (save, media, etc)
- Add other locale files
- Address Ctrl+Click for Mac browser
- Make website buttons open in new tab
- Disable "check for updates"
