### ISSUE TITLE
Allow sidelinks quietly (with words & chunks)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1357]
1. Turn off sidelink warnings, allowing sidelinks to be easily made.
2. If the user says "OK" to make the sidelink, the sidelink is not actually made. But it's not enough to avoid making the sidelink; the whole dialog should not be shown at all.

**To reproduce**
(see SBC002)   
Make a sidelink involving a chunk, as shown in this screenshot.   
See that the sidelink warning is still present, and still annoying.    
(Here, it was triggered by creating a chunk in line 19 while making a track chain. Previous selection was "him" in line 16).   
   
<img width="959" alt="Side-link warning is still present" src="https://github.com/user-attachments/assets/42d83b71-55a3-487d-a51d-1c87e663d890">

**Comment by johnwdubois** [comment]
There is still a problem with sidelinks.   
**To reproduce:**
1. Make a Trail with a few Tracks in it, including  a 2-word chunk.
2. Click on a single word ("he").
3. Then double-click between the 2 words of the chunk. 
4. See message about "side-links".
5. The problem may go deeper than just turning off side links: Why is clicking twice inside a chunk considered a side-link in the first place?

![Image](https://github.com/user-attachments/assets/87074657-7532-4cd3-9853-52e16f41ad67)

**Comment by johnwdubois** [comment]
Done.

**Comment by johnwdubois** [comment]
Still present, still annoying.

**Comment by terrydubois** [comment]
This is now a chunk-only problem.
