### ISSUE TITLE
Random link generator

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#139]
**Is your feature request related to a problem?**
For testing purposes, it may be useful for developers (us) to be able to automatically generate a large number of links and chains (Rez links/chains, Track, Stack, Clique...). 
See also #129 .

**Describe the solution you'd like**
1. Allow the developer/user to automatically create large numbers of (random) links and chains (Rez links/chains, Track, Stack, Clique...) with a single keystroke. 
2. It's as if Rezonator automatically goes through a whole conversation, creating links between words as it goes. These can be arbitrary links/chains.
3. Use a random number generator to ensure a certain amount of (pseudo-)randomness as to what words are selected to be linked, and what chain they will be added to.
4. Allow the user/developer to specify whether the chains to be created should be Rez, Track, Stack, or Clique, or some combination of the above.
5. This is a developer feature, so it should have a keystroke like Alt-Shift-X.

**Future development**
Allow the developer/user to specify some probabilistic values, intended to govern certain properties of the resulting links (on average):
1. Specify a value between 0 and 1 for `Density` (what proportion of the words in a discourse should be included in the random links). 
2. Specify a value between 0 and 1 for `Distance` (how long should the random links be, on average: mostly short links, plus randomly a smaller number of long-distance links separated by many lines).
3. Specify a value between 0 and 1 for `Tilt` or `Cross` (what proportion of links show some Tilt, that is, they deviate from a simple vertical link).

**Additional context**
1. This will make a very useful feature as part of a testing regime. For example, we could have a feature that creates either many, or few, Race-prone links. This will help in testing for Race to infinity. And making a large number of links/chains can help us see if the fps rate slows down.
2. Creating a very complex array of chains will also provide a good motivation to let users simply what they see by choosing to display only Rez chains, or only Track chains, etc.

**Comment by Georgio-Klironomos** [comment]
Though a basic implementation, the current random link generator has given us plenty of insight on how to improve Rezonator's performance.
