### ISSUE TITLE
Cannot open Rezonator (ver 1.2.0/1.3.0, Windows 10)

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1395]
Rezonator 1.2.0  / 1.3.0 do not open for me. I'm on Win 10. Data in My Documents is created as normal (after a prompt from Avast Antivirus to approve the operation). Does not appear in Avast's quarantine centre, nor does any further message from Avast appear.

**Comment by johnwdubois** [comment]
Do we need to add a "retry" loop in Rezonator, if the install process is paused for messages like this from anti-malware software?

**Comment by kayaulai** [comment]
Issue resolved with 1.3.0.1.
