### ISSUE TITLE
Layer tab (for all Stacking, Chainings, etc) 

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1397]
As an alternative to https://github.com/johnwdubois/rezonator/issues/1297, if the stacking system can be easily adapted to chunks/resonance/trails, then it would be really useful to have them there.

Priority-wise, I think having them on chains would be the most useful, as this allows one token or chunk to be part of different chains. Chunks would be next, and rezzes would be the least important since I can't think of any use cases at the moment.

**Comment by johnwdubois** [comment]
Let's do it, and call them all "layers" (after all).

**Comment by johnwdubois** [comment]
1. The "Layer" tab should display a list of all layers, including:
- Stack layers (a.k.a. Stackings)
- Resonance layers
- Trail layers
2. Users can choose one layer of each type (just one, not more) to show on the screen at any time. They can save this selection as a "Picture".
3. Users can select from among various saved "Pictures" to display.
4. Checkboxes and a "More" menu allow the user to select, filter, show/hide, delete, etc. (For example, to select for a .rezx export).

**Comment by johnwdubois** [comment]
Duplicate: This is subsumed under **Layers**. #1460
