### ISSUE TITLE
Eliminate [CTRL-h] as keyboard shortcut

### ISSUE THREAD

**Issue by terrydubois** [johnwdubois/rezonator#1418]
**What to do**
1. _Eliminate_ the keyboard shortcut CTRL-h (used to show/hide participant labels). 
2. When toggling participant labels on/off (via the menu), use a variable to remember the _column width_ for participant labels, as set by the user. (Currently this information is lost each time the toggle is used.) 

**Background**
1. Removing this shortcut is intended to reduce confusion, when users accidentally hide participant labels.) 
2. The option to Show/hide participant labels remains, but is only from the View menu (a standard toggle, with checkmark).

**Comment by johnwdubois** [comment]
To reduce confusion, consider eliminating the keyboard shortcut Ctrl/Cmd H. (If it is kept, then add Ctrl/Cmd H to list of keyboard shortcuts.)
