### ISSUE TITLE
Crashes when drawing resonance

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1429]
The first error appears when linking 'her' and 'me' here:
![image](https://github.com/johnwdubois/rezonator/assets/43101723/11365c78-bb82-40b0-9b69-8a01c37b5f21)

also when starting a new chain on the highlighted 'do':

![image](https://github.com/johnwdubois/rezonator/assets/43101723/a63e8682-8f21-4d7f-bbea-267d8786b163)

and also linking up the 'and's:

![image](https://github.com/johnwdubois/rezonator/assets/43101723/d036d4a1-3bbb-4f30-8902-c1e0211722df)

**To reproduce**
Maybe after merging 2 resonance chains together?   
   
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_setCliqueAutoTags
############################################################################################
gml_Script_scr_setCliqueAutoTags (line -1)
gml_Script_scr_mergeCliques
gml_Script_scr_newLink
gml_Script_scr_tokenClicked
gml_Script_scr_drawLineEntryList
gml_Script_scr_drawLine2ElectricBoogaloo
gml_Object_obj_control_Draw_0

--------------------------------------

A different one, while drawing chunk around 'in the casino':

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_mergeCliques
############################################################################################
gml_Script_scr_mergeCliques (line -1)
gml_Script_scr_newLink
gml_Script_scr_createChunk
gml_Script_scr_mouseRect
gml_Object_obj_control_Draw_0

![image](https://github.com/johnwdubois/rezonator/assets/43101723/e4b1b1a4-a41b-4ed7-bde8-3deb9ed9792a)

**Comment by kayaulai** [comment]
And here's a third one:


___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_cliqueCheckChain
############################################################################################
gml_Script_scr_cliqueCheckChain (line -1)
gml_Script_scr_refreshClique
gml_Script_scr_newLink
gml_Script_scr_createChunk
gml_Script_scr_mouseRect
gml_Object_obj_control_Draw_0


![image](https://github.com/johnwdubois/rezonator/assets/43101723/6fa97fd2-a12c-4bb9-9aa5-1ddfad02d6cb)

**Comment by kayaulai** [comment]
Here's a reproducible example (see screenshot for the action taken).

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_setCliqueAutoTags
############################################################################################
gml_Script_scr_setCliqueAutoTags (line -1)
gml_Script_scr_mergeCliques
gml_Script_scr_newLink
gml_Script_scr_tokenClicked
gml_Script_scr_drawLineEntryList
gml_Script_scr_drawLine2ElectricBoogaloo
[diamond resonance.zip](https://github.com/johnwdubois/rezonator/files/12208678/diamond.resonance.zip)

gml_Object_obj_control_Draw_0


![image](https://github.com/johnwdubois/rezonator/assets/43101723/8d53ed18-173f-4d62-9061-425d2e104b93)

**Comment by kayaulai** [comment]
And a new one!


___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_control:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_refreshChainOrderMap
############################################################################################
gml_Script_scr_refreshChainOrderMap (line -1)
gml_Script_scr_newLink
gml_Script_scr_tokenClicked
gml_Script_scr_drawLineEntryList
gml_Script_scr_drawLine2ElectricBoogaloo
gml_Object_obj_control_Draw_0

**Comment by kayaulai** [comment]
And another new one, when making side links:

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_dialogueBox:

ds_map_find_value argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Script_scr_refreshChainOrderMap
############################################################################################
gml_Script_scr_refreshChainOrderMap (line -1)
gml_Script_scr_newLink
gml_Script_scr_dialogueConfirm
gml_Object_obj_dialogueBox_Draw_0

**Comment by johnwdubois** [comment]
Ryan says:
I've added a reproducible example of the resonance crash to GitHub.....
I hope this bug can be prioritised in the future development of Rezonator, as it's extremely common when dealing with resonance.
JWD: Yes, let's prioritize this.
