### ISSUE TITLE
Bugs and polishes with scrolling the various tabs

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1438]
There are still several issues with scrolling the nav window. I decided to open one ticket for it, since they're likely all interrelated.

- [x] When switching from one-to-many mode to one-to-one mode, one scrolls back to the top. This is undesirable behaviour; I have spent a long time scrolling back and forth because of this. It would make sense to keep the currently focused row constant.
- [x] Currently, the one-to-one tabs do not scroll when one clicks on something in the main window, or vice versa. I don't remember if I've requested this before, but it would be great if this can be done now because I personally scroll a lot because of this, and some students have also mentioned this to me in last year's classes.
- [x] After making a quick stack, the Track pane scrolls to the bottom. I'm not sure why this is the case, but it creates issues for me when I am creating stacks centered around tracks.

It would be a great boost to productivity to have all these issues resolved. Thanks!

**Comment by terrydubois** [comment]
- [ ] "Sync to unit tab" should scroll to correct position, regardless of being in 1-to-many or 1-to-1
- [ ] Double-clicking on left pane should hop main screen to first relevant unit (specifically look at Rez, Track, Stack)
