### ISSUE TITLE
Chunk-box still draws after its chunk has been scrolled off the screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1456]
**Bug**
A Chunk's box still draws at the top of the screen, even after the chunk has been scrolled off the top of the screen.    

**To reproduce**
1. Make a Rez chain with a chunk in line N, and a second chunk in line N+1.
2. Scroll down so that line N is off-screen, but line N+1 is still visible (at the top of the screen).
3. The problem does _not_ occur when scrolling chunks off the _bottom_ of the screen.
4. Do the same for Tracks. Same problem.
5. (It seems to happen regardless of line height and font size.)

**Screenshots**
   
(See SBC002)
   
Rez chain (not good, see the highest line drawn on-screen):   
      
<img width="958" alt="Chunks still draw after they have left screen" src="https://github.com/user-attachments/assets/2b6094d3-aa61-427b-a9e3-252a4b8c4608">
   
Rez chain (good, both chunks on-screen):   
      
<img width="959" alt="chunk box stays on screen after chunk scrolls off-screen" src="https://github.com/user-attachments/assets/725c8b18-bed6-49e7-9891-24371b82436a">
  
Rez chain (not good, one chunk scrolled off-screen):   
      
<img width="959" alt="chunk box stays on screen after chunk scrolls off-screen 02" src="https://github.com/user-attachments/assets/789fa9d3-3b87-4671-9e32-aec558f0df91">
   
Track chain (good, both chunks on-screen):   
    
<img width="959" alt="chunk box stays on screen after chunk scrolls off-screen 03" src="https://github.com/user-attachments/assets/ce8f47b9-2812-4307-bd8e-379795eb807e">
   
Track chain (not good, one chunk scrolled off-screen):   
    
<img width="959" alt="chunk box stays on screen after chunk scrolls off-screen 04" src="https://github.com/user-attachments/assets/17528cf9-2425-43a8-957a-7edb8beea996">   
   
It is not dependent on large line height or font size:   
    
<img width="959" alt="chunk box stays on screen after chunk scrolls off-screen 06" src="https://github.com/user-attachments/assets/558cf44c-473e-44d4-a0cd-34201efb8042">

**Comment by kayaulai** [comment]
Is this specific to rez? I don't recall seeing this, but it might be because I haven't done any resonance annotations for quite a while ...

**Comment by johnwdubois** [comment]
It might be specific to rez links -- perhaps because of Cliques?

**Comment by johnwdubois** [comment]
I think I can reproduce it now -- see above. (It is not limited to Rez chains.)

**Comment by terrydubois** [comment]
This problem stems from having the Nav window turned off. There are also some behavioral bugs related to this:

- [ ] New chains (rez, track, and stack) auto-deselecting when made on tokens that would be hidden by nav window (specifically, tab region)
- [ ] Units sometimes do not draw at the very top of the screen
