### ISSUE TITLE
Match Trail color to Participant color (for first person reference)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1461]
**Goal**
For trails consisting of first person reference (when a speaker uses "I" to refer to themselves), use color-coding to display the unique connection between the self-reference (Trail) and the speaker (Participant label). 

**What to do**
1. In the rightclick menu for Trail, show an option:
- "Recolor" > "Match Participant color"
2. If this option is selected, make the Trail color match the (pre-existing) color for the currently selected participant (i.e. the speaker of the unit that contains the self-referential pronoun "I").
3. Show confirmation dialog: "Match color of X?" {Cancel, Recolor} [where X = Participant name/label]

**Fancy** 
Once this option is set, any changes to the color of the Participant label should be automatically inherited by the Trail color (i.e., Trail is re-colored to match Participant).   
**Screenshot**
   
In this example, the Trail consisting of Harold's self-reference ("I") would be re-colored to match the color used for Harold's speaker label.   
   
<img width="762" alt="Color-coding for speaker first person self-reference" src="https://github.com/user-attachments/assets/16c85df8-912e-419a-9a1f-2755b30c97a3">

**Comment by kayaulai** [comment]
Lol I've been doing this fakely by spamming randomise till I got something similar!
