### ISSUE TITLE
Chunks should remain existent after being delinked from a trail/resonance

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#1488]
**Background**
As of now, delinking any chunk from a trail/resonance, i.e. deleting the track/rez, will delete the **chunk itself**, even if the chunk itself used to be a blank chunk. This will create many problems for people who have annotated lots of blank chunks, and then just accidentally put a blank chunk into a trail.

In fact, I believe it would be necessary to remove the chunk-deleting behaviour of delinking in order to properly implement layers; for there to be trail layers, a chunk shouldn't be inextricably associated with a single track.

**What to do**
So I propose that:
- Executing Remove link on a chunk-track should remove the link ONLY, leaving the chunk intact
- The same goes for delete key.
- Delete key for blank chunks should delete the chunk itself, as always.

Additional info
Consider deleting the chunk IF it is a "low value" trail or resonance (kind of like CTRL-z); see

**Comment by johnwdubois** [comment]
I agree.
