### ISSUE TITLE
Each new Layer should restart auto-generated names  from 1

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#1492]
Each new Layer should have its own accounting for auto-generated names within the layer.    
For example:    
For each new Trail layer, reset auto-generated names to: Trail 1, Trail 2, Trail 3...

**Comment by terrydubois** [comment]
Each layer, on each tab, should get its own counter variable (that only increments) that we use to name new chains. These variables should be saved to the REZ file so the user can continue with that naming convention through multiple sessions.
