### ISSUE TITLE
Words aren't being pushed in Filter mode

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#15]
**Describe the bug**
When in Stack mode (filtered), when you make a rez link the word moves behind another word, as if it doesn't "know" it's there.

**To Reproduce**
1. Make a stack by adding a line, then skipping over several lines, adding another line, etc.
2. Make some vertical rez chains (that line up nicely in column X).
3. Start a new rez chain with the first word outside column X, then click on a word in column X.
4. See the problem: The new rez chain also occupies column X, and some of its words are behind the words that are already present in column X.

**Expected behavior**
When you make new rez chains, make sure the positions of words update. Check to make sure that this works while in stack mode, etc.

**Screenshots**
![rez bug - words hiding behind words](https://user-images.githubusercontent.com/22628444/44625225-06e2dc80-a90d-11e8-8dd1-828d19d51a17.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by terrydubois** [comment]
This bug happens in any Filter mode when creating new aligned chains. In Filter mode, words do not know when they should be pushed.
