### ISSUE TITLE
"Go to line" needs to specify which discourse (discoID) to search in

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#156]
**Is your feature request related to a problem?**
The "go to line" function seems to assume there is only one discourse at a time.

**Describe the solution you'd like**
1. The "go to line" function should check how many discourses (discoID) are loaded. 
2. If only one, then it can function as it currently does.  
3. If more than one, it should first offer a dialog box allowing the user to select which of the currently loaded discourses to search in.
4. Then, a second dialog box lets the user type in the line to go to.
5. Be sure to test the "go to line" function with a non-standard sort (e.g. lines in reverse order of uID).

**Additional context**
See #84 .

**Comment by johnwdubois** [comment]
Currently, "Go to line" lets you specify a DiscoID, but doesn't actually go there - only goes to the first Discourse.
Also, "Go to line" should incorporate the DiscoID into a single dialogue box.    

![Go to line only goes to first disco](https://user-images.githubusercontent.com/22628444/54089834-fad4de80-4375-11e9-82fa-1e52c6cc5ee3.PNG)

**Comment by terrydubois** [comment]
Pane is still trying to keep letters:
ERROR
unable to convert string "sdada" to number
 at gml_Script_scr_jumpToLine (line 17) - var lineNum = real(lineStr);
