### ISSUE TITLE
Join chains

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#179]
**The problem**
Sometimes a user invests a lot of time in making a long Chain, and then realizes it actually belongs together with another existing Chain.    
What the user needs is a way to join the two Chains into a single Chain.

**What is needed**
1. Users should be able to:
- Join two chains to make one longer chain
- Join two stacks into one larger stack
2. A Join should only be allowed between two chains that are of the same type:
- both are Rez chains 
- both are Track chains
- both are Stacks
- etc.
3. How the user does it:
- first click any word in on one chain, to focus the chain
- then click on any word in the second chain (the one you intend to merge with)
- a dialogue box pops up for confirmation {Okay, Cancel}         
4. While it should be easy for a user to join two chains, it should also be confirmed (since it's a risky action). Show a dialogue box with the following message (as appropriate): 
- "Join this Rez chain with another Rez chain? (Cannot be undone)" 
- "Join this Track chain with another Track chain? (Cannot be undone)" 
- "Join this Stack with another Stack? (Cannot be undone)" 
- Options: {Okay, Cancel} 
5. When the user is about to Join a Stub chain with a regular chain (or vice versa), don't bother to show a confirmation dialogue - just do it! (This is not really a risky operation, so no confirmation is needed.)
6. Retain the original clickTimes from the original Link and LinkViz table. Just reassign the ChainId.

**Additional development**
It may be useful to visually highlight the two Chains that are about to be Joined. (If this is hard to do, don't bother.)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois A prototypical implementation has been made by Brady and Terry, and work for both Rez chains and Track chains. Next up is making it work for Stacks and testing the heck out of it.

**Comment by Georgio-Klironomos** [comment]
We'll need to adjust this feature for the Mac builds, as CTRL functions differently on those keyboards.

**Comment by Georgio-Klironomos** [comment]
Combine chains now uses the Command key for the Mac, making it full functional for both platforms.
