### ISSUE TITLE
Search results on Main screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#181]
**The issue**
Sometimes a user wants to see Hits in their full context, that is, highlighted in the main screen.

**What is needed**
1. When the user searches for a word, show all Hits (words that meet the search criteria) by highlighting them "in place" on the main screen, that is, as part of the normal view of a conversation.
2. For this function, there is no need to switch to the Search screen; the user remains in the Main screen.
3. By default, the highlighting of Hit words persists until another search is performed; but also give the user a way to cancel the highlighting (i.e. return to normal).
4. The form of the highlighting might be:
- boldface
- font color = dark blue
- yellow fill color for the word (light yellow, low saturation, high transparency)

**Additional context**
This is closely related to #41 and #58 .

**Comment by kittynugget** [comment]
- added in new check to word draw functions in both search and main page results. found words are colored dark blue currently.
