### ISSUE TITLE
Rainbow stack is back

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#184]
**Describe the bug**
The rainbow stack is back. You can create mixed colors in a single line, by using QuickStack to extend a Stack.

**To Reproduce**
1. Make about 3 Stacks, using QuickStack. Leave a few lines in white (un-stacked) between the Stacks.
2. After making Stack 3, go back to the last line of Stack 2. Click-drag on the Speaker labels to draw a QuickStack.
3. Notice the mixed color in one of the lines.

**An example**

![rainbow stack is back](https://user-images.githubusercontent.com/22628444/54035831-dd134800-41c2-11e9-8ddf-ad3366b587e6.PNG)

**Expected behavior**
1. It should not be possible to assign one line to two different stacks. And it should not be possible to get two different Stack colors in one line.
2. We may need a more robust solution than the current one to keep this from cropping up again in the future. 

**Additional context**
See also #140 and #183 .

**Comment by johnwdubois** [comment]
It's baaack - on steroids.   
![rainbow stack on steroids](https://user-images.githubusercontent.com/22628444/55282926-cb027080-534e-11e9-90ee-377ff1565527.PNG)

**Comment by johnwdubois** [comment]
It's baaaack!
(But maybe not quite as bad as before.)
I was doing a mix of QuickStacks, dragging the mouse in the speaker column; drogging from down to up, etc.)
I repeat what I said before: It shouldn't even be possible to have two different Stack colors in one line, so we need to go deeper on rethinking what the problem is here. The whole method for assigning lines to Stacks seems problematic.

Time to test with gamatas?

![rainbow stack is back 0-8-32](https://user-images.githubusercontent.com/22628444/56504697-0cd3a080-6522-11e9-89e4-cb2cdf6fb827.PNG)

**Comment by Georgio-Klironomos** [comment]
I've added checks to prevent the quickStack from clicking on a unit that's already stacked, which hopefully prevents the possibility of a rainbow.

**Comment by johnwdubois** [comment]
I think that's an artificial (or superficial) way to block rainbow stacks. It should be done deeper, in the data structure itself. That is, the lists of lines/units/words that are created to mark membership in a stack should not allow for membership in more than stack.

Here's one more case of rainbow stack. It may have something to do with blank lines in the middle of a stack, followed by deleting a line, followed by adding a line. In SBC005, drag down over lines 1 to 7. Notice that line 5 is not in the Stack (because it has no words). Then play with deleting lines from the Stack, then hit Esc to start a new Stack, and click on an existing line. Doesn't always create a rainbow, but maybe the blank line gives a clue to the problem.

![rainbow stack is back 0-8-32 2](https://user-images.githubusercontent.com/22628444/56572132-1ebb4f00-65c7-11e9-8a5a-2f06107668fe.PNG)

**Comment by johnwdubois** [comment]
I now have a reliable way to make rainbow stack.
1. With the Stack brush activated, drag down over several lines, to make a QuickStack.
2. Hit Delete, to delete the last line of the Stack.
3. Now click on the last (colored) line that remains in the Stack.
4. See that the line has two colors. It shouldn't. (See the screen shot below.)

By the way:
1. It's harder than it should be to delete all the lines in a Stack, with successive presses of the Delete key. This sometimes works with a freshly made Stack, but not when going back to an old Stack (which requires you to click a line, then Delete, then repeat -- too tedious).
2. The color for Stacks no longer extends rightward to infinity -- somehow this nice feature went away. 

![rainbow stack is back 0-8-32 3](https://user-images.githubusercontent.com/22628444/56573841-9d65bb80-65ca-11e9-9198-eeb7bbbdee18.PNG)

**Comment by johnwdubois** [comment]
More rainbow stack weirdness. This one is after making a QuickStack on lines 207-212, then deleting all the lines from this Stack,, then using QuickStack to again mark the exact same lines. Apparently they don't get fully deleted.
I suspect the whole "UnitInStack" system needs to be rethought, and replaced. This calls for some pair programming, I think.     

![rainbow stack is back 0-8-32 4](https://user-images.githubusercontent.com/22628444/56614325-74bce080-6621-11e9-9372-a126c7a9a273.PNG)

**Comment by johnwdubois** [comment]
I now have a reliable way to make a Rainbow Stack. That's good, sort of.

**Steps to reproduce**
1. Open a new file (e.g. SBC007).
2. Before doing anything else, scroll down to line 20 or so.
3. Click on a space between two words, and drag down (to make a QuickStack).
4. See the Rainbow Stack.
5. Also, notice the "volunteers" - Rainbow lines among the first few lines of the discourse (which were not included in the click-drag).

**What to do**
1. A deep think may be required to solve this problem at the level of the root cause.
2. This is needed, rather than another round of whack-a-mole: putting limits on superficial aspects of the problem as it appears in the coloring of lines, instead of preventing the deeper problem before it is encoded in the data.
3. Is "UnitInStack" the problem? Is there an alternative?
