### ISSUE TITLE
Limit column resizing in the Search screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#186]
**Describe the bug**
When in the Search screen, choosing too small a column width can cause letters to get jumbled on top of each other.
This is related to #104 .

**To Reproduce**
1. Do a search for the word "the".
2. Make the column width as narrow as possible.
3. See the words get written on top of each other.

**An example**

![limit column resizing in the search screen](https://user-images.githubusercontent.com/22628444/54044162-f0301300-41d6-11e9-8591-a0e2fb121fc8.PNG)

**Expected behavior**
1. Put a limit on column resizing in the Search screen. Don't let the columns get too narrow.
2. If possible, do allow a larger font in the Search screen.

**Another useful behavior**
If possible, allow the Justification ("j") toggle to function in the Search screen. This should close up the space between words, closely aligning the words, centered on the Hit word.

**Comment by terrydubois** [comment]
Have center-aligned justification be default view for search view. This can be toggled with "J."
