### ISSUE TITLE
Search: Formatting of hit words

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#20]
**Is your feature request related to a problem?**
When looking at the results of a concordance search, it's not immediately clear where the hits are. 
 
**To see the issue**
Do a search for the word 'the' (with 'f'). Notice how it might take a while for the new user to see what they're looking for (the hit words).

**Describe the solution you'd like**
The visuals for displaying hit words in a search should be more clear.
1. When viewing search results, the hit wors should be:
- in color (e.g. deep blue)
- boldfaced
- centered.
 2. They should also be centered on the screen better. That is, centering of the zero column (for search results) should take into account the width of the text, excluding the left margin (i.e. excluding line numbers and speaker labels).
3. The Justify function ("J") should work with the Search screen. While keeping the Hit word (e.g. the word "the", if that was the Search word) centered in Column Zero, this would bring the left context words and right context words in closer to the Search word (i.e. with normal text spacing, rather than grid spacing).

**Note**
Note that in this view, a search hit should only be boldfaced when it is in the center column (not just anywhere on the screen). 

**Describe alternatives you've considered**
You could highlight the search hit (e.g. 'the') anywhere the word appears on the screen, but this is not the desired result, for this kind of search.

**Comment by kittynugget** [comment]
- Added in new check to word draw functions in both search and main page results. found words are colored dark blue currently. 
- Similar to #181
