### ISSUE TITLE
Update the Menu

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#211]
**Describe the solution you'd like**
Update the Menu by: 
1. Show the Advanced menu
2. Add the Dark theme 
3. Provide a live link to download Rezonator etc, using the notation in the  table below
4. Make various changes to descriptions etc., as shown in the  table below  

**Key**  |  **Function**  |  **Description**  |  **Menu**   |
---  |  ---  |  ---  |  ---  |  
[drag word]      | QuickLink    |   Drag from word to make multiple Links   |   Link    |    
[drag line]      | QuickStack    |   Drag from line to make a Stack |   Link    |    
b       |  Box  |   make a Box around some words  |      Link    |    
p      | Pick   |   add focused element to pickList   |   Pick    |    
w       | Word-form |   display words vs. transcriptions  |    View    |    
v       |  View  |   view main screen  vs. search screen  |      View    |    
CTRL-b       |  Dark theme  |   use Dark theme  |      View    |    
ALT+SHIFT+e  | Shuffle   |   sort lines in random order  |      Advanced     |    
ALT+SHIFT+u  | User-word   |   insert a new word   |  Advanced    |     
ALT+SHIFT+d  | Developer   |   turn on developer variables and messages   |  Advanced    |    
...          | Download    |   [Download Rezonator](https://rezonator.com/download/)   |  About    |     
...          | About us   |   For more information, go to [Rezonator.com](https://rezonator.com/)   |  About    |     

**Additional context**
See [Menu](https://github.com/johnwdubois/rezonator/wiki/3.-Functions#menu).
Related to Menu #38 .

**Comment by Georgio-Klironomos** [comment]
Advanced menu now shows, added new descriptions and dark theme. Clicking the About sections will open the user's browser to the respective URL's

**Comment by johnwdubois** [comment]
1. Change the keystroke for Shuffle to ALT+SHIFT+e (like the other Advanced functions).  It's too dangerous otherwise!          
1. Make Shuffle be a toggle, so that the second time you press it, it "unshuffles" - that is, restores the default sort order. 
3. Look carefully at the table in this Ticket -- some Menu items have not been correctly updated.

**Comment by Georgio-Klironomos** [comment]
Menu has been updated, just need to update the Shuffle functionality.
