### ISSUE TITLE
Crash on Clique Zero

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#217]
**Describe the bug**
There were several Cliques listed in the Nav window (Clique 1, Clique 2...).
The last one was named just "0" (not Clique 0). When I clicked on it, it crashed.

**To Reproduce**
1. Not sure.
2. There may have been a fake Clique made automatically in the first few lines of the discourse.

**Expected behavior**
Don't make fake Cliques.   
Don't display a Clique named "0"; if you do, and user's click on it, don't do anything. (But this doesn't really resolve the underlying cause of the bug....)

**Screenshots**
![Crash on Clique Zero](https://user-images.githubusercontent.com/22628444/56503812-41922880-651f-11e9-9312-c8901c2487a2.PNG)

**Comment by Georgio-Klironomos** [comment]
Terry and I added supplemental checks to keep the clique grid and the clique display grid at the same exact size, hopefully ridding us of ghost cliques.
