### ISSUE TITLE
Excess volunteers in QuickLinks

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#220]
**Describe the bug**
When making a QuickLink near the beginning of a file, some "volunteer" words appear among the Rez links, when they shouldn't.

**To Reproduce**
1. Open file SBC005.
2. Click on the last letter of the word ''Pollyanna" in line 10.
3. Drag down and to the right.
4. See that a bunch of words above line 10 get marked as part of the QuickLinks. They shouldn't.
5. It also happens in other files, e.g. SBC004.
6. It seems to only happen the first time a QuickLink is made. Once  

**Expected behavior**
QuickLinks shouldn't create RezLinks on words above the first line of the drag.

**Screenshots**
![Volunteer words in QuickLinks](https://user-images.githubusercontent.com/22628444/56510090-7dce8480-6531-11e9-9245-3e2d5e295861.PNG)

**Additional context**
It's probably best to implement the **SnapToGrid drag #222** first, and then address this. 
This might also be related to #218 .

**Comment by Georgio-Klironomos** [comment]
Discovered when volunteers were being made, and now the MouseDragRect is disabled until that time is passed. This solution doesn't get in the way of using the MouseDragRect, and I haven't been able to replicate the volunteers since.
