### ISSUE TITLE
Drag with SnapToGrid

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#222]
**Is your issue related to a problem?**
Dragging to define a box or a line (whether by mouse or by gesture) is an important input form for Rezonator. But making it work well for Rezonator depends on the script being aware of key Rezonator structures, such as cells, lines, rows, columns, and words.

**What is needed**
We need a strong, robust, and general system for dragging in Rezonator. It should be usable across many different contexts, for both data markup and playing games. It should work whether the goal is to form a box or a line (and maybe even for a "wrap", which is a convex polygon).    

Right now the system is too dependent on x/y pixel values, which are often too specific, and not abstract enough or general enough to work efficiently with the grid and cell structure of Rezonator. It's okay to start with pixels, but we should follow a `SnapToGrid` strategy to convert them to more abstract (and more useful) values based on the cell structure of the main screen in Rezonator. 

In sum, `SnapToGrid` converts overly specific x/y pixel values for the cursor location into a more generalized, and more useful, cell-based location (with coordinates that reflect the _relevant_ cell values). This will improve the efficiency of marking QuickLinks (#218) and Chunks (#24), among other things. 

**Definitions of Key Locations**
1. Where the drag begins:
- `DragOriginPoint` = x/y pixel value of the precise point where the user starts the drag. 
- `DragOriginCell` = the cell (defined by display row and column values) where the user starts the drag. 
- Crucially, the `DragOriginCell` has four bounding points (vertices), each with its own x/y pixel values. These points should be sensitive to the height and width of the display column (as set by the user). Depending on the drag direction, Rezonator needs to decide which of the four points to use for drawing the `Box`. This requires some subtle reckoning, as will become clear in what follows. 
2. `DragDirection` = {down, up, right, left, southeast, southwest, northeast, northwest}
3. `DragAngle` = {straight, diagonal}
- If `DragDirection` = {down, up, right, left}, then `DragAngle` = straight
- If `DragDirection` = {southeast, southwest, northeast, northwest}, then `DragAngle` = diagonal
 
**How to draw a box**
1. The Box will be drawn as a rectangle from the 'LeadingPoint' to the 'TrailingPoint' (each of which has an x/y pixel value).
2. As the user drags in a certain direction, relative to the `DragOriginPoint`, they create at least four additional data points:
- `LeadingPoint` = the point where the cursor is currently (x/y coordinates)
- `LeadingCell` = the display cell where the cursor is currently (row/column coordinates)
- `dragDirection`: Classified into one of 8 categories, as defined above
- `dragAngle`: Classified into one of 2 categories, as defined above 
3. Meanwhile,  we need to calculate a `TrailingPoint` which has the x/y coordinates of one of the four corners of the `DragOriginCell`.
4. If the `DragAngle` = `diagonal`, the `TrailingPoint` depends on the `DragDirection`, as follows. Basically, the `TrailingPoint` _snaps_ to the grid at the **_opposite endpoint_** of the `DragOriginCell`, relative to the diagonal drag, as follows:
- If `DragDirection` = southeast, then `TrailingPoint` = min(x), min(y) of `DragOriginCell`
- If `DragDirection` = southwest,  then `TrailingPoint` = max(x), min(y) of `DragOriginCell`
- If `DragDirection` = northeast, then `TrailingPoint` = min(x), max(y) of `DragOriginCell`
- If `DragDirection` = northwest, then `TrailingPoint` = max(x), max(y) of `DragOriginCell`
5. As the user continues the diagonal drag, draw a box from the `TrailingPoint` to the `LeadingPoint`.
6. Meanwhile, if the `DragAngle` = `straight`, instead of a `TrailingPoint` there is a `TrailingEdge`.   We need to calculate the `TrailingEdge`, which is a line segment equivalent to one of the four edges of the `DragOriginCell`.
6. The `TrailingEdge` depends on the `DragDirection`, as follows. Basically, the `TrailingEdge` _snaps_ to the grid at the **_opposite edge_** of the `DragOriginCell`, relative to the leading edge of the drag, as follows:
- If `DragDirection` = down, then `TrailingEdge` = min(y) of `DragOriginCell`
- If `DragDirection` = up,  then `TrailingEdge` = max(y) of `DragOriginCell`
- If `DragDirection` = right, then `TrailingEdge` = min(x) of `DragOriginCell`
- If `DragDirection` = left, then `TrailingEdge` = max(x) of `DragOriginCell`
- (Obviously we need to fill in more detail here: we need the x/y coordinates of the points at each end of the 'TrailingEdge` line segment, but you get the idea.)  
7. The `LeadingEdge` = a line segment parallel to, and vertically aligned with, the `TrailingEdge`, whose vertical position is determined by the user's current mouse location. This responds continuously to changes in the user's mouse position. (That is, it does not snap to the grid, until it is released.)
8. Once the user releases the drag (`mouseUp`), evaluate which cell the 'LeadingEdge' is in, and snap-to-grid to **include** the whole cell (following a strategy similar to that outlined above).
9. To determine whether a mouseDrag is straight (up/down, left/right) or diagonal, it is important to allow the user a margin of error for "straight" drags. Once the threshhold of the margin of error is exceeded, the drag is reclassified as a "diagonal" drag. For "straight" drags, the margin of error of the `LeadingPoint` is equal to:
- the width [(min(x) to max(x)] of the current column, when `dragDirection` =  {up, down}  
- the height [(min(y) to max(y)] of the current row, when `dragDirection` = {left, right}
10. For diagonal drags, the `LeadingPoint` goes outside of the above limits.
11. Depending on whether the `dragAngle` is straight or diagonal, the box displayed should adjust accordingly:
- If `dragAngle` = straight and `DragDirection` = {down, up}, the box is exactly one row high
- If `dragAngle` = straight and `DragDirection` = {right, left}, the box is exactly one column wide
- If `dragAngle` = diagonal, the box is sized to reflect the actual distance between the `TrailingPoint` and the `LeadingPoint`.

**Additional context**
This snap-to-grid system should be used wherever it is applicable; for example, in #218, #205, #220, #172, and #24.

**Example**
As an example of how SnapToGrid could be used, consider the following example (from SBC006). The user may want to mark some multi-word Chunks or Spans in lines 10, 11, 13, and 121. Assuming the "Chunk" brush has been activated (#24), in line 10 the user would drag horizontally from the word "this" to the word "thief" (or from "thief" to "this"). This would create a single box extending enclosing the words "this former car radio thief".  Similarly, in line 13 the user can drag across the words "her ex-boyfriend" (dragging in either direction) to mark them as a single Chunk.    
(In this example, the sideLink notation (borrowed from Rez chains) is intended to stand in for markup of a Span/Chunk. But in the actual Span/Chunk notation, no SideLinks would appear. Instead, the Span (sequence of words on the same line) would be surrounded by a single bounding rectangle (Plate).    

![track chain with spans-chunks - example](https://user-images.githubusercontent.com/22628444/53804255-b7cad380-3f4f-11e9-8c5f-23757fcec78a.PNG)

**Comment by johnwdubois** [comment]
1. The drawing of Box and Chunk should follow the _**"spirit"**_ of this discussion of SnapToGrid, even if it doesn't follow all the details of the implementation described above.
2. The drawing of Box and Chunk should be closely coordinated with Gestures #70 , especially regarding the setting of the `ActivityState` based on where the drag begins.
3. The height of the Box (and Chunk) needs to scale up with increasing font size.  
4. It would look a lot better if the right side/edge of a Chunk (or a one-line Box) was scaled to match the length of the rightmost word in the Chunk (or one-line Box), instead of matching the size of the rightmost cell (as is done now). The goal is to give the Chunk/Box visualization a "tight" fit, narrowly enclosing the actual words, rather than the cells they occupy. 
5. In the same vein, for a multi-line Box, the right side of the Box can be scaled to the longest word in the rightmost column of the Box.)

**Comment by Georgio-Klironomos** [comment]
Rezonator now communicates exactly what each possible gesture does, both before and after. The user will know what their mouse click or drag will do based on their starting position within the "grid" and their direction, making it simple for us to select which mode they need to be in.
