### ISSUE TITLE
Empty filter should reset to no filter

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#224]
**Is your feature request related to a problem?**
If the user has some Picks selected, and Filters on them, and then removes the last Pick, all you see is a big blank screen. Confusing for the new user.

**Describe the solution you'd like**
If the user has removed the last Pick, remove the Filter (button "F" in upper left corner of Nav window), so that the blank screen is replaced by the normal discourse view, of a full screenful of conversation.

**Comment by Georgio-Klironomos** [comment]
Rezonator now deactivates the filter is the user has removed the last pick, hopping them back to the main screen where they left off.
