### ISSUE TITLE
Move counter

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#226]
**Is your feature request related to a problem?**
For playing games (like Rezzles #199 ), it's better to count moves than to run a clock. This encourages thoughtful play, where every move counts (but not every second).   
For other games, a timer may be preferable.

**Describe the solution you'd like**
1. For every move the user/player makes, add one to the `moveCount`.
2. What should count as a move is not always obvious, but we can start by counting each of the following as one move:
- one click
- one click-and-drag (mouseDown-mouseUp)
- one pick (e.g. pick the current Stack
- one filter or un-filter
3. The click-and-drag rule benefits the player who knows how to use QuickLink and QuickStack strategically, which is good.
4. Designing a move counter that can be tuned to which game you're playing seems like a good idea. Play testing the move counter will be important, to make sure it feels "fair" and promotes interesting game play.

**Describe alternatives you've considered**
1. Of course, as in timed chess, it may sometimes be useful to _also_ use a timer, to encourage players to move things along reasonably fast. But the penalty should be moderate: one point off for each 10 seconds might be good place to start. Or bump up the time penalty slightly for each additional 10 seconds. 
2. (And then of course there's the player who simply stepped away from the computer.... so maybe after a certain point, pausing the game and presenting a dialogue asking "Pause the game?" would be good.)

**Comment by kittynugget** [comment]
- created a debug variable called moveCounter located in obj_control for counting moves in rezzles. use alt+shift+Q to reset back to zero

**Comment by johnwdubois** [comment]
It's time to implement this as a feature in Rezonator, displaying both the Move Counter and the Game Clock in the Nav Window, along with a Reset button. We need it for play testing.
