### ISSUE TITLE
Crash when searching for number

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#227]
**Describe the bug**
Crash when searching for an integer, as the first action.

**To Reproduce**
1. Open a new file.
2. Immediately do a search (with "f" key) for an integer.
3. See the crash
4. Is searching for integers a problem? Or just when the first action is a search. 
5. Error message:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Key Press Event for F-key Key
for object obj_control:

local variable oldSearch(100003, -2147483648) not set before reading it.
at gml_Script_scr_searchForWord
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scr_searchForWord (line -1)
gml_Object_obj_control_KeyPress_70

**Comment by Georgio-Klironomos** [comment]
Quick fix, it was just checking the wrong variable.
