### ISSUE TITLE
View key doesn't work when Search and Filter are both active

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#231]
**Describe the bug**
When the user has done a Search, and then applies the Filter, they can get trapped, unable to the switch between the Main screen and Search screen (using the V key).     

**To Reproduce**
The problem seems to be that the View key doesn't work as expected when the user has created a Hit grid (using Find), and there is also a Filter in place.    

1. Open a file (for example, SBC012).
2. Make a few QuickStacks at the beginning. Make sure some of the Stacks include the word "the", and some do not. 
3. Do a Search for a common word (e.g. "the"). Notice that the Stack colors appear in the Search screen, but only if the Stack had the word "the" in it. That's a good result.
4. Use the V key to switch back and forth between the Search screen and the Main screen. Notice that the switch works easily.
5. When in the Main screen, Pick a few of the Stacks; then apply the Filter (F).
6. Use the V key. Notice that the expected switch back to the Search screen doesn't happen. 
7. Now try the reverse. Unclick the Filter, then use V to switch to the Search screen. Then apply the Filter again.
8. Use the V key again. Notice that the expected switch back to the Main screen doesn't happen.
9. Search for a rare word, like "Greeks" (which occurs once in SBC012, in line 459. Try the same experiments above, with the V key.
10. Create a Stack that includes the word "Greeks" in line 459. Repeat the experiments above, with the V key.
11. Play around with these two searches, and the Filter on or off. Notice when V works to switch screens, and when it doesn't.

**Expected behavior**
Make sure the V key works, letting you switch between Main screen and Search screen, whenever the two screens exist (whether a Filter is applied or not).
 
**Screenshot**  
![View toggle doesnt work w Search plus Filter](https://user-images.githubusercontent.com/22628444/57181719-dee64880-6e9f-11e9-9149-1ef3bff479f6.PNG)

**Comment by Georgio-Klironomos** [comment]
V key can now switch freely between the main screen and the search screen when the filter is active

**Comment by Georgio-Klironomos** [comment]
V now switches correctly back to the filter screen, if filter is active, right after the search is activated.
