### ISSUE TITLE
Canceling a Save forces a failure to save

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#232]
**Describe the bug**
Canceling a Save creates a failed Save. This is serious.    
Instead, canceling a Save should let the user return to the file they were working on, and try the Save again.  
Also, when Saving a file, canceling can give misleading or mixed messages.    
It may be time to bite the bullet and substitute Samuel Venable's dialogue module for the current dialogue.

**To Reproduce**
1. Open a file, and make a few Stacks or Chains.
2. Press CTRL-s to begin to Save the file.
3. Notice that the message "Saving" appears in blue in the upper right corner. This is premature, because the Saving isn't really happening yet. See the following screenshot:   

![Saving message appears too early](https://user-images.githubusercontent.com/22628444/57180155-865a7f80-6e8e-11e9-912f-c0b197ffe74a.PNG)

4. Now try canceling the save. Still the message is misleading. If the user cancels, they may think they've saved, because the blue message still says "Saving" - but they haven't actually saved. 
   
![Saving message - cancel gives mixed messages](https://user-images.githubusercontent.com/22628444/57180256-70998a00-6e8f-11e9-85ca-accce093cc22.PNG)

5. As a final experiment, begin the saving process once again, but before completing it, resize the window (with the Windows resize button in the upper right corner). Notice that the Rezonator window goes all white. Worse yet, it covers up the dialogue box. A sophisticated power user will find the hidden dialogue box eventually, but the unsophisticated user may feel that Rezonator has lost their data, and left them stuck with no way to get Rezonator to respond. Not good. See the following screenshot:    

![Saving  - resizing the window in midsave makes window go all white ](https://user-images.githubusercontent.com/22628444/57180306-fe757500-6e8f-11e9-8f9e-dcc300dc8847.PNG)

**Expected behavior**
1. IMPORTANT: Canceling a Save anytime before completing it should return the user to the file they were working on, so they can have the option of continuing to work on it.
1. When the user presses CTRL-s to start the Save process, don't show the "Saving" message right away. Show it only after they've finished all the necessary steps of inputting the filename etc, and have hit the Okay button.
2. When the save really does begin, make the blue Saving message flash on/off, so it's more eye-catching.
3. If the user tries to resize the window in the middle of a save (which will make the Rezonator window go all white), don't let them do this. Instead, make the dialogue box flash at them, to show it must be dealt with first, whether by supplying the required info or canceling. (Or if it's hard to prevent the user from resizing the window, at least make sure the Rezonator window doesn't cover up the dialogue box.)    
4. Give the user an explicit option to cancel the save. If the user chooses to cancel the save:
- change the ambiguous message "Error in saving" to "Error: File not saved".
- by default, return the user to the state of working on the file they were working on when they initiated the Save
5. All of these picky little problems (will there be more in the future?) suggest a solution: Replace the existing Save process with Samuel Venable's Dialogue Module.

**Comment by time-killer-games** [comment]
It's also worth noting that switching to dialog module will allow the use of multiple file filters on mac with the file dialogs, something that with GameMaker out of the box is Windows-only. If there are any functions included in GameMaker that you'd prefer dialog module to not override, you can delete the functions you don't want implemented with dialog module by deleting the actual functions themselves from the resource tree by editing the actual extension. This is Samuel Venable by the way. This project looks very interesting. :)
