### ISSUE TITLE
Crash when picking a Rez chain

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#243]
**Describe the bug**
After making various Rez chains, Chunks, Stacks etc, I tried to select a Rez chain (with p, then CTRL-p), and got a fatal error.

**To Reproduce**
1. Make various Rez chains, etc
2. Select a Rez chain (with p, then CTRL-p).
3. See the fatal error:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_chain:

DoAdd :2: undefined value
at gml_Script_scr_drawRezChain
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scr_drawRezChain (line -1)
gml_Object_obj_chain_Draw_0
**Expected behavior**
Don't crash.
(Something about picking Chains and Filtering keeps bringing back the crashes. 

**Screenshots**
![Crash when Picking a word in an aligned Rez chain 03](https://user-images.githubusercontent.com/22628444/58748626-71b8d980-8484-11e9-862d-71d865529c48.PNG)

**Comment by Georgio-Klironomos** [comment]
Crash was caused by a focused chain being outside of the filter's rendering area. Filter now unfocuses any focused chain that lies outside of the lines being rendered, preventing the crash.
