### ISSUE TITLE
Import plain text data in DLx Scription format 

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#264]
**Is your feature request related to a problem?**
Linguists often need to analyze Interlinear Glossed Text. One of the simplest ways to produce this kind of data is to use Scription (DLx).  At its simplest, Scription is simply a set of conventions for using a word processor (or text editor) to create a plain text file (.txt) that conveys the form and meaning of Interlinear Glossed Text. Scription defines a plain text format that is both user-friendly and systematic, which makes it especially attractive for many users. Supporting this convention will allow linguists to easily to import their data into Rezonator.     

**Describe the solution you'd like**
1. Create a Rezonator strategy to automatically import a plain text file that follows the Scription conventions. 
2. For a detailed explanation, see:
- [**Scription**](https://scription.digitallinguistics.io/).    
3. See also the [DLx Word Aligner](https://github.com/digitallinguistics/word-aligner)

**Test data**    
Test the Rezonator import process using one of these test data files (which provide ready-made examples of interlinear-glossed discourse data in Scription format).
- [Scription example](https://github.com/digitallinguistics/scription/blob/master/example.txt)
- [Chitimacha.txt](https://github.com/digitallinguistics/scription2dlx/blob/master/test/data/Chitimacha.txt) (simple)  
- [Nuuchahnulth.txt](https://github.com/digitallinguistics/scription2dlx/blob/master/test/data/Nuuchahnulth.txt) (complex)    
- [Scription test data](https://github.com/digitallinguistics/scription2dlx/tree/master/test/data),

**Additional context**
This is related to #65 and #96 and #467  .

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x]  Block Types (for Import) #638 - 11 hr
- [x] Get Block Grid data into Import Grid - 5 hr
- [x] Display Scription data correctly on Import Screen- 3 hr
- [x] Display Scription data correctly on Main Screen - 3 hr

**Comment by johnwdubois** [comment]
Also, be sure to handle the "schema" notation:
https://medium.com/digital-linguistics/scription-text-format-ee30e99645bc

**Comment by johnwdubois** [comment]
Update labels for file import fields (etc):     

<img width="960" alt="Import screen" src="https://user-images.githubusercontent.com/22628444/76059690-65dad600-5f34-11ea-89c2-bffbb292e646.PNG">

**Comment by johnwdubois** [comment]
[Import interlinear gloss - data structure.docx](https://github.com/johnwdubois/rezonator/files/4301406/Import.interlinear.gloss.-.data.structure.docx)

**Comment by johnwdubois** [comment]
A flow chart for how to process Interlinear Glossed Text:

[IGT-Odin_enrichment_flowchart.pdf](https://github.com/johnwdubois/rezonator/files/4507880/IGT-Odin_enrichment_flowchart.pdf)

**Comment by johnwdubois** [comment]
This is more like what we need for the import screen (as sketched by Brady & Jack):
[Import interlinear gloss - data structure v2.pdf](https://github.com/johnwdubois/rezonator/files/4518776/Import.interlinear.gloss.-.data.structure.v2.pdf)

**Comment by johnwdubois** [comment]
I updated this to separate the plain text version of Scription from the JSON version (now written up in a separate ticket, so we can deal with it later).

**Comment by Georgio-Klironomos** [comment]
The next step for this import is preventing import data of different token count from both being listed as Token level

**Comment by Georgio-Klironomos** [comment]
DLx Scription format files are now being imported correctly into Rezonator, and now we can user test this import.

**Comment by johnwdubois** [comment]
Not solved yet. There's lots of work still to be done.

**Comment by johnwdubois** [comment]
Here is a model of parent-child inheritance in Nuucha'nulth. This shows how the 1-to-many feature of the Nav window can be used to display any of the following: 
- unit-to-morph
- unit-to-word
- word-to-morph
For details see this pdf:    

[IGT example - Nuucha'nulth unit 12.pdf](https://github.com/johnwdubois/rezonator/files/5405571/IGT.example.-.Nuucha.nulth.unit.12.pdf)

**Comment by johnwdubois** [comment]
See the revised version of the IGT pdf:    

[IGT Import Schema - Nuuchahnulth - Unit 12.pdf](https://github.com/johnwdubois/rezonator/files/5406961/IGT.Import.Schema.-.Nuuchahnulth.-.Unit.12.pdf)

**Comment by dwhieb** [comment]
https://github.com/digitallinguistics/scription/issues/50 relates to this.
