### ISSUE TITLE
Link tags

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#268]
**Background**
We need to give users the option to add a Tag (e.g. a text string) to a Link (e.g. Rez link, Track Link, Tree Link, etc.). In Rezonator, drawing a Link involves drawing a line between the Source token and the Goal token token (with arrowheads to show directionality.     
There is already at least one field set up in the Link grid to deal with tags (the Relation field, a.k.a. DepRel, Role, etc.), but more tags are needed .     

**Describe the solution you'd like**
1. It should e possible to attach a Tag to a Link (e.g. between a pair of words etc.), for example in the Relation column.
2. In the Link grid, every Link has (or should have) fields for:
- Source: nodeId of the Source token
- Goal: nodeId of the Goal token
- Relation (e.g. Dep, etc.)    
- Clicktime
3. Let the user add Tags to a Link using as many of the following options as are feasible:
- select a Relation label (or a shortcut key) from a drop-down list
- type in a word for the Relation label
- Use the right Pane of the Nav window to let the user input the Tags.

**Additional context**
For inspiration about Relation tags, see the Forbes TAG format, as described here:
https://github.com/johnwdubois/rezonator/issues/169#issuecomment-513443734   
Corresponding to the field called "Relation" in Forbes' system is what we used to call "Role" (e.g. Source>Goal>Role).

**Comment by Georgio-Klironomos** [comment]
We'll want this to be a dynamic list of Tag fields, similar to what we have for Unit and Token tags at the moment, so it may scale for different applications.

**Comment by johnwdubois** [comment]
This should use the Node map, obviously.

**Comment by terrydubois** [comment]
Save sourceClickTime and goalClickTime for chain entries & links, and then export those in link.csv.
