### ISSUE TITLE
Crash due to Chunk/Box inaccuracy in left-justified text

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#290]
**Describe the bug**
The Chunk/Box tool is inaccurate in left-justified text, capturing the wrong words.
As a bonus, when you try to delete the incorrect Chunk (still in left-justified text), it crashes.

**To Reproduce**
1. Open SBC015.
2. Press "j" for left-justified text. 
3. Increase the font size.
3. Go to line 389 ("There's a town")
4. Try to make a Chunk on "a town"
5. Notice that the Chunk is too big: It includes "There's" as well.
6. Try again on "a town" in line 391. Same problem, but now it's worse.
7. Conclusion: Marking of Chunks/Box is inaccurate in left-justified text.

**Expected behavior**
Make sure that marking of Chunks is accurate, even in left-justified text.
(Making Track Chains is one context where left-justified text is very likely to be used, so marking of Chunks should be very accurate here.)

**Screenshots**
In the following example (SBC015_389-393), I used the Box tool to drag from "a" to "town". In both cases, the Chunk expanded to the left, including one or two words that I never touched. 

![Chunks inaccurate in justified text](https://user-images.githubusercontent.com/22628444/62077802-aadab380-b253-11e9-9133-820d8280d1df.PNG)

**Crash**
Now try to delete the Chunk, while still in Justifed text mode. See the fatal error:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Key Press Event for <Delete> Key
for object obj_control:

ds_list_size argument 1 incorrect type (undefined) expecting a Number (YYGI32)
at gml_Object_obj_control_KeyPress_46
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_obj_control_KeyPress_46 (line -1)

![Crash when deleting a Chunks in justified text](https://user-images.githubusercontent.com/22628444/62078480-66e8ae00-b255-11e9-87cb-4fb454aece9c.PNG)

**Comment by Georgio-Klironomos** [comment]
Chunks now accurately captures left-justified words. The mentioned crash is still being investigated.
