### ISSUE TITLE
Search dialogue: Update messages, design & function

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#295]
**Is your feature request related to a problem?**
The search dialogue box has confusing messages and layout. In addition, some functions need to be updated, and the keystroke shortcuts changed. 

**What to do**
Replace the message strings in the current "Search" dialogue box, reorganize the layout for clarity, and update the functionality, as follows. 
1. When the search is activated, display a dialogue box showing the following:    
 
_Search for word:_ 
.__________________________         
[_________________________]         

 _Search in field:_        
.__________________________           
[__________________________V__]         

 case sensitive
 search in current chain only
 use Regular Expressions
        [CANCEL]    [SEARCH]

2. The "Search for word" and "Search in field" boxes can be displayed side-by-side to save space, if this helps.
3. The user's cursor is automatically placed in the "Search for word" box.
4. If the user has already performed a search, remember the most recent search word, and display it in the "Search for word" box.    
5. Clicking on the "Search in field" box opens a drop-down menu, with the following options. (Show only the options which exist in the file and have been mapped in Rezonator.)
◉ text    
○ transcript    
○ lemma      
○ morph    
○ gloss    
○ translation    
○ speaker

6. Display the version number (e.g. "Rezonator 0.9.1.4") in a more sublte way: no boldface, small font, font color is light grey.
7. Make sure the font size in the dialogue box (and the dialogue box itself) can scale up in size, along with the rest of Rezonator 
8. Allow enough room to support the user's selected language:
- buttons should be sized to to allow any reasonable message string length 
- dialogue box should be sized to to allow any reasonable message string length 
9. For the "Search in field" drop-down menu, "text" is the default value. The display should be pre-populated with the currently active selection, which updates once the user changes the selected option. 
10. If the user has not entered anything into the "search word" box, the [SEARCH] button should be greyed out (to show that it is inactive) 
11. Remember all of the user's Search preferences as selected above, and store them in the .ini file (or equivalent).
12. The keystroke shortcuts should be:
- "CTRL-f" = Search (instead of the current "f")
- "f" = Find (= Find next" #632 )

**Additional context**
Here is some design inspiraction by: 
- [**UX Planet**](https://uxplanet.org/how-to-improve-advanced-search-ux-450df698004c)
See also #632  #679 
(For details about the future development of the dialogue box, see #319 .

**To do**
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] Task 4

**Comment by laurenmin** [comment]
The updated search dialogue boxes
![Frame 54](https://user-images.githubusercontent.com/72825616/113432076-97211200-9391-11eb-93da-d18cd95b084d.png)
