### ISSUE TITLE
Basic sort for Nav window columns

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#333]
**Is your feature request related to a problem?**
The most natural place to put a sort option is on the column of data to be sorted. This applies to all the columns in both panes of the Nav window.
 
**Describe the solution you'd like**
1. For each column containing data in the Nav window, in both the Chain and Contents panes, insert a Sort icon (small triangle next to Column Header), which should be easily clickable by the user. 
2. The triangle points up or down, to select Ascending or Descending sort. If the user clicks on the arrow, it produces the following results:
- Downward-pointing triangle: Sort in Ascending order
- Upward-pointing triangle: Sort in Descending order
3. To get UI inspiration, play with sorting columns in the Windows Explorer, or sorting CSV data using a good spreadsheet (e.g. LibreOffice or Excel).

**Further development** 
1. It may prove useful to also create an icon to restore the Standard Sort (a multi-column sort of DiscoID-UnitID-WordID). This sort icon may be displayed for each pane of the Nav window, or on each Tab (Rez, Track, Stack, Clique), whichever seems more relevant.
2. More advanced sorts will take some more effort, and may require a pop-up dialogue.

**Comment by terrydubois** [comment]
Extend this functionality to the chainContents.

**Comment by johnwdubois** [comment]
We need to have sorting in:
- clique tab (along with show/hide & filter

**Comment by johnwdubois** [comment]
Isn't this already done?
