### ISSUE TITLE
Rezonator hangs when starting in Tablet mode

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#345]
**Describe the bug**
There is a mysterious bug that arises when the user starts Rezonator in Tablet mode of Windows 10.   
It can be fixed by not just closing Rezonator, but leaving Tablet mode.

**To Reproduce**
1. In Windows 10, switch to Tablet mode (e.g. with a Surface Pro, remove the keyboard, and say Yes to Tablet mode). 
2. The opening screen appears, but it takes on a weird look, with the sides of the boxes for each button being drawn only partially.
3. When trying to use the buttons to open a file, nothing happens.
4. To escape from the problem, switch back to regular Windows (instead of Tablet mode).  
5. It may be necessary to use the Windows Toolbar to start and stop Rezonator. 
6. If Rezonator remains in the same state and cannot be closed, in the worst case it may be necessary to restart Windows.
7. If you start Rezonator in computer mode, and then switch to Table mode, things work correctly.

**Screenshot**
Here's what Rezonator looks like when you start it in Tablet mode (notice the poorly drawn buttons, which don't actually work): 

![Hang when starting in Windows 10tablet mode 2](https://user-images.githubusercontent.com/22628444/64922681-9427f600-d7da-11e9-8657-6f72d1d618a5.PNG)

**Expected behavior**
1. It should be possible to use Tablet mode in Windows 10 for all Rezonator functions, including starting the program, opening files, and saving, etc.

**Comment by hopesu21** [comment]
I was able to get Rezonator to work in Tablet mode on my Surface Pro 4 by minimizing and then unminimizing the screen. 
![Screenshot (83)](https://user-images.githubusercontent.com/77072787/110932478-68f36980-82e0-11eb-95d7-613111bdcc62.png)
![Screenshot (86)](https://user-images.githubusercontent.com/77072787/110933044-19fa0400-82e1-11eb-93d3-81bd7913f6fc.png)
![Screenshot (86)](https://user-images.githubusercontent.com/77072787/110933156-40b83a80-82e1-11eb-9178-ab12998aab59.png)
![Screenshot (88)](https://user-images.githubusercontent.com/77072787/110933166-43b32b00-82e1-11eb-80ee-6ed02e00b260.png)

**Comment by johnwdubois** [comment]
@hopesu21 That's great! Glad you have a Surface Pro (I have one too).   
@terrydubois With this input from Hope, perhaps you can work with her to fix this bug? (This will help me, as well as all users of the Windows 10 tablet mode, I believe.)
