### ISSUE TITLE
Stacks reduce to 1 line only

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#352]
**Describe the bug**
Stacks reduce to 1 line only.

**To Reproduce**
1. Drag down over several lines in the Speaker label region.
2. See the resulting Stack end up with only one line.

**Additional problems**
Can't delete a line from a Stack.

**Expected behavior**
1. Dragging down over several lines in the Speaker label region should produce a multi-line Stack.
2. L:et users easily delete a line from a Stack.

**Screenshots**
![Stacks reduce to 1 line only](https://user-images.githubusercontent.com/22628444/64942362-83768f00-d871-11e9-985f-876b9f5abaa7.PNG)

**Comment by Georgio-Klironomos** [comment]
Both of the methods I've found that replicates this behavior have fixed, however this bug reminds me heavily of rainbow Stacks. We should keep our eyes open for similar behavior.
