### ISSUE TITLE
"W" toggles "Text" vs. "Transcript" in Nav window display

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#357]
**Is your feature request related to a problem?**
When the user presses "w" to toggle between the "Text" vs. "Transcript" view, the display of word strings updates correctly in some parts of the Nav window display, but not in others.   

**Describe the solution you'd like**
1. Make sure that Rezonator displays a word string reflecting the "Transcript" view (as opposed to the "Text" view), in all parts of the Nav window display, when the user presses "w". The following should update (toggle) in the Contents pane, in response to pressing "w":
- Rez chains
- Track chains (here it is already implemented correctly)
- Stack
- Clique
2. For Stack and Clique, the label "utterance" (in the header of the Contents pane in the Nav window) should default to say "Text" instead.
3. For all Nav window headers in the Contents pane (for Rez, Track, Stack, Clique), the header label should update to display as either "Text" or "Transcript", when the user presses "w" to toggle the display. 
4. For the "Text" entry for Stack and Clique in the Nav window, make sure to include the EndNote.

**Screenshot**
Currently, the Track chain portion of the Nav window displays correctly (see the screenshot below), but other parts of the Nav window do not update when "w" is pressed.
 
![Show transcription in Nav window Rez chains](https://user-images.githubusercontent.com/22628444/64962637-6f965180-d8a0-11e9-9db9-b99ca4d311f3.PNG)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Because this feature is built around the old Rez files and redundant because of the user's ability to switch their display token in the Nav window, we'll will be taking it out from the 0.9 release. Then for the next release we can rebuild it to work with any type of file.
