### ISSUE TITLE
Audio player ignores Windows audio settings

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#364]
**Describe the bug**
The Audio player completely ignores Windows audio settings.

**To Reproduce**
1. Import an audio file and start playing it.
2. Using Windows, try to do the following:
- mute the audio:  it fails 
- change the audio playback level:  it fails
- change the audio to a different output (e.g. headphones):  it fails

**Expected behavior**
1. The Audio player should respond to the user, via the Windows audio settings for:
- mute the audio
- change audio playback level
- change to a different audio output
2. Pressing spacebar should should begin playing the audio from the line where the user is focused.

**Comment by terrydubois** [comment]
Seems to be a GM problem, although there is very minimal discussion about it in the forums. I can change the audio output device in the GM general preferences, but it does not seem to be dynamic enough to change mid-runtime. We can return to this later.

**Comment by johnwdubois** [comment]
Windows audio control seems to work okay for me now. It seems that part was not a real bug.
