### ISSUE TITLE
Stack delete without confirmation

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#365]
**Bug**
In the Nav window, it is easy to delete a stack without any confirmation. For example, 
- click on a stack in the Nav window
- press delete (and it's gone, with no warning)

**Expected behavior**
1. Require confirmation from the user when deleting a stack (or anything else important) by any means.
2. Show an alert: "Delete this stack?" [OK, Cancel]
- also, highlight the stack that is about to be deleted
3. Change all alerts from the old style (referring to "clear chains") to the new style ("Delete this stack?")
4. Consider adding a trash can icon to the stack list (but require confirmation here too)

**Comment by johnwdubois** [comment]
We still have the problem of deleting without confirmation.

**Comment by terrydubois** [comment]
Deleting the final unit in the stack should give a dialog box confirmation.
