### ISSUE TITLE
 Nav window coordination is wrong when context button is used

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#366]
**Describe the bug**
The Nav window coordination is wrong when the "Next" context button is used. 

**To Reproduce**
1. Following the screenshot below, create a Stack, Pick the Stack, and Filter it.
2. Turn on the "Next" context button, as shown.
3. Double-click on a line of the Stack in the Contents window.
4. See how Rezonator jumps to the wrong location. 
5. Why? Apparently the script doesn't adjust for the absence of the Prior context lines in the Main screen display.

**Expected behavior**
1. When the user double-clicks on a line of a Stack in the Contents window, make sure Rezonator jumps to the right location. 
2. Test the behavior with all possible combinations of:
- prior, tween, and post context buttons on/off
- stack is filter/picked or not
- etc.
3. Test in the same way also with Rez chains, Track chains, and Cliques.
4. Add this to the Testing protocol, along with all relevant coordination between Nav window and Main screen.

**Screenshots**
Follow the steps in this screenshot to test the problem:

![Nav window coordination is wrong when context button is used 3](https://user-images.githubusercontent.com/22628444/65047963-0714a680-d96c-11e9-9e8c-36795705a19c.PNG)

**Additional context**
Related to #56.

**Comment by Georgio-Klironomos** [comment]
The chain contents were only grabbing info from the Line Grid, but in scenarios like this one it needs info from the Filter grid. Now we use the CurrentActiveLineGrid variable within this script and get the result we want
