### ISSUE TITLE
Up-down arrow should move 1-to-1 in Contents Pane

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#369]
**Describe the bug**
In the Contents Pane, pressing the up and down arrow keys moves way too slow (when line height and font size are maximized). 

**To Reproduce**
1. Maximize line height and font size, and make some QuickLinks.
2. Click on a line in the Contents pane. 
3. Click on the down arrow.
3. It should take exactly one press of the down arrow to move down one full line. 
5. Try the equivalent for the up arrow.   
6. Currently it looks like the up and down arrows are not 1-to-1 (one keypress moves one line).
7. Perhaps they are also not scaling for line height. They move way too slowly, as if by a fixed pixel value, or by the wrong line height.

**Expected behavior**
1. In the Contents Pane, the up and down arrows should move 1-to-1 just as in the main screen. That is:
- 1 keypress moves up/down one full line
- movement scales correctly with the current line height.
2. Same behavior is expected in Grid view, Search screen, Main screen....

**Further development**
1. Also, in the Contents Pane, one press of the PageUp/PageDown keys should move one screenful up or down (that is, as measured by the number of lines within the Contents Pane.
2. To do this accurately, it will be necessary for Rezonator to know how many lines are displayed in the current Contents Pane, as currently displayed. This should take into account:
- the current Line height (as applied to the Contents Pane)
- how big the Contents Pane is currently (if the windows was dragged/enlarged by the user, for example), measured in number of lines it can discplay

**Additional context**
Related to #339.

**Comment by Georgio-Klironomos** [comment]
Scrolling with the arrow keys now moves you one line at a time no matter the text size
