### ISSUE TITLE
Chunk visualization is unclear

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#373]
**Describe the bug**
The visualization of Chunks is unclear. 
- There is almost no space between the Word box and the Chunk box
- The Chunk box is light grey, and hard to see

**Expected behavior**
- There should be a significant, easy to notice space between the Chunk box and any Word box it encloses.
- For nested Chunks, there should be a significant space between any Chunk box and the Chunk box it encloses.
- The Chunk box should be easy to see, colored in dark blue (until it receives color from being added to a Chain).

**Screenshots**
Use the following as a model for how much space to leave between nested boxes:

<img width="840" alt="Nested chunk visualization - Hugging Face Neural Coref 2" src="https://user-images.githubusercontent.com/22628444/65173382-e8d3a700-da4e-11e9-8083-2d3c663a5339.PNG">

 (Source: https://huggingface.co/coref/)

If necessary, get a measuring device and make sure there is X percent of space between nested boxes.

**Additional context**
Related to #255 and #262 .

**Comment by Georgio-Klironomos** [comment]
![image](https://user-images.githubusercontent.com/44912030/65186617-d6da1000-da1e-11e9-95c6-94414c7a4b75.png)

**Comment by Georgio-Klironomos** [comment]
Here's Chunks with their buffer increased to 10 pixels for non-nested and 6 pixels for nested. These values are doubled for the horizontal length of the boxes. Going any higher than these values causes severe overlap between Chunks and word rectangles when on the lowest line height/column width, but if need be we can play with the values more

**Comment by johnwdubois** [comment]
The current buffer is inadequate. 
- The screenshot I gave shows the correct proportions. 
- The screenshot you gave shows incorrect proportions.  

The solution is simple:
- Make the proportions larger than currently used. 
- Increase the buffer by a percentage, proportionally to the height of the Word box, not by pixel count
- When there is overlap with a Word box in the next line above or below, the solution is to increase the Line height. There is nothing sacred about the minimum Line height currently being used.
