### ISSUE TITLE
Import tab-delimited transcriptions from Elan

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#375]
**Is your feature request related to a problem?**
Rezonator users may want to import data produced in popular software such as [Elan](https://tla.mpi.nl/tools/tla-tools/elan/). Elan is widely used by linguists, anthropologists, and others, especially for transcribing audio and video recordings of conversation. A useful workflow is to: 
- use Elan to transcribe the conversation 
- use Rezonator to analyze the conversation. 
So we need a strategy to get data from Elan into Rezonator in the easiest possible way. 

**The solution you'd like**
To import data from Elan, do the data exchange in two steps:
1. First, use Elan to export the file , using a commonly used file format, such as a tab-delimited file. 
- open the Elan transcription file (.eaf file)
- From the menu, select "File/Export as/Tab-delimited text". 
- Select the appropriate export options, checking the boxes as shown in the screenshot below.    
2. Second, use Rezonator to import the tab-delimited text. (See next section for details.)

**Screenshot**
The following shows how to select options for the "Export as tab-delimited text" option in Elan:    

<img width="731" alt="Export from Elan" src="https://user-images.githubusercontent.com/22628444/76155269-98a0dd80-609e-11ea-9015-a9102d795781.PNG">

**Import into Rezonator**
1. Now use Rezonator to import the tab-delimited file.
2. Rezonator then creates an "Import" grid, which mimics the file structure of the tab-delimited file (which inherits its file structure from the original Elan file). 
3. Within Rezonator, it is important to correctly handle the fields of data commonly encoded in Elan. Each field should be assigned to the correct field (and grid) in Rezonator. This will require mapping into Rezonator fields from the fields labeled by the Elan conventions, such as:
- timestamps (e.g. begin time, end time, total length)
- participants (speaker labels)
4. The text field will contain all the tokens (e.g. words, pauses, vocalisms, etc.). This field needs to be tokenized in the usual way.
5. By default, Elan groups utterances by the participant who produced it, not by the conversational sequence. For a good result, Rezonator should use the time-stamp information to sort the utterances into the original conversational sequence. (Sort by unitStartTime, then by unitEndTime.) 
6. For more complex Elan transcriptions, this may involve fields such as text, transcription, gloss, translation, etc. The Rezonator import screen should allow users to specify the mapping between Elan field names and the corresponding Rezonator field names.

**Documenting the Elan export**
1. A key goal is simply to document the export process in Elan. Even if the Elan documentation already describes how to export a tab-delimited file, Rezonator users will benefit from us documenting the simplest way possible to export from Elan, and import into Rezonator. 
2. For details on how to export a tab-delimited file (to be used as our data exchange format), see the Elan documentation on:     
[Exporting a document as a tab-delimited text file](https://www.mpi.nl/corpus/html/elan/ch01s04.html#Sec_Exporting_a_document_as_a_tab_delimited_text_file).     
3. For general information on Elan and the .eaf format, see the documentation on [Elan](https://tla.mpi.nl/tools/tla-tools/elan/)     

**Alternatives you've considered**
While it might be possible for Rezonator to import an Elan file (.eaf) directly, this would require a schema to interpret and process the .eaf format files used by [Elan](https://tla.mpi.nl/tools/tla-tools/elan/). This would not be easy, so it's better to use the existing Elan export functions to create an exchange file format, as described above.

**Additional context**
This is related to #264, and to #65 and #96 .

**Comment by johnwdubois** [comment]
Here's a link to the file to use for testing:    
https://ucsb.box.com/s/16c7w3xghpa01dpbi2mj6rsxldbe3ndc

**Comment by gtroiani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rezonator](https://trello.com/c/1xFqHuft/40-rezonator)
