### ISSUE TITLE
PageUp/PageDown should adjust to Nav window height

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#376]
**Describe the bug**

**To Reproduce**
1. Drag the Nav window border to make the window bigger.
2. Click on PageUp/PageDown a few times. 
3. Note that it skips over several lines, not displaying them as expected. 

**Expected behavior**
1. PageUp/PageDown should adjust to Nav window height. 
2. PageUp/PageDown should not skip any lines.

**Comment by Georgio-Klironomos** [comment]
PgUp and PgDn calculations now take the height of the menu bar into account along with the current height of the Nav window. The scroll value is also multiplied by 0.9 for extra safety.
