### ISSUE TITLE
Chunk makes unwanted Word link

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#381]
**Describe the bug**
Marking a Chunk in a Track chain sometimes makes an unwanted Word link, in addition to the Chunk.

**To Reproduce**
1. In Track chain mode, mark a bunch of Chunks. Notice that the drag sometimes makes an unwanted Word link, in addition to the Chunk. 
2. The unwanted word seems to always be the last word in the Chunk, suggesting that this has to do with how the MouseUp event is being interpreted.

**Expected behavior**
Insert some checks/tests to make sure that a single mouseUp event doesn't create both a Chunk and a Word at the same time.

**Screenshots**
![Chunk makes unwanted Word link](https://user-images.githubusercontent.com/22628444/65818782-a152d500-e21d-11e9-993f-bcf8ee0677ae.PNG)

**Comment by Georgio-Klironomos** [comment]
Creating a chunk now starts a small safety period (less than a second) in which no word links can be made, preventing unwanted word links.
