### ISSUE TITLE
Mac installation problems

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#385]
**Describe the bug**
Several students have trouble with installing the Mac version of Rezonator.   
- won't run
- screen flashes diagonally (and it won't run)
- etc.

**To Reproduce**
We may need more input from users. The solution for most was to drag the Rezonator icon into the applications folder. (Not everyone knew they should do this.)

**Expected behavior**
1. The installation experience for Mac users should work, and preferably in a clear and simple way..
2. Guidelines for how to install are needed on the website.

**Additional context**
Communicating directly with users might be a good idea, to get more feedback.

**Comment by Georgio-Klironomos** [comment]
Installation is working fin with our Mac, though we'll be trying to user test with Mac users as much as we can before 0.9.0
