### ISSUE TITLE
Track tool precedes Rez tool

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#388]
**Is your feature request related to a problem?**
Users can easily get confused with the Rez chain, which is a more advanced concept than making a Track chain. This is especially true given that Where's Elmo gives people their first introduction to using Rezonator. The natural follow-up is that the first kind of Chain to make in Rezonator is the Track chain.

**Describe the solution you'd like**
1. In the Nav window, place the Track tab ahead of the Rez tab. (The Track tab appears in second position, right after the Line tab).
2. The default justificiation for Track mode is left-justified

**Additional context**
This goes along with making left justification the default when Rezonator is started (in Read mode) (see #210 ).

**Comment by Georgio-Klironomos** [comment]
By "The default justificiation for Track mode is left-justified", are you meaning the default as Rezonator is opened, or the default for whenever the Track tool is active?
