### ISSUE TITLE
Typing R or T in dialogue box triggers Rez and Track tool change

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#392]
**Describe the bug**
Typing R or T in a dialogue box (for example, when renaming a Track chain) triggers a change in the Rez vs. Track mode.

**To Reproduce**
1. Make some Track chains.
2. Click on one of them to rename it as "Sharon" or "Stan"
3. Notice that by typing R or T in the name, this triggers an uninted shift in mode, to R=Rez or T=Track mode. This is confusing to the user.

**Expected behavior**
Make sure that typing in any dialogue box never triggers a change of Rez vs. Track mode (or any other such keystroke shortcut). 

**Additional context**
If we can't solve this problem efficiently for all keystroke input (hopefully in a way that it won't come back), we will need to stop using shortcuts like T and R etc., and change them to CTRL-T and CTRL-R. But it would be better to be more disciplined in interpreting keystroke input in dialogue boxes.

**Comment by Georgio-Klironomos** [comment]
Checks are now in place to prevent user's text input from changing the tool mode.
