### ISSUE TITLE
Import plain text (song lyrics)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#414]
**Is your feature request related to a problem?**
There's a lot of resonance in song lyrics, which are easily available online (e.g. lyrics.com). This is a great way to get people started on marking resonance: with their favorite song.

**Describe the solution you'd like**
1. Let users easily import song lyrics (or other simple plain text documents, such as poems) into Rezonator.
2. This would create:
- a Unit grid (one Unit per line of the original data)
- a Word grid (Words defined by whitespace  in the original data)
3. Use the easiest input method: Import a plain text (.txt) document.

**Additional development**
1. Automatically create "auto-stacks" when importing, based on the blank lines that are typically used to separate verses: one verse per Stack.

**Related to**
#391 , #312

**Comment by johnwdubois** [comment]
We can easily add "auto-Stacks": One stack per line group (corresponding to chorus or verse), where the line groups are typically marked by a single blank line.
Note that line groups in song lyrics are NOT to be treated like line groups in an interlinear glossed text.

**Comment by johnwdubois** [comment]
Aim for a "1-click" import for plain text import:
- Don't ask the user for a speaker label. (We can add that later using the Tag tool, if necessary.)
- If the file looks like song lyrics (no Line Groups), assume that's correct, and go ahead and import it as is. 
- Automatically turn the pseudo-"Groups" into Stacks.
- If possible, don't even show the confirmation screen.
- Take a risk!

**Comment by johnwdubois** [comment]
This ticket is mostly done, but it needs the following:
- Use blank lines to automatically create Stacks (= verse, in songs or poetry).
- Once that is done, get rid of the blank lines in Rezonator. (Treat blank lines as similar to whitespace, but at the Unit level.)

**Comment by Georgio-Klironomos** [comment]
Song lyrics are now importing correctly. @johnwdubois we should consider making separate feature tickets for the automatic verse stack creation, and the blank lines.

**Comment by Georgio-Klironomos** [comment]
The song txt import has been user tested and works as expected!
