### ISSUE TITLE
Hidden Speaker label Issues

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#442]
**Describe the bug**
When importing plain text song lyrics, there are some problems that arise where the speaker labels used to be.

**To Reproduce**
1. Import some song lyrics (for example, "We shall overcome").
2. Mark some stacks.
3. Notice that the color of the stack does not extend all the way to the grey (on the left margin, where the speaker labels ordinarily would be).
4. Try to drag diagonally southeast (QuickLinks) from the first word of the first line on the screen.
5. Notice that you can't start a QuickLinks on the first word. (But you can start from the right, and drag to the left.)

**Expected behavior**
1. Fix it so the "dead zone" where the Speaker labels were (i.e. the "ghost" left by the speaker label column) doesn't block 
- (a) line color for Stacks, and 
- (b) clicking on a word to make links & QuickLinks.
2. Make the default file type for importing data be plain text (TXT), not XML.

**Screenshots**
Notice the missing color in the "dead zone" where the Speaker labels were. (Also, try to reproduce some of the QuickLinks shown below.)    

<img width="960" alt="Color is missing where speaker labels were" src="https://user-images.githubusercontent.com/22628444/76060419-1b5a5900-5f36-11ea-8743-6ff4df224594.PNG">

**Comment by johnwdubois** [comment]
Also, the plain text import seems to completely ignore any TAB characters. Right now if two words are separated by a TAB, they get merged together as a single word. (At least this is what happens when they appear as the first 2 tokens of the line). At a minimum, Rezonator should recognize TABs as whitespace, and use them to tokenize as separate words. (One way is to convert TAB to a space -not ideal, but better than nothing.)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Terry was able to fix this bug, next we'll user test it

**Comment by Georgio-Klironomos** [comment]
User testing shows this bug has been successfully squashed.
