### ISSUE TITLE
Import schema

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#446]
**Is your feature request related to a problem?**
Users often need to import multiples files, where each file follows exactly the same format. To avoid user frustration, it is important for Rezonator to acknowledge this.    
That said, the import process should still be as flexible as possible, accepting whatever data the user wants to import (within reason).   

**Describe the solution you'd like**
1. Allow the user to save a named ImportSchema (template) for mapping fields from the imported files into Rezonator fields.
2. For each import, there is an ImportSchema that Rezonator follows. This contains information like the following:
- For each field in a CSV file to be imported, what is the Level of this field (column)?
- What is the Utterance Splitter field ( = Unit Splitter, or Unit Delineator)?
3. "Import schema" options can be displayed to users on the import screen, allowing them to select one. Display the message: "Select schema for importing file:"
4. For each importSchema, it will be important to decide which processing path each of these file types is predicted to follow, once the Rezonator import processing actually begins.
5. While the user's choice is useful information for helping Rezonator to choose the best processing path, it is still necessary for Rezonator to apply its own tests to ensure a good result.

**Future development**
Some data formats are predictable, coming up again and again. Rezonator should recognize/remember standard import schemas.    
1. For certain standard file formats which are used by many people, Rezonator should offer a ready-made ImportSchema.   
2. Present users with a drop-down menua of pre-set ImportSchemas (templates) for reuse in order to take advantage of the increased predictability.     
3. The following are top candidates for ImportSchemas to offer (listed in order of presentation to the user, not of development):    
- None selected
- Plain text TXT
- DFT transcription TXT
- Elan CSV
- Tab-delimited CSV
- Tab-delimited (user-defined) CSV
- Interlinear ToolBox TXT
- Interlinear Scription TXT
- Interlinear (user-defined) TXT
- SBCorpus XML
4. The "user-defined" ImportSchemas should be renameable by the user. (They are not necessarily listed until they are created.)   
5. Note that "None selected" should be the first option in the drop-down list. We may allow users to use this, if they have no clue which one to pick. Then Rezonator is on its own for interpreting/ parsing the file (as is the case now).

**Comment by kayaulai** [comment]
There's an additional reason to want to support import schemas. If a user converts a file into a Rezonator-friendly format through RezonateR I'd like them to be able to import it with one click, not through the import screen. I can provide a function to produce the import schema in R.

**Comment by Georgio-Klironomos** [comment]
User tests show this feature working as expected and being quite helpful!
