### ISSUE TITLE
Crash when importing plus place chains

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#447]
**Describe the bug**
When importing some glossed text, Rezonator crashed

**To Reproduce**
- It might be the file.    
- Or it might be the presence of place chains.
See error:    

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_chain:

string_width argument 1 incorrect type (undefined) expecting a String (YYGS)
at gml_Script_scr_drawRezChain
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scr_drawRezChain (line -1)
gml_Object_obj_chain_Draw_0

**Expected behavior**
Make sure it doesn't crash with place chains and/or importing glossed text.

**Screenshots**

![CRASH Sak ex in Rezonator](https://user-images.githubusercontent.com/22628444/78124117-12896580-73c4-11ea-8d10-086af14b182f.PNG)

**Comment by johnwdubois** [comment]
A new crash. This time I sent you the actual Rez file that crashed it (see Google Drive, as described in my note on Slack.) I filtered on the Stacks, maybe that's part of it.


___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Key Press Event for W-key Key
for object obj_control:

string_length argument 1 incorrect type (undefined) expecting a String (YYGS)
at gml_Script_scr_toggleTranscription
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_scr_toggleTranscription (line -1)
gml_Object_obj_control_KeyPress_87

![CRASH Sak ex in Rezonator 02](https://user-images.githubusercontent.com/22628444/78423873-3fd15000-761e-11ea-8ef5-793b36091b9e.PNG)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois I'll just need to test with the Sakapultek file to ensure this crash no longer happens
