### ISSUE TITLE
Same speaker label gets 2 colors  

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#448]
**Describe the bug**
Sometimes the same speaker label gets assigned 2 different colors, when importing a file. Color should be consistent throughout all instances of a given speaker label.

**To Reproduce**
In the Sakapultek example, Manuel comes up in 2 different colors.
So does Maria. I double-checked the original file, and there's no difference in the names themselves. Must be something in the color-picking algorithm. Worth a look when you have time.

**Comment by hopesu21** [comment]
No longer an issue in 0.9.2.6
