### ISSUE TITLE
Speaker Label and Line Number Columns forget their width

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#449]
**Describe the bug**
When the user sets a column width for speaker labels or line numbers, it gots forgotten, as soon as you do/undo a filter.

**To Reproduce**
1. Change the column width for Speaker labels in the main screen.
2. Change the column width for Line numbers in the main screen.
3. Make some quick-stacks, filter them, then unfilter.
4. Notice that the column widths have gone back to the default.

**Expected behavior**
1. Columns should remember the width as set by the user, even after the user has been playing with things like turning filters on and off.
2. Try to think of other things that might make Rezonator forget the column widths, and test for these as well.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois The Line Number and Speaker Label columns now have their own individual max width, and took out rogue alarm resetting column widths. These values are now getting saved and loaded with the INI file correctly, and they are not getting negatively effected by the Filter

**Comment by Georgio-Klironomos** [comment]
This fix has now been user tested and consistently works.
