### ISSUE TITLE
Update Menu Bar

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#457]
**Dev Hours**
5 Hours

**Is your feature request related to a problem?**
The Menu and Help List need to be updated to reflect current functions
.   
**Describe the solution you'd like**
1. The Menu and Help should show the following:
- Name (one-word name of function)
- Key (keyboard shortcut)
- Description (brief description of the function, displayed only when the user hovers)
2. Where possible, standard keystroke conventions are used that will be familiar to most computer users.
3. The document linked below indicates how Rezonator functions should be organized for the Menu and the Help List. As far as possible, these should be consistent with each other.

[Menu and Help List.docx](https://github.com/johnwdubois/rezonator/files/4537372/Menu.and.Help.List.docx)

**Checklist w/ dev hours**
- [x] Finalize Format of Menu Bar - 1 hr
- [x] Test functionality for all Menu options - 2 hr

**Comment by Georgio-Klironomos** [comment]
Brady and I will be cleaning up the Menu Bar to have only currently implemented functions. And then we'll look at that doc to make it reflect the current Menu Bar, assess functions that are missing, estimate Dev Hours for those, and make Github tickets based on those desired functions.

**Comment by Georgio-Klironomos** [comment]
After a thorough testing, we can say that all options, except for the "Create Stacks" options still in dev, are working correctly. There is still a bug present with clicking a dropdown option and it selecting on of the chain tabs in the nav window.
