### ISSUE TITLE
Import CoNLL-U format ("Universal Dependencies")

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#464]
**What is the estimated development time?**
5 Hours

**Background**
Rezonator's graph structure is uniquely suited to representing syntactic dependency relations. Currently, more and more languages are being documented via corpora with this kind of information.     
One of the most important data formats is CoNLL-U, used in the following corpora:
- Surface Syntactic Universal Dependencies (SUD)   
- Universal Dependencies (UD)    
For an introduction to the data format used in these corpora, see: [**CoNLL-U format**](https://universaldependencies.org/format.html)

**What to do**
1. As a test case, download the [English-GUM corpus](http://grew.fr/download/sud-treebanks-v2.5/SUD_English-GUM/en_gum-sud-dev.conllu) in CoNLL-U format (SUD dependency analysis).
2. Import it into Rezonator. 
3. The structure of the file is basically tab-separated values (TSV, a.k.a. CSV), with "one word per line" (OWPL). This is a very common data format, and fairly straightforward, so we should be sure that Rezonator is set up to process it. 
4. For detailed information on the structure of the data, including project description and publications, see:
- [Surface Syntactic Universal Dependencies (GitHub)](https://surfacesyntacticud.github.io/)
5. Pay special attention to:
- spaceAfter = no -- Implement spaceAfter as a field in the Token grid of Rezonator. At the word level, most of these tokens should be combined with the neighboring token to form a word. 
- PUNCT = 'punctuation' (comma, period, question mark): Treat as a separate token?
- PUNCT = 'punctuation' (other): Combine with the neighboring element?
- Column header = FEAT (= features). This is a list of one or more features, which are attributes of the corresponding word/token. This is comparable to the Rezonator 'Tags' column. For now, treat this as a single string, to be placed in the 'Tags' column.
6. In the long run, we will make the .rez files we create for the English-GUM corpus corpus available for download on Rezonator.com (with appropriate acknowledgment and license information).

**Further steps**
1. For a much larger body of data, download the following corpora:
- [Surface Syntactic Universal Dependencies  (corpora)](https://surfacesyntacticud.github.io/data/)    
- [Universal Dependencies (corpora)](https://universaldependencies.org/)
2. Import them into Rezonator.
3. Make the .rez files for all of these corpora available for download on Rezonator.com (with appropriate acknowledgment and license information).
4. Import files in the extended format:
- [CoNLL-U Plus](https://universaldependencies.org/ext-format.html)

**Tools**
The CoNLL-U files (.conllu) can be examined with a standard text editor, word processor, or spreadsheet. But for more sophisticated treatment of the data, consider using the following tools (for editing CoNLL files): 
- [CoNLL Editor demo](https://syntaxfest.github.io/syntaxfest19/slides/conllueditor_demo_windows_subtitled.mp4)
- [CoNLL Editor (GitHub)](https://github.com/Orange-OpenSource/conllueditor)
- [CoNLL Editor (paper)](https://www.aclweb.org/anthology/W19-8010.pdf)
- [Universal Dependencies tools](https://universaldependencies.org/tools.html)

**Additional context**
This is related to #169. The data format is similar to #93 .    

**Checklist w/ dev hours**
- [x] Correctly import Unit level data - 2 hr
- [x] Correctly display Unit level data - 1 hr
- [x] Test with Larger .txt file - 1 hr
- [x] Test import of Ryan's version of the .txt - 2 hr
- [x] Speaker Label Display #522  - 4 hr
- [x] research of Pepper & Salt #515  - 3 hr

**Comment by Georgio-Klironomos** [comment]
Conllu import can take a .txt version of the GUM corpus and turn it into a Rez file. Tokens along with token data are correctly displayed in the main screen and in the grids. Current issue is displayed the speaker labels/unit level info correctly. Pushed, but not yet on a released Exe.

**Comment by johnwdubois** [comment]
To improve the GUM import, please use Pepper/Salt/ANNIS, described here: https://github.com/johnwdubois/rezonator/issues/515.

**Comment by Georgio-Klironomos** [comment]
Thanks to @kittynugget , we have speaker label information importing correctly now. Last step is importing coreference data, and for this we'll need to discuss with @kayaulai how this process should go.

**Comment by johnwdubois** [comment]
Use the correct column header labels, following the CONLLU conventions, instead of "col 1, col 2, col 3", which is incorrect.

The following is from the CONLLU website:
"Word lines contain the following fields:

ID: Word index, integer starting at 1 for each new sentence; may be a range for multiword tokens; may be a decimal number for empty nodes (decimal numbers can be lower than 1 but must be greater than 0).
FORM: Word form or punctuation symbol.
LEMMA: Lemma or stem of word form.
UPOS: Universal part-of-speech tag.
XPOS: Language-specific part-of-speech tag; underscore if not available.
FEATS: List of morphological features from the universal feature inventory or from a defined language-specific extension; underscore if not available.
HEAD: Head of the current word, which is either a value of ID or zero (0).
DEPREL: Universal dependency relation to the HEAD (root iff HEAD = 0) or a defined language-specific subtype of one.
DEPS: Enhanced dependency graph in the form of a list of head-deprel pairs.
MISC: Any other annotation."

Further detail (for the legacy format Conll-X:
"The fields DEPS and MISC replace the obsolete fields PHEAD and PDEPREL of the CoNLL-X format."

**Comment by Georgio-Klironomos** [comment]
Conllu Import with it's base functionality has now been thoroughly user tested.
