### ISSUE TITLE
Add word to off-screen Track Chain

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#476]
**Background**
Sometimes a word that should be added to a certain Track chain (such as a pronoun or name referring to a particular person) occurs when no other references to that person are visible on the screen. This can make it difficult to add the word to the appropriate Track chain. Why? Because the word may refer back to a person who hasn’t been mentioned in a long time. It is inconvenient to scroll back to find the most recent reference, which may be many screens back. What's worse is, if you do scroll back, you lose track of which word you wanted to add to the Track chain.

**What to do**
Let the user easily add a word to a Track chain, even when no other words from that Track chain are visible in the Main pane.
1. To set up the context: The user selects Track mode, and makes a few different Track chains. But the user has not yet found all the words that belong to these chains. Exit the current Track chain (with Escape). Scroll down to a new place in the conversation (where no referents have yet been added to the Track chain).
2. The user sees a pronoun they want to add to an off-screen Track chain. But how to do this, without losing your place?
3. The user uses the Nav window (left pane) to select a referent for which a Track chain has already been begun, by:
- scrolling through the list of Track chains to find the right referent
- click (or shift-click?) on the label for one of the Track chains.
4. The user then clicks on a word in the Main screen (e.g. the pronoun of interest). This adds it to the Track chain selected in the previous step. 
5. This should also work for Chunks: the user can create a new Chunk on the fly, and it will be added to the (previously selected) Track chain.
6. This should also work when there is already a Track chain in progress (when there is an active pickwhip, at the time the user moves to the Nav window).

**Additional context**
This feature becomes more valuable if it is implemented along with Frequency (#475), because that lets the user easily keep all the most important (most frequent) Track chains visible in the Nav window.

**Comment by kittynugget** [comment]
The user currently has the ability to this. if you were to select one of the chains in the nav window with a left click and that focuses that chain meaning the next click on a word will add it to that selected chain.
