### ISSUE TITLE
Trail name based on Track text 

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#478]
**Background**
I think a nice feature to have would be to annotate, by default, track chains by name of the first element (with a number if necessary), rather than Track + number. I think this will save a fair bit of time in naming the chains.

**What to do**
There are 2 good places to find a Trail name that is the most meaningful: (1) the first Track, when the Trail is first created, or (2) a Track chosen by the user.
1. When a new Trail is first created, automatically assign the Trail name based on the text of the first Track in the Trail. This could be either chunk text, word text, or token text -- whatever the Track entry contains.
2. If the user doesn't like the automatically assigned Trail name, let them rename it easily with a right-click. 
- The user first selects one specific Track in a Trail (using the right pane of the Trail tab)
- The user right-clicks on this Track
- This pops up a text input dialogue that is prepopulated with the text of the selected Track. 
- The text input dialogue shows the message "Rename the Trail?" plus the options: {RENAME, CANCEL}
- The user can edit the text, or simply accept it as is by pressing RENAME.
3. Although it is useful to assign the Trail's "Name" field automatically (Step 1), and also to allow semi-automatic replacement with user help (Step 2), the Trail's Name should NOT be UPDATED automatically. The Name should be relatively stable, not dynamic, once it is assigned.

**Further development**
The "Name" field could be **_supplemented_** by a "Text" field that updates based on the text of all the Tracks in the Trail, but it should not be replace by it. And this kind of dynamic Text field is less critical for Trails.

**Comment by johnwdubois** [comment]
I agree that this would be useful.
Here's a variation of this idea, which may prove even more useful: By default, choose the longest one (measured in characters). Or give two options: (1) first token in the chain, or (2) longest token in the chain.

**Comment by johnwdubois** [comment]
My previous comment is overridden by the recent edits to the main ticket.
