### ISSUE TITLE
Checkbox action: Add current Hits to Trail (or assign same Tag to all Hits)

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#479]
**_NOTE:_** See the recent [comment below by @johnwdubois](https://github.com/johnwdubois/rezonator/issues/479#issuecomment-778765206)  

It would be nice to have a feature where all instances of a certain string are added to a chain; this would save a lot of time with proper names etc. When we can start adding attributes to chains, words, chunks etc, it would be a good idea to be able to automatically set attributes this way as well (e.g. annotate all instances of 'Alice' as belonging to the 'Alice' chain, and annotate all of them as proper nouns).

**Comment by johnwdubois** [comment]
There are two good ideas here, both worth implementing.
The first idea is half-way there already. You can use CTRL-f to do a search for 'Alice', and then add drag the cursor over all the instances of 'Alice' to add them to a Track chain (assuming you've selected the Track mode). 
Things to develop further:
(1) Allow the user to use this technique to add to an existing chain (not just when beginning a new chain). In effect, this could be accomplished via the "Join Chains" function (there's a ticket for this, but it's not yet implemented). 
(2) Based on the results of a search, let the user add a particular feature (e.g. "proper noun") to all of the search hits.

**Comment by kayaulai** [comment]
To elaborate on a difference with the current approach: Currently we need to use drag-and-drop, which isn't feasible when there is a very large number of items as we can't scroll while doing drag-and-drop.

**Comment by johnwdubois** [comment]
Good point. We should implement an easy way to do the following:
1. In the search pane, let the user do the following
- highlight all of the current search results (with CTRL-a?)
- use the arrow keys (SHIFT-ARROW?) to select a subset of the search results
2. Add the highlighted items to the currently focused chain (the chain that is/was focused in the main screen).

**Comment by johnwdubois** [comment]
Let's keep it simple. 
**What to do**
Implement an easy way to do the following:
1. In the search pane, the user can easily select all of the current search results
2. Add the highlighted items to:
-  the currently focused chain (the chain that is now focused in the main screen)
-  the most recently focused chain (the chain that was focused in the main screen)
3. What is happening is that each user action adds to a list of Node ID's (TokenId's) that will be added to the current Track chain.
