### ISSUE TITLE
Change chunk extent

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#480]
A useful feature to have would be to be able to change the starting and ending word in two clicks, cf. changing spans in ANALEC (which is one-click and the programme guesses which side you're changing to - can lead to slightly annoying errors sometimes) and changing annotation boundaries in ELAN.

**Comment by johnwdubois** [comment]
Yes, this would be useful (applied to a chunk that has already been made). 
(1) Right-click on a chunk to click to open the right-click menu.
(2) Select option "Extend chunk"
(3) Click on word to which the Chunk should be extended.
More enjoyable, but more work to code:
(1) Hover over the left or right edge of a Chunk; after a pause, a drag-handle (double-headed arrow) appears
(2) Drag the handle to add a word to the Chunk, or subtract a word from the Chunk.
(Notice that this version has the advantage of allowing the user to make the Chunk smaller.)

**Comment by kayaulai** [comment]
The first option can actually work for reducing as well; when reducing, Rezonator just has to make a judgement on whether to keep the left side of the word or the right side. This is essentially what is done in ANALEC, but based on characters instead of words. But I think perhaps a better way would be to just click the desired beginning *and* end so we do not have to guess what the user wants.

**Comment by johnwdubois** [comment]
related to #387

**Comment by johnwdubois** [comment]
Closed: This duplicates #387.

**Comment by johnwdubois** [comment]
I've updated and reopened this ticket, because it may be the simplest way to get what we need.
**What to do:** See [this comment.](https://github.com/johnwdubois/rezonator/issues/480#issuecomment-646912653)

**Comment by terrydubois** [comment]
Add right click options: 
"Remove token from start of chunk"
"Remove token from end of chunk"
