### ISSUE TITLE
Reduce / Allow customisation of whitespace between lines

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#481]
Currently, one way in which Rezonator differs significantly from other tools (apart from Atomic and GraphAnno, as far as I'm aware) is the focus on IU as a unit. However, it seem that the amount of whitespace between IUs is comparable to that between paragraphs in other tools, and so it takes a lot more scrolling to be able to annotate. than in other tools. I think reducing, or allowing the user to reduce, the line height / whitespace between lines (and/or the padding of the cells if the lines are presented in a table format) would be useful for annotation.

**Comment by johnwdubois** [comment]
Both of these features already exist. Try:
CTRL PLUS/MINUS 
SHIFT PLUS/MINUS 
CTRL-SHIFT PLUS/MINUS

**Comment by kayaulai** [comment]
It seems that Shift + Plus/Minus only allows us to *increase* the whitespace from the default, but not decrease it (the default is already the smallest possible), so the space between lines is still quite long. Is there any way to decrease the whitespace?

**Comment by Georgio-Klironomos** [comment]
Hi @kayaulai ! I've reduced the minimum amount of whitespace to half the amount it is now, I'm attaching an image to get your feedback! The next EXE release will hopefully make annotation easier for you! 
![rezMin](https://user-images.githubusercontent.com/44912030/85474133-14993580-b569-11ea-8131-fd152ca8542b.PNG)

**Comment by johnwdubois** [comment]
Cool!
