### ISSUE TITLE
Prose View (= paragraph)

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#482]
**Background**
Most other existing tools deal with textual data, and so organise texts around paragraphs rather than lines. Clearly this has issues with respect to resonance annotation, but for the purposes of annotating track chains, the paragraph view does have its strengths. I think it would be a good idea if we can toggle to a 'paragraph mode' in which rez chains are disabled, and all turns become paragraphs.

**What to do** [JWD]
Give users the option to import "Paragraph" text data (i.e. prose, such as a newspaper article).
1. When importing paragraph data, each paragraph will end with a newline character (hard carriage return). So each paragraph will automatically be interpreted by Rezonator as one Unit.
2. The import will be similar to "Song & Verse", because it is plain text. The difference is that each "line" is a paragraph, so unless we do something special, the lines will be very long in Rezonator (going off the screen). 
2. The solution to this problem is to use several Lines to display one Unit. The Line is for mapping words to the screen.
3. Roughly speaking, the first 10 words of the paragraph go into the first Line; the second 10 words go into the second line; etc.
4. More precisely, the width of each word in pixels should be taken into consideration, in relation to the width of the visible Main screen.
5. Each Word has a variable (or Field in the Word grid), called `LineEndWord`. By default, for each word the value of `LineEndWord` = FALSE.
6. Rezonator measures the word length and calculates how many words are needed to fill up the Line, given the current width of the visible Main screen. 
7. For a Word that falls at the right margin of the screen, set `LineEndWord` = TRUE.
8. The newly created Line (which is temporary of course) should now be displayed on a single line of the Main screen. (The remaining words of the Turn are pushed to the next line, where they are displayed as before - as a paragraph with word wrap.) 

**Additional development**
1. Create an option on the File Import screen to import the "Paragaph" text type.
- "Paragraph" option comes immediately after "Song & Verse"
- Per line = Paragraph
- checkmark in "Whitespace" column (only)
- File = .txt
2. In the future, we might try to create Line breaks by paying attention to punctuation (comma, period, question mark, exclamation point) as Line splitters.

**Context**
Related to #654

**Comment by johnwdubois** [comment]
Good idea. This would be a new mode, parallel to the Rez and Track modes. Or maybe it's just a minor variation on the current Track mode. The idea is that marking of Rez links is turned off, and only Track links can be made.
    The main innovation that is needed to make this work is a kind of word-wrap function, so that a paragraph is displayed in several lines. (Currently, a paragraph would be displayed by Rezonator as a single long line, requiring the user to constantly use the horizontal scroll bar, which would make the task so annoying that such users would probably quit using Rezonator.) 
      (This could be a good use case for Samuel Venable's text insertion asset -- or maybe not.)

**Comment by johnwdubois** [comment]
This may be relatively simple:
1. The paragraph will end with a hard carriage return, so it will be automatically interpreted by Rezonator as a Unit (Utterance).
2. The key is to use several different Lines to display one Unit/Utterance.
3. The first 10 words go into the first line; the second 10 words go into the second line; etc.

**Comment by johnwdubois** [comment]
I changed "Paragraph" to "Prose" for the sake of clarity.
