### ISSUE TITLE
MTurk resources (old)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#483]
_**NOTE:**_ For the newer alternatives to MTurk, see #737  

**What (was) needed**
1. To support crowd-sourced annotation of linguistic data, Rezonator should be integrated with Mechanical Turk (MTurk) or an alternative.

**MTurk Resources**
Tutorial: Retrieving bounding box image annotations from MTurk
https://blog.mturk.com/tutorial-retrieving-bounding-box-image-annotations-from-mturk-253b86cb7502

QuestionForm (Tic Tac Toe example)
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QuestionFormDataStructureArticle.html

Formatted Content: XHTML
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_FormattedContentXHTMLArticle.html

GAMES: TIC TAC TOE. Etc.
https://turkerview.com/requesters/A36VTN3KTHRRWY
https://turkerview.com/requesters/AO1L2PEQ2WNYW

Doing psych experiments on MTurk (by Todd Gureckis):
http://gureckislab.org/courses/spring14/online_data_collection/lecture4.html

MTurk: External questions    
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html     

MTurk: External questions    
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/Concepts_HITsArticle.html#using-your-web-site-to-host-questions     

Integrating Mechanical Turk with Firebase       
https://github.com/ejolly/svelte-turk    

Chan, Chun (2017). Delivering web experiments using Amazon Mechanical Turk.    
http://groups.linguistics.northwestern.edu/documentation/v2/experiments/webExperiments/delivering_web_experiments_via_mturk.pdf    

**MTurk Basics**
Mechanical Turk 101: How to use MTurk for tagging training data
https://monkeylearn.com/blog/mechanical-turk-101-use-mturk-tagging-training-data/

General MTurk
https://blog.mturk.com/tutorial-using-the-mturk-sdks-together-with-the-requester-website-d46f94c66284

Tutorial: Managing Results With The Requester Website
https://blog.mturk.com/tutorial-managing-results-with-the-requester-website-219f6c809e47

Tutorial: Categorizing Names With The Requester Website
https://blog.mturk.com/tutorial-categorizing-names-with-the-requester-website-eef620ae8aa5

**Comment by johnwdubois** [comment]
Also check out PsiTurk:
https://psiturk.org/
https://github.com/NYUCCL/psiTurk

**Comment by Georgio-Klironomos** [comment]
PsiTurk seems promising for creating an HTML middleman between AlphaAI and MTurk! This video helped me grasp it much better http://gureckislab.org/courses/spring14/online_data_collection/lecture9.html

**Comment by johnwdubois** [comment]
Consider using LingoTurk, which fills a role comparable to PsiTurk, but is designed specifically for linguistics. Also, it uses the more modern web-based PlayFramework.

**Comment by johnwdubois** [comment]
This ticket contains old references; it is mostly superceded by #737 .
