### ISSUE TITLE
Stacker

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#484]
**Dev Hours**
20 Hours

**Background**
Sometimes it is useful to create Stacks automatically. Rezonator needs a way to do this.    
Minimally, a Stack is defined as a set of Units (or Lines).

**What is to be done**
1. Create a tool called Stacker (also a menu option called simply "Stack"). This will automatically create Stacks of various kinds. Some of these involve assigning every Unit/Line in a Discourse to a Stack. That is, the entire Discourse is exhaustively partitioned into a series of Stacks, with no lines left unassigned.
2. As with current Stacks, every Stack should have a unique stackId (integer).
3. Note that it is possible to have two (or more) _different_ assignment of Units/Lines to Stacks. 
- To allow users to define more more than one "Stacking" annotation for the same discourse, the Stack grid needs a field that will allow  users to specify one from a set of allowed stackTypes. 
- For display on the main screen, the user will need to specify just one stackType.
4. Here are some Stack types (= `stackType`) to let users create. All but the first can potentially be created automatically:
- Default (manual): The kind of manually created Stacks we have now.
- Turn (simple): Each turn at talk (continuous speech by a single speaker, until the next speaker begins speaking) equals one Stack. (In the new SBCorpus csv file, this Id value is already marked, in a field called "Turn".)
- Prosodic sentence (or pSent): A sequence of one or more Units (intonation units), which ends in a period (.) or question mark (?). (In a _different_ version of the SBCorpus csv file, this information is already available, marked via an ID value in a Field called "pSent".)
- Verse: When importing a song or a poem, define a "Verse" Stack based on the presence of a blank line.
- Random: Pick a number between randomly between 1 and 7 (with Zipfian probability distribution -- 1 is frequent, 7 is infrequent, etc.). This is how long to (arbitrarily) make the current Stack. For each successive Stack, generate a new quasi-random number.
5. Let users specify which type of Stack to Show (by selecting an option from the StackType field):
- Default (manual)
- Turn
- Prosodic sentence
- Paragraph
- Act (e.g. Question, Answer, etc.)
- Verse
- etc.
6. Be sure not to overwrite the user's manual Stacks! That's a lot of hard work lost, that may not be recoverable. This is why stackType is important.
7. Create a top-level menu item for Stack. This would contain as sub-menu choices:
- Create stacks (and select which type of Stack to create: Default, Turn, etc.
- Show stack (select which type of Stack to show on the main screen: Default, Turn, pSent, All, None, etc.
- StackShow 
8. The "s" key (not the "k" key) should let the user select "Stack mode". (For "Save file", we can just use "CTRL-s", which is what everyone expects.) 
9. When in Stack mode, you can make:
- Stacks
- Chains (probably Rez chains by default)
- Does this mean Stack mode is equivalent to Rez mode (by a different name)?

**Future development**
At a more advanced level, it is useful to recognize a more subtle definition of the Turn:
- Turns (advanced): Same as a simple Turns, except that a Backchannel utterance (a Unit consisting of a single word like unhhunh, spoken by a different speaker than the main speaker, does not count as interrupting the main speaker's Turn (which continues even after the Backchannel utterance. 
- Syntactic sentence (or synSent): A sequence of one or more Units that makes up a syntactic sentence. (This may be created by the user (manually) in Rezonator, or by a syntactic parser outside of Rezonator. But it is not the job of Rezonator to parse sentences.)

**Alternatives you have considered**
- Paragraph: Although it would be possible to treat a paragraph as a Stack, this is probably not the best way to implement Paragraphs.

**Checklist w/ dev hours**
- [x] Allow generation of Random Stacks - 2 hr
- [x] Allow Turn Stack Generation- 5 hr
- [x] Update Turn Stack Generation for new import process- 2 hr
- [x] Ensure random stacks cover every line of the discourse- 1 hr
- [x] Ensure Stack labels begin at "Stack 1"- 1 hr
- [x] Ensure "Clear Stacks" functions with random stacks- 4 hr

**Comment by Georgio-Klironomos** [comment]
Next step is connecting the Random and Turn stack generator functionality to the Menu Bar, will wait for Brady to push his menu bar changes.

**Comment by Georgio-Klironomos** [comment]
Random and Turn stack generation is working within the Menu Bar. Currently the turn stack generator works off of the "TurnOrder" column, we should decide if we'll use the "TurnID" column instead.

**Comment by Georgio-Klironomos** [comment]
Next step for @terrydubois and I on the stacker is getting a prototypical version of Stacktypes to work.

**Comment by johnwdubois** [comment]
Stacker bug (random stack): There is a missing line between every pair of Stacks.  Don't leave lines out -- the Stacking should be exhaustive (assigning every line to a Stack).

![Stacker bug - missing lines](https://user-images.githubusercontent.com/22628444/89604603-74e5ed00-d820-11ea-8452-aeb624c990a0.PNG)

**Comment by johnwdubois** [comment]
After using the Stacker to do a random stacking, the menu option "Advancec/Clear/Stacks" doesn't work.

![Stacker bug - _clear all Stacks_ doesn't work](https://user-images.githubusercontent.com/22628444/89605055-8085e380-d821-11ea-89b4-e19ad5be194c.PNG)

**Comment by Georgio-Klironomos** [comment]
The turn order stacker is now working nicely with the new SBC rez files.

**Comment by Georgio-Klironomos** [comment]
The basic implementation of the Stacker is fully functional and testing thoroughly. Further developments such as Sent Stacker (#524 ) and Stacktypes (#602 ) are housed in other tickets, so we'll close this one.
