### ISSUE TITLE
Edit Koan to Reflect Summer 2020 Goals

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#493]
**https://rezonator.koan.co/**

Koan is useful for keeping track of big picture goals. Jack and Geo will put in place and prioritize this Summer's goals in an easy to access place.

**Comment by johnwdubois** [comment]
Yes, it would be especially useful for @Georgio-Klironomos to check, and propose changes if needed, for:          
- due dates
- metric values (current & target)
- missing metrics: can we invent one?
- anything else that needs fixed
