### ISSUE TITLE
Create Stacktype field in Node map

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#497]
Stacktype will include types like Random, Default, Turn, etc.

Only one Stacktype will be visible in the discourse at a time.

**Comment by johnwdubois** [comment]
This may be confusing, or an oversimplification. There are times when more than one LEVEL of stack needs to be shown on the screen. For example, see #410 .

**Comment by johnwdubois** [comment]
Duplicate. Closed.
