### ISSUE TITLE
Splitters (unit delineating column for import)

### ISSUE THREAD

**Issue by terrydubois** [johnwdubois/rezonator#505]
**Dev Hours**
5 hours

**Background**
Rezonator's CSV import requires a column in the Import Screen for the user to delineate on a chosen unit value.    

**Splitters: What to do**  [JWD]
What Rezonator needs can be called an **utterance splitter**.     
In the long term, we will need splitters for several different units, The user will want to an option to specify **splitters** for the following:
- utt (utterance, a.k.a. unit)
- turn
- prosodic sentence (psent)
- sent (sentence)
- word

**Comment by Georgio-Klironomos** [comment]
Utterance and Turn splitters are implemented. We'll create tickets for the future splitters such as Psent and Sent
