### ISSUE TITLE
Language localization with JSON

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#513]
**Background**
Rezonator is all about languages, so it's important that we support as many of the world's speakers as possible, with all their variety of native languages.    
This is about the language that the Rezonator user **speaks**, _not_ the "target" language (the language that the conversation is in). How to display the target langauge is also highly relevant for Rezonator, but this is a very different problem. (The issue of how to display characters and fonts applies in both contexts, however.)    

**Describe the solution you'd like**
1. Collect all the text messages that are displayed to the user by Rezonator. This should include menu labels, Help screens, dialogue box messages, etc. (In the GML code, search for "draw_text" and "show_message".)
2. Organize the information in a spreadsheet (e.g. CSV or similar) that gives the following information:
- variable name (a brief but descriptive variable name, which communicates clearly the context in which the message is displayed, and the content of the message (e.g. menu_mydescription, help_mydescription, etc.)
- original message (in English, as the default) 
3. Revise the original (English) messages as needed, for clarity.
4. To support an open-ended set of languages quickly and reliably, use OmegaT. Using OmegaT, prepare a file that will implement localization (translation) of all messages displayed to the user.  OmegaT will make it easy to add new languages, without requiring any modification of the Rezonator code. 
5. Export from OmegaT to JSON. The JSON file is what will actually be loaded by Rezonator. 
6. When new languages are added, the only files that will need to change are the OmegaT files, and the JSON file that is created based on the OmegaT file. 
7. In GameMaker, implement a solution to display the relevant messages to the screen, based on the variable name plus the language selected by the user. (The solution proposed by "Yawning Dad" (see below) seems like a good one.) 
8. One modification of the "Yawning Dad" method is necessary. To let the the user select their language preference, he suggests using the arrow keys to cycle through all the available languages. Rezonator will support too many languages for this to be a reasonable solution. A better solution is this: From the main Menu. the user selects "Settings/Language". This presents a drop-down list of all the languages supported by Rezonator. The user selects one to use for displaying messages.
9. For a particular user-selected language, if there is no translation available for a particular variable (the translation for this message is missing), Rezonator should display the default language (English).

**GameMaker resources**
Here is how to implement this in GameMaker Studio (see the solution proposed by "Yawning Dad"):
[localization with JSON v.1](https://alexder.itch.io/json-localization-game-maker-studio)
[localization with JSON: video tutorial](https://forum.yoyogames.com/index.php?threads/making-your-games-multilingual-via-auto-loading-json-files.57659/)
[localization: Miscellaneous threads](https://forum.yoyogames.com/index.php?tags/localization/)
[localization with JSON](https://forum.yoyogames.com/index.php?threads/how-to-localize-your-game-using-json.55568/)

**Translation resources**
1. OmegaT is a good choice for a widely used, open-source resource that supports translation and localization:
- [OmegaT (free translation memory tool)](https://omegat.org/)
- [Okapi filters for OmegaT](http://okapiframework.org/wiki/index.php?title=Okapi_Filters_Plugin_for_OmegaT)
- [Okapi filters for OmegaT (JSON)](http://okapiframework.org/wiki/index.php/JSON_Filter)

2. _ISO standard language names_ (use these language names and abbreviations)
- [ISO language matrix](https://en.wikiversity.org/wiki/ISO_639-1_language_matrix)
- See also #639 

**Additional information (GameMaker Studio)**
_Fonts_
When it comes to languages, fonts, characters, and localization in GameMaker Studio 2, a good person to consult is FrostyCat. For GMS2, FrostyCat advocates using Raw TTF fonts from font_add() in native platforms.      
[FrostyCat tips re TTF fonts](https://forum.yoyogames.com/index.php?threads/localizing-for-chinese.1555/post-12887)
[FrostyCat comment: Google Play in India](https://forum.yoyogames.com/index.php?threads/advice-when-it-comes-to-loading-text-localization-solved.51963/post-371247)
[fonts](https://forum.yoyogames.com/index.php?tags/font/)

_Other_
[Add range](https://forum.yoyogames.com/index.php?threads/cyrillic-font-doesnt-work.44179/#post-272127)

**Comment by johnwdubois** [comment]
Some useful information:
https://www.textunited.com/blog/top-10-languages-localization/
https://www.textunited.com/blog/localize-your-business-languages/

**Comment by kayaulai** [comment]
Once we have the system ready, I can localise to Chinese (traditional + simplified). I can try French, Japanese and Tibetan as well, since there are existing resource for translating technology-related terms, though as a non-native speaker it would be hard to think of names for Rezonator-specific words. (Japanese would probably be easier though since we can just turn all of the words into katakana.)

**Comment by gtroiani** [comment]
<img width="564" alt="Italian_opening" src="https://user-images.githubusercontent.com/26060089/93830825-28b30880-fc26-11ea-87e7-128574bfbab4.PNG">

Added a script and an object to handle localization. Locale language is extracted from user's system and set as default. This is how the opening screen looks like in Italian.

**Comment by gtroiani** [comment]
The next step for this is creating the JSON dictionaries for the languages we want to implement. We are now working on Chinese, Hebrew, Italian, Japanese, Spanish, and Vietnamese.

**Comment by gtroiani** [comment]
Italian localization is completed and code is working. Glossaries in other languages will be committed soon.
