### ISSUE TITLE
Update Help Menu

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#516]
**Dev Hours**
3 Hours

**Is your feature request related to a problem?**
The Help List need to be updated to reflect current functions
.   
**Describe the solution you'd like**
1. The Menu and Help should show the following:
- Name (one-word name of function)
- Key (keyboard shortcut)
- Description (brief description of the function, displayed only when the user hovers)
2. Where possible, standard keystroke conventions are used that will be familiar to most computer users.
3. The document linked below indicates how Rezonator functions should be organized for the Menu and the Help List. As far as possible, these should be consistent with each other.

[Menu and Help List.docx](https://github.com/johnwdubois/rezonator/files/4537372/Menu.and.Help.List.docx)

**Comment by Georgio-Klironomos** [comment]
Created to split up the tasks of updating Menu and updating Help

**Comment by johnwdubois** [comment]
For future development, it may be good to integrate this with the JSON strategy for Localization (#513.) If so, you may want to to bring @gtroiani in on this.
