### ISSUE TITLE
Import speaker labels from Conllu/GUM

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#522]
**Background**
When information about _speaker labels_ is present in Conllu data, Rezonator should be able to import the information and put it in the right place.

**Describe the solution you'd like**
1. When importing Conllu data, check for the presence of _speaker labels_.
2. Automatically map the Conllu speaker labels into the Speaker column of the Main screen in Rezonator.
3. For test data, use the GUM corpus: the discourses labeled **interview** (look for the discourse "cyclone"). 

**Additional context**
Related to #517

**Comment by Georgio-Klironomos** [comment]
Georgio will debrief Brady on how to approach this problem, and Brady will start on it.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Speaker labels are now correctly importing thanks to Brady, and user testing has proven it works.
