### ISSUE TITLE
Stack menu "default" option doesn't work

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#527]
**Background**
On the Stack menu, the option "Create stacks/Default" doesn't work.

**To Reproduce**
1. Start Rezonator. Open a file.
2. From the main menu, choose the option "Stack/Create stacks/Default".
3. See the message that tells you what to do. Do what it says.
4. It doesn't work: nothing happens. No Stacks are created.

**What to do**
Make the dialogue message come true. Rezonator should do what you say it will do.

**Comment by Georgio-Klironomos** [comment]
Default Stack option now immediately allows user to create stacks. This fix will be will be included in the next build and user tested.
