### ISSUE TITLE
Replace old SBC .rez files with new SBC data 

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#528]
**Background**
The current .rez files for the SB Corpus are based on an old XML import of the transcription data (in DT1 format, but with mistakes). This XML data is hihgly problematic in many ways, and should not be distributed to the public. 

**What to do**
1. Create new .rez files for the 60 files of the SBCorpus.
2. The new .rez files should be based on an import of a (new and improved) version of the SB Corpus (using the transcription format DT2/DFT).
3. The new .rez files will be distributed with all future versions of Rezonator, beginning with the 0.9 release.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Brady's first priority this week will be manually creating the new set of Rez files based on the CSV format we've been given

**Comment by Georgio-Klironomos** [comment]
The Newest set of Rez files based on the latest SBC Schema are included in our current (non-public) version of Rezonator. They are ready to be released alongside 0.9.0, when the time comes.
