### ISSUE TITLE
Unshuffle

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#532]
**Bug**
When the user shuffles a discourse, there is no way to restore the original order.

**To Reproduce**
1. Shuffle a discourse (with Alt-Shift-e).
2. Try to unshuffle (restore the order you had). Doesn't work.

**Describe what to do for the desired behavior**
1. Allow the user to unshuffle (restore the original order) after a shuffle.
2. Be sure to test by loading 2 or more conversations, to make sure you can restore the order when multiple discourses are present (multiple discoId).

**Comment by Georgio-Klironomos** [comment]
@johnwdubois the user can unshuffle the discourse by right clicking the speaker labels and selecting "restore order", however this isn't present in the help menu. We'll add it there, also the restore order does work with 2 discourses.
