### ISSUE TITLE
Remember column width in GridView

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#533]
**Is your feature request related to a problem?**
Among the many painful UI issues with GridView, the one that could bring the most immediate improvement with the least effort is probably this: Remembering the user-defined column width in GridView.

**What to do**
1. When the user resizes the gridView columns, remember the column width. It should be stored, so that it is retained the next time this user opens any Rezonator file. 
2. The Rezonator default setting for column width in GridView should be smarter to begin with. The default column width should be appropriate for the kind of information that typically appears in the column. 
- Set a default column width, and remember it permanently as the Rezonator default, to be used upon loading.
- There's no need to wait for the user to fix the column width. We can manually choose a good width for each column (e.g. for SBC Corpus imports), and save this as the default value to start with (perhaps as part of the import schema).

**Future development** 
1. If possible, use wider columns, filling out the whole GridView screen horizontally . 
2. Consider making the columns resize automatically in GridView, to fit the size of their contents. 

**Additional context**
For information on related GridView issues, see #4, #103, #104, #109, #236.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Terry has finished programming the grid view column widths to be remembered, we'll close the ticket once it's user tested

**Comment by Georgio-Klironomos** [comment]
User testing and internal testing show the Grid View column widths getting remembered. I'll create a separate ticket for more effectively using the space in the Grid View screen.
