### ISSUE TITLE
Broken buttons and GridView escape

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#534]
**Background**
A new user who ends up in GridView by mistake may get confused about how to get out. Right now the Tool buttons that appear in GridView do not work, which is a frustrating experience: broken GridView buttons!

**What to do**
Implement several different ways for the user to _escape_ from GridView, and get back to the Main view. Any one of the following should work to take you back to the Main view:
1. If the user Clicks on any icon for Read, Track, or Rez mode: This should take you to the Main screen, not leave you in GridView. 
- To make the button _work_  requires taking you to the right place!
- Test whether the user is in GridView, when they press one of the tool buttons. If they do, take them back to the Main screen.
2. If the user presses the "Escape" key, this should take you to the Main screen, not leave you in GridView 
3. If the user does a Search (with the "f" key), this should take you to the Search/Hit screen, not leave you in GridView.

**Future development**
Consider implementing the following: Clicking on any button that has no possible meaning in GridView should probably take you back to the main screen.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois While in Grid View, pressing any of the tool buttons, the ESC key, or searching a word will take you out of the Grid View. Also, the ESC key will get you out of the Search Screen. Now to the user tests!

**Comment by Georgio-Klironomos** [comment]
Back arrow has been added to the Grid View screen, giving the user ample ways to get back to the main screen.
