### ISSUE TITLE
User-friendly export: Basics

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#538]
**Background**
The simplest thing we can do to make the CSV export more user-friendly is this: Don't confuse the user.     
This means not exposing users to CSV files they have no use for. 

**What to export: Grids**
Not all Rezonator grids are equally relevant to the user. Export only the grids that are actually useful to the user. 
1. DO NOT export grids that are only for internal use by Rezonator.    
2. Export grids that contain one or both of the following:    
- New data that were created by the user within Rezonator (links, chains, etc.) 
- User data to which Rezonator has added a new index value (such as the words, units, etc. that were imported by the user into Rezonator)     
3. Include information that is needed for context, to make the new Rezonator data understandable. This may include strings (e.g. "text") copied from the original, imported conversation data.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois The only CSV's being exported now are the ones relevant to the user.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois This feature has now been user tested and works as expected
