### ISSUE TITLE
Song import should suppress "import mapping" screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#547]
**Bug**
When the user imports plain text, which is recognized to be song or poem etc (no interlinear glossed text markers, etc.), the user is shown "import mapping" screen. This is:
- useless
- prone to introduce error (if the user clicks on the wrong choice)

**Fix**
When the user imports plain text, which is recognized to be song or poem etc, do the following:
- suppress the "import mapping" screen (don't show it)
- immediately display the main Rezonator screen.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Brady and Terry have made it such that song lyrics go straight to the main screen, preventing confusion from happening during this simple import. User testing has shown it to be very helpful.
