### ISSUE TITLE
Highlighted line in the Nav window fails to display characters characters correctly

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#548]
**Bug**
For languages like Hindi or Nepali, the highlighted lines in the Nav window fails to display characters characters correctly. This will happen for many languages, because the script and fonts do not have a font for italics. (Many also lack boldface.)

**To reproduce**
1. Import the Zurich data. Select the Nepali (\nep) field for Unit display.
2. Click on a line to highlight it. See the missing characters.

**Fix**
Do not use boldface or italics for highlighting lines or words in the Nav window (nor anywhere else in Rezonator). Use color instead.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois All instances of the bold font have been replaced with our regular font, preventing any of the missing character instances.
