### ISSUE TITLE
Empty space detector fails

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#549]
**Bug**
When a user tries to quit a Track chain or Rez chain by clicking on empty space, most of the time this fails. The user has to click around repeatedly to get it to work.

**To Reproduce**
1. Make a Track chain. To quit the chain, click on a nearby empty space.
2. Try this with max line height etc.
3. It fails repeatedly.

**Describe what to do for the desired behavior**
1. Make a highly reliable EmptySpaceDetector. This should recognize all the "empty" space on the screen, meaning places where there are no words, no speaker labels, no Nav window, etc.
2. Consider creating a developer display to show all of the empty space on the current screen (e.g. in green).
3. Test with all line heights, font size, etc.
4. Make sure that a single click in EmptySpace is recognized as such, and results in quitting the current chain.

**Comment by Georgio-Klironomos** [comment]
Empty space detector's new and improved functionality held up during user testing.
