### ISSUE TITLE
Scrolling within the Help menu also scrolls in the main screen

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#554]
**What is the background of this bug report?**
When the user has the Help Menu open and tries to scroll using the arrow keys, the scrolling will also affect the main screen scroll bar.

**To Reproduce**
1. Open the Help menu pop out
2. Scroll through the help options using the arrow keys
3. See that the main screen is also scrolling

**Describe what to do for the desired behavior**
When the Help menu is open, scrolling should only affect the help menu. And when it is closed then scrolling should only affect the main screen.

**Desktop (please complete the following information):**
 - OS: MacOS, WIndows
 - Version: 0.8.84

**What is the estimated development time?**
2 Hours

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] Completely separate the scrolling within the help menu - 1 hr
- [x] Test to ensure the scrolling is now independent- 2 hr

**Comment by Georgio-Klironomos** [comment]
Scrolling is separated between the help menu and the main screen, and based on which window the mouse is hovering over.

**Comment by johnwdubois** [comment]
**Problem**
Now we need to fix the exact same fix, except for touch screens:    
- If you drag your finger over the Help screen items, you can change the which Help item is focused, BUT....
- The text in the Main screen scrolls at the same time.
**Fix**
Make sure that the only thing that scrolls is what they user's finger is hovering over (either Help menu or Main screen, but not both).
