### ISSUE TITLE
CSV file validation & schema

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#556]
**Background**
It is important to validate the structure of CSV data files before they are imported into Rezonator.

**Validation: What to do**
1. For CSV data files that are to be imported into Rezonator, test them to validate the structure.
- https://blog.openbridge.com/how-to-do-csv-file-validation-and-schema-generation-43a9cb78e1eb
- https://csvlint.com/

**Validation: Additional resources**
- http://digital-preservation.github.io/csv-validator/
- https://csvlint.io/about

**Schema: What to do**
1. Create a schema for valid data:
- https://blog.openbridge.com/how-to-do-csv-file-validation-and-schema-generation-43a9cb78e1eb

**Schema: Additional resources**
- http://digital-preservation.github.io/csv-schema/
- https://github.com/digital-preservation/csv-schema

**Comment by Georgio-Klironomos** [comment]
@johnwdubois The current CSV's are verified to be UTF-8. Ryan has fixed the previous newLine error, and we're now using the default GameMaker CSV loader, which works better and faster than Juju's script (no disrespect to Juju, that's just how it is)
