### ISSUE TITLE
Clip from Stack

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#559]
**Background**
The current way of making a Clip is clunky, and makes an unnecessary burden on the user: to type in two line numbers, which they don't know.    

**What do do**
Implement a much easier way for the user to make a Clip, using the Stack function.
1. Let the user focus a Stack, either in the Main screen or in the left Nav window.
2. On the right-click menu, show an option: "Clip"
3. If the user selects this, make a clip as follows:
- the first line of the Clip is the first line of the Stack 
- the last line of the Clip is the last line of the Stack 
4. Eliminate the current method of making a Clip (which asks the user to type in 2 line numbers).

**Comment by Georgio-Klironomos** [comment]
The new Clip from Stack feature has been User tested and internally tested. The old Export Portion is now commented out.
