### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#561]
Revise the menu for clarity, as follows:

![Menu 2020-09-01](https://user-images.githubusercontent.com/22628444/91918647-613f7200-ec78-11ea-9ce9-1e41930a4ac1.PNG)

Related to #457

**Comment by johnwdubois** [comment]
To update the menu design, prototype it first using Google Sheets: 
https://docs.google.com/spreadsheets/d/1-HWrz17GJQLi4Zeoz2dpS4_UXJy1-6aZcQKiaPkESlc/edit?usp=sharing

**Comment by Georgio-Klironomos** [comment]
@johnwdubois All of the functions we already had functional are now in place in the new menu. Terry and Brady are now working on creating and implementing the new functionality listed in the Menu bar redesign.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Everything in this menu redesign, outside of undeveloped features, is built. Here's the newly made tickets for the undeveloped features: "Data": #630 , "Tag Set": #631 , "Find Next": #632 , "Field": #633 , "Search Options": #634 , "Stackshow Tutorial": #635 , "Language": #636

**Comment by Georgio-Klironomos** [comment]
This iteration of the Menu has been tested, and proves to be a big improvement.
