### ISSUE TITLE
Large grid name display in GridView

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#563]
**Background**
The name of the grid that is selected in GridView is extremely small and hard to read, making it hard to interpret the data you are looking at. There should be an easy fix, and there is.

**What to do**
At the top of the screen in GridView, display **in a very large font** the name of the currently selected grid (the grid whose tab has been selected). Label this as follows:
- **Grid:** [gridname]

**Additional development**
1. When the user presses the [TAB] key, shift the focus to the next tab to the right (the next Grid in the sequence of grids).
2. When the user presses the ALT-[TAB] key, shift the focus to the next tab to the left (the previous Grid in the sequence of grids).

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] Show current grid name in a big font - 1 hr
- [x] Select next grid using [TAB] key - 1 hr

**Additional context**
Related to

**Comment by Georgio-Klironomos** [comment]
The new grid Name Display and navigation bit Tab has been built and user tested.
