### ISSUE TITLE
Dropdown list of Grid names in Gridview

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#565]
**Background**
It's hard to see the names of Grids in the GridView pane. If you can't see them, you can't select them.

**What to do**
1. Show a drop-down list of Grid names in the GridView pane.
2. If the user clicks on a Grid name from this list, set the Tab to this Grid.
3. Note that this is _in addition_ to showing the grid names on each Tab. No need to change the Tab setup for now. 
4. The user activates the drop-down list by clicking on the large label for the current Grid name.
5. For readability, make sure to:
- Use a large font for grid names in the drop-down list 
- Allow plenty of width in the drop-down list to show long grid names
- It's okay if the drop-down list appears on top of the gridview display (assuming that the list goes away once a new Grid is selected).

**Additional context**
Related to #563 -- the user clicks on this large label to get the drop-down list.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Terry has created the Grid View dropdown to allow for easy access to all the grids. The only issue currently is a few long names being cut off, but we'll have a fix for that soon.
