### ISSUE TITLE
Import data screen: File type selection

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#567]
**Background**
We need to know the user intent when they are importing data.    
Users often have a hard time understanding what their import options are. We should help them provide us with more information about what kind of import they are trying to do, Discovering the user intent can be accomplished using the "Import Data" screen, which currently has little information, and hence little value for the user. If the user provides more information about their intent on the "Import Data" screen, this can be used to make better imports, easier for them and for us.

**What to do**
1. Show the users an informative version of the "Import Data" screen that displays their import options. Users select a radio button corresponding to their import data type:

![Import screen options 02](https://user-images.githubusercontent.com/22628444/92620260-4f149380-f277-11ea-9bac-c216cc21c40e.PNG)

2. When the user has selected an option
- the "Continue" button appears in the lower right corner
3. When the user presses "Continue", Rezonator captures the information from the radio button in a variable `ImportFileType`
4. Based on the user-selected `ImportFileType`, Rezonator does the following:
- activates the `ImportSchema` that was most recently stored _**for that import file type**_ 
- processes the imported data according to the `ImportSchema` (field mapping, defaults, ShowFieldsList, etc)

**Further development**
The first phase (fully described above) requires only a list of options (with radio buttons), and a "Continue" button. The rest of the "Import data" screen (the other 3 boxes displayed) is slated for further development, as follows:
1. When the user selects a radio button, 
- Show a sample of the kind of data to illlustrate each option. 
- Show the example in a separate text panel off to the right side (greyed out).
- For instance, show an example of a song, a line of interlinear glossed text, etc. 
- This example will be shown greyed out, to make clear that it is a canned example, selected in advance by us to illustrate the concept, rather than live data.
2. Show the example only when 
- the user hovers over a specific option (radio button)
- the user selects a specific option (radio button) 
3. For each option, Rezonator will store the following data: 
- text of short descriptions (bullet lists)
- text of one representative example (canned, not live)
- URL links to more data of this kind (optional)
4. Rezonator.com should have a landing page called data.rezonator.com where users can go to find data, links, etc.
5. Radio button options that are not yet implemented (e.g. "Prose", a.k.a. "Paragraph") can be grayed out, or left off the list.

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] Implement functionality of file type selection - 2 hr
- [x] Create rough draft UI for File Type selection - 1 hr
- [x] Connect UI to functionality- 1 hr
- [x] Polish File Type Selection UI - 2 hr
- [x] Streamline schema use between File Type screen and Import screen - 2 hr

**Comment by Georgio-Klironomos** [comment]
@johnwdubois this coming Monday, either Terry or Brady will show where this feature is at and get clarification on it's next step. Long story short, a prototypical version is on the newest release and will be user tested.
