### ISSUE TITLE
Less is more

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#571]
**Background**
_"Can't see the forest for the trees."_    
When a .rez file contains many fields (for example, the SB Corpus), it can be difficult for the user to see the most interesting kinds of data.

**What to do**
1. Help the user easily choose which fields to display in the Nav window, and in the Main screen.
2. Remember these choices as part of a display schema (`showFieldSchema`). 
3. Ship Rezonator with a standard display schema (`showFieldSchema`) for data that is shipped with Rezonator (e.g. the SBC files). 

**Related to**
#577

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Now that Brady has all the Rez files, he'll just need the specifications for which columns to display as default in the Nav window, and then he can set all the Rez files to match that

**Comment by Georgio-Klironomos** [comment]
@johnwdubois  All of the rez files prepped to ship with 0.9.0 have their default fields set to what you, terry, and brady specified. This feature has also been user tested, and helped in preventing the user from getting overwhelmed.
