### ISSUE TITLE
Backspace in Text Input on Mac causes problems

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#573]
**What is the background of this bug report?**
When using Rezonator on a Mac, trying to backspace during text input causes weird characters to appear and sometimes prevents more backspacing. This problem has not occurred on Windows machines, so it appears Mac specific.

**To Reproduce**
1. On the Mac version on Rezonator, open up a text input dialog box (such as the search box)
2. Type in a few characters, then attempt to backspace
3. See that an odd character is created, and backspace now takes a couple of presses to work

**Describe what to do for the desired behavior**
Text input on Mac should function as it does on Windows, without creating odd characters and making it difficult to edit text.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 0.8.86

**What is the estimated development time?**
3 Hours

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [ ] Identify what is causing this problem in the text input scripts - 1 hr
- [ ] Fix the issue- 1 hr
- [ ] Test to ensure text input works correctly on both Windows and Mac- 1 hr

**Comment by hopesu21** [comment]
This issue does not exist in Windows.
