### ISSUE TITLE
Default fields to show for Token & Unit

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#577]
**Background**
A .rez file should include a list of default fields to show, in a default order, with default column width.

**What to do**
Create a ShowFieldList (default) for the Santa Barbara Corpus, like the following:

_Unit Fields_
Create a ShowUnitFieldList with the following fields, in this order:
1. ~rzUnitId
2. UnitId
3. TurnId
4. *Participant (= agent) 
5. UnitLen
6. UnitStart
7. UnitEnd

_Token Fields_
Create at ShowTokenFieldList with the following:
1. ~rzUnitId
2. ~rzTokenId
3. Order
4. Place
5. *Transcript
6. Text
7. Tag (= tag_Spacy)
8. Dep (=depRel_Spacy
9. Kind

**Details**
1. Asterisk (*) indicates which field should be shown by default:
- Transcript (for Tokens, in the Main screen)
- Participant (for Units, in the speaker column)
2. Rezonator also needs to specify a default field for Search. Normally this will be the **Text** field.
3. Rezonator also needs to specify a list to cycle through for the "w" key:
- Transcript
- Text
4. NOTE: It will be important to distinguish between Rezonator ID values (such as ~rzUnitId and ~rzTokenId) vs. user-supplied ID values (such as UnitId and TokenId).
5. Why are there duplicate fields (2 "Place" columns, etc.)?

**Column width**
Create a ShowFieldWidth (default) for the Santa Barbara Corpus. Each field should be saved with one of the following default width values:
- small
- medium
- large
(Or of course, you could do better by assigning a percentage of the total available space, summing to 100 or less.)

**Related to**
#571

**Comment by Georgio-Klironomos** [comment]
The correct default fields are being displayed correctly in the latest batch of Rez files, and this new default has been user tested.
