### ISSUE TITLE
"j" key cycle

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#579]
**Background**
The "j" key doesn't do much for the user. In particular, it does not give easy access to right-justified options.

**What to do**
1. In the Main screen, the "j" key should give easy access to _both_ left-justified and right-justified options. It should cycle through the following:
- left-justified + prose
- left-justified + grid
- right-justified + grid
- right-justified + prose
2. Note that for the Main screen, center-justified is not included in the cycle, because in this context it is a more specialized function (which the user can activate via the menu if necessary). 
3. In the Search screen, the default justification is center-justified. But in addition, the "j" key should give easy access to left-justified and right-justified options. Thus in this context, the "j" key should cycle through the following:
- center-justified + grid
- center-justified + prose
- left-justified + prose
- left-justified + grid
- right-justified + grid
- right-justified + prose
4. Whenever the user changes the view (to the Main screen or Search screen), reset the justification to the default for that screen.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois We now how the specified cycle happening with the J key in the main screen. We currently don't have text justification capabilities for the Search Screen outside of the Center alignment, so we'll need to program these in.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois A quick attempt at implementing right and left alignment into the Search Screen is showing us that this won't be a simple task. I'll create a new ticket for that task specifically.

**Comment by Georgio-Klironomos** [comment]
User tests show this new feature is intuitive, especially with the new Justify icons.
