### ISSUE TITLE
"u" key toggles display of Unit tags

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#581]
**Background**
Users need easy access to display options for "Unit-level tags.

**What to do**
Set the "u" key to toggle the display of Unit-level tags in the Nav window (alternating with token-level tags). It toggles between:
- display Unit-level tags 
- display Token-level tags

**Comment by Georgio-Klironomos** [comment]
"U" key now allows users to switch easily between Unit-level and Token-level tags, and this feature has been user testing.
