### ISSUE TITLE
Read mode warning is annoying

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#582]
**Background**
The Read mode warning is annoying, harassing the user unnecessarily.

**What to do**
Put a check-box option at the bottom of the message box, to turn it off, with this message:
- "[  ] Don't display this message again"

**Future development**
1. Make the warning smarter to begin with, so it is only triggered when relevant.
2. For example, allow the user to click (and double-click) on line numbers, to select a unit for display in the Nav window. This should not trigger a Read-mode warning.

**Comment by Georgio-Klironomos** [comment]
There is now a toggle option on Read Mode Hint that allows the user to prevent the pop-up from showing up again. User testing showed this feature to be very useful.

**Comment by johnwdubois** [comment]
The warning is still annoying: It triggers when it's irrelevant. 
- Allow the user to click (and double-click) on line numbers or speaker labels.  This should NOT trigger a Read-mode warning.
- Why? Because clicking on line numbers or speaker labels has a (non-destructive) effect on updating the Nav window display, which means it is a legitimate user action in Read mode,

**Comment by Georgio-Klironomos** [comment]
The Read mode hint is now only triggered by clicking on words within the main screen, no longer being activated by selecting the line numbers or speaker labels.
