### ISSUE TITLE
MinMax 2-for-1 selection

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#583]
**Background**
When you minimize line height and maximize font size, strange things happen, especially when selected a word.

**To Reproduce**
1. Maximize font size
2. Minimize line height 
3. Choose Rez mode or Track mode, 
4. Find a word that is partially covering another word in the line below. 
- Place the cursor at the midpoint vertically between the two words, 
- Click to select.
- Notice that both words are selected: Not good.
6. Move to the Speaker labels. Find a speaker label that is partly covering the label below.
- click halfway between the two labels.
- Notice that both lines are selected for the Stack: Not good.
- Click DELETE at the half-way point. Notice that 2 lines are deleted from the Stack. Not good. 

**Screenshots**
![Minmax 02 Two for one word selection](https://user-images.githubusercontent.com/22628444/93006340-d9772480-f50f-11ea-82d7-0b4c43f50cf5.PNG)

![Minmax 03 Two for one line selection](https://user-images.githubusercontent.com/22628444/93006345-e267f600-f50f-11ea-8fdc-3d6ac9c63e93.PNG)

**Desired behavior**
1. Correct the underlying problem first. Do NOT simply put a limit on line height and/or font size. Make sure that a single click cannot:
- select two words at once
- select two lines at once
- delete two lines at once
2. _After_ the deeper problem has been addressed, you may also want to put a different limit on line height, which is sensitive to the current font size.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Our mouse over word check now prevents 2 words from being clicked on, hovered over, or deleted at the same time. Also, the minimum line height is now tied directly to Font size, preventing any vertical word overlap.

**Comment by Georgio-Klironomos** [comment]
The fix to this issue has been now user tested and internally tested. We can say for sure that only 1 word can be clicked at a time.
