### ISSUE TITLE
Bleed-through words in the Search screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#584]
**Background**
The MinMax test also reveals other problems. In the Search screen, words are showing through the speaker labels. These are misplaced or bleed-through words.

**To Reproduce**
1. Maximize font size
2. Minimize line height 
3. Do a Search for the word "the".
4. Use the End key or arrow keys to scroll right.
5. Look at the speaker labels. White bars are showing through. Their width reflects the width of the word underneath -- a kind of misplaced or bleed-through word (not the same as the ghost word problem).

**Screenshots**
![Minmax 01 Search screen ghost words under speaker labels](https://user-images.githubusercontent.com/22628444/93006356-0592a580-f510-11ea-9e02-28711c2dd177.PNG)

**Desired behavior**
1. The fix: Do NOT simply put a limit on line height. Instead, first fix the underlying problem:
2. Words (even remnants of misplaced words) should not bleed through from underneath the Speaker labels.**Describe what to do for the desired behavior**
3. Make sure that misplaced words cannot be displayed, or clicked on, through the speaker labels. 
4. _After_ the deeper problem has been addressed, you may also want to put a different limit on line height, which is sensitive to the current font size.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Now words that are completely behind the speaker labels or line numbers are not drown nor checked for mouse clicks, preventing the bleed through.

**Comment by Georgio-Klironomos** [comment]
The fix to this issue has been tested by users and by the dev team.
