### ISSUE TITLE
Move documentation button off of the opening screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#586]
**background**
The documentation button takes the user away from the program they just opened. Not good.
Also, the text of the button sounds too hyped, like an ad for a product.

**What to do**
1. Move the documentation button to a better location, on a different screen
2. The button should have a simple one- or two-word label, such as: 
- "Help (online)"

**Screenshot**
![Documentation button misplaced](https://user-images.githubusercontent.com/22628444/93006845-28c05380-f516-11ea-989f-c3f3436a577a.PNG)

**Comment by Georgio-Klironomos** [comment]
The new documentation button on the main screen Now appears just as a simple question mark, and communicates to the user that it will take them to a webpage.
