### ISSUE TITLE
Stack Tags: Act, Repair, Act Sequence

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#590]
**Background**
It's important to allow users to attach Tags to Stacks.

**What to do**
Create several Fields in the Stack grid, which will allow users to attach a Tag (label) to a specific Stack.
1. To start with, there will be just 3 Fields (columns), displayed in the Contents pane of the Nav window (whenever the user has selected the Stack tab). The Stack Tag columns should have the following headers:
- Act
- Repair
- Act Sequence 
2. By default, _in Read mode_ the Stack tab shows a "1-to-many" relationship:  One Stack maps to many Units (lines)
3. Create a new button somewhere in the Nav window to control what appears in the right (Contents) pane for a Stack. It toggles between:
- "1-to-many"
- "1-to-1"
4. To annotate their data, the user should do the following:
- Select the Stack tab in the Nav window
- Click to toggle the "1-to-1" button (vs. "1-to-many", which is the default in Read mode)
- In the right (Contents) Pane of the Nav window, select one of the 3 columns to edit
- Use the arrow keys or mouse to move to a row that corresponds to the specific Stack that is of interest
- Type a Tag in this row, to attach it to the relevant Stack
- Or, ideally, the user can simply select a Tag from a predefined Tagset for this column (see TagSets below)
5. When in the Stack tab, the "u" key can be used to toggle between the "1-to-1" and  "1-to-many" options. (This is similar to the toggle function of the "u" key in Read mode, where it toggles between the 1-to-1 mappings of the Unit-level vs. the 1-to-many mappings at the Token level.)
6. To help the user remember what the content of the current Stack is, replace the uninformative string "Stack 1" with a more informative string created by concatenating the text of all the lines in the current Stack (such "I mean who are you, Polyanna?" -- see the second screenshot below).

**Fields & TagSets**
The following shows the 3 Stack fields, with their associated TagSets. 

Act|Repair|Act Sequence
--- | --- | ---
Question|Break|Q&A    
Answer|Edit|Repair   
|   |Fix|    

**Example**
The following example illustrates how a user might annotate a small stretch of conversation, attaching one or more Tags to each Stack:   

StackId|Act|Repair| Act Sequence
--- | --- | --- | ---
1|Question||Q&A
2|Answer||Q&A
3|Question||Q&A
4|Answer||Q&A
5||Break|Repair
6||Edit|Repair
7||Fix|Repair
8|Question||Q&A
9|Answer||Q&A
10||Break|Repair
11||Fix|Repair     

**Future development**
Allow the user to sort the Contents of the Nav window by any of the Fields/columns.

**Screenshots**
The following screenshot shows Questions and Answers, marked as Stacks. All are from SBC005.    
The goal of this ticket is to allow the user to annotate their data to show:
- (1) which Stacks are Questions and which are Answers; 
- (2) which Stacks are part of a Q&A act sequence.

<img width="960" alt="QandA 01" src="https://user-images.githubusercontent.com/22628444/70416901-f0369b00-1a14-11ea-905f-1fb5e1d31acd.PNG">

The following screenshot shows the use of a more informative string, created by concatenating the text of all the lines in the current Stack (such "I mean who are you, Polyanna?"):

![Stack tag renaming for Q and A](https://user-images.githubusercontent.com/22628444/93821692-93d0ff00-fc67-11ea-931f-ccdfc42e2907.PNG)

**Additional context**
1. Sometimes there is a Question that receives no answer. It is nevertheless useful to allow users to mark this as part of an "Act Sequence", even though it is defective (incomplete). This lets the user show that even though it is a Question, it is not paired with an Answer.
2. Another important "Act Sequence" is "Repair", where the first, second, and third parts of the Act Sequence are:
- break (=reparandum, the mistake or false start)
- edit (= edit marker, communicating that a repair will be made. For example: "I mean")
- repair (the "replacement" text produced by the speaker to fix the problem

**Checklist w/ dev hours**
- [x] Creating Prototype - 5 hr
- [x] Allow for display of stack contents in chain list- 2 hr
- [x] Fix display of contents for Random Stacks- 3 hr
- [x] Polish Tag Display- 3 hr

**Comment by Georgio-Klironomos** [comment]
@johnwdubois this implementation of Stack Tags is fully functional and polished. It has also been user tested.
