### ISSUE TITLE
Arrow keys don't work with right- or center-justified text

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#592]
**Background**
People expect arrow keys to work the same for navigation, regardless of what pane, view, or justification.

**To Reproduce**
1. Open a document.  
2. Find a long line of text, or simply increase the column width to make the text long.
3. Right-justify the text (using menu Justify/Right or the "j" key).
4. Try the following keys:
- left arrow
- right arrow
- Home
- End
5. Notice that the arrow keys don't produce the expected result.
6. Center-justify the text (using menu Justify/Center).
7. Again, notice that the arrow keys don't produce the expected result.

**Describe what to do for the desired behavior**
Make sure the arrow keys produce the expected result, when looking at right justified (or center justified) text.

**Additional context**
Notice that in the Search screen, the arrow keys DO  work for center-justified text. So the problem has been solved at least in that context.

**Comment by hopesu21** [comment]
No longer an issue as of 0.9.2.6. Arrow keys work with all way of justifying text.
