### ISSUE TITLE
Rezonator makes random stubby Rez chains

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#595]
**Background**
Rezonator creates hundreds of random stubby Rez chains, each one word long -- when you're not even trying to make Rez chains.

**To Reproduce**
1. Open SBC007.
2. Drag across several Speaker labels to make some quick Stacks.
3. Notice the strange Stack labels: "Stack 309" is the first Stack.
4. Check out the Rez tab: more than 300 Rez "chains", each consisting of a single word, were created for no clear reason.

**Describe what to do for the desired behavior**
1. Rezonator should not create hundreds of random stubby Rez chains, each one word long, when you're trying to make Stacks.
2. Rezonator should not treat the naming/numbering of Stacks as a continuation of the naming/numbering of Rez chains.

**Screenshot**
When the user makes a few Stacks (see the Main screen), Rezonator generates lots of fake Rez chains (see Nav contents pane:

![Random solo Rez chains](https://user-images.githubusercontent.com/22628444/93284422-5be73900-f7db-11ea-921f-38e003170b8b.PNG)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois when you have a moment, could you send us this rez file, if you still have it? This seems to be another strange case that we are not able to replicate, though I have a hunch it has to do with some Link Grid weirdness, so being able to look at the grids in this file will help.

**Comment by johnwdubois** [comment]
- Looks like it might have to do with AutoSave intervening when the use is in the middle of an action: For example, there's a drag (MouseDown) across the speaker labels, but not MouseUp yet, when the AutoSave starts.
 - Another thought: this may have to do with the automatic Stacker gone wild?

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Turns out it was the Random Stacker adding to the wrong Chain Grid. Terry was able to patch this up and prevent the random rez chains.
