### ISSUE TITLE
Eliminate "Rezzles" and other old data

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#598]
There are some old data directories and files that are either obsolete, or simply untested, with the new Rezonator release (0.9.0). It's better to eliminate them. For example:
- Remove "Tutorial" directory and its contents
- Remove "Rezzles" directory (under "Games")
- Rename "Games" directory to "Play & Learn"

**Comment by Georgio-Klironomos** [comment]
@johnwdubois THese directory changes have been implemented for the new release

**Comment by Georgio-Klironomos** [comment]
The cleaner directory appears with the 0.9.0.1 download.
