### ISSUE TITLE
Eliminate secret codes: No Arg0 etc

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#605]
**Background**
When meaningless or opaque names are used for arguments, "levels", variables, or data in grids:
- Secrecy and opacity cause problems for maintaining code
- Secrecy and opacity are not welcoming to new coders and new users 
- Secrecy and opacity cause problems for user-friendly export 

**Solution**
1. Eliminate all instances of Arg0, Arg1, Arg2 and similar in the Rezonator code.
2. Eliminate "levels" (0,1,2,3...), which act as secret codes, excluding new coders.
3. Always use meaningful and clear names for:
- arguments
- other variables
- values in grids
- tiers, etc.
4. Make every value in every column of every exportable grid user-friendly
- use readable and interpretable names
- applies whether the grid is exported as CSV or not.

**Related to**
See the new options for functions in GML 2.3: #486

**Comment by Georgio-Klironomos** [comment]
Arguments have been given readable variable name, and so have the word and chain states. However, we'll have to wait for the grid rehauls to change their values to strings, as this will prevent backwards compatibility with current Rez files.
