### ISSUE TITLE
Message blocks words & extends offscreen 

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#606]
**Background**
Messages displayed to the user sometimes:
- hide words (by sitting on top of them)
- extend offscreen, so they are effectively hidden to the user
This problem arises for the Read mode warning, messages in _Where's Elmo?_, etc. While the Read mode warning message may not be the most important message in the world, it is still useful to get it right, as a model that can be extended to other messages directed to the user (such as in _Where's Elmo?)_.

**To Reproduce**
1. Open a rez file. Make sure that the "Read mode" warning is active.
2. Click on the last line visible at the bottom of the screen.
3. Notice that most of the message is hidden offscreen, making it impossible to read, and to click on the option "Do not show this message again".
4. On a line that contains many words, click on the first word of the line. 
5. Notice that the Read mode message now hides many words in the line, even though there is plenty of "empty space" available nearby that could be used to display the message.

**Desired behavior**
Make good use of the EmptySpace detector!
1. When displaying this (or any other) message, make sure that the message:
- is fully visible to the user (not partially hidden offscreen)
- does not cover up words (unless there's no other solution)
2. To implement this
- use the EmptySpace detector to identify a region large enough to display the current message entirely (or mostly) over empty space
- monitor the edges of the screen (especially the bottom edge) to make sure the message doesn't extend offscreen; adjust placement of the message as necessary
3. Make sure this works for:
- Read mode message
- Where's Elmo messages
- Other messages to the user

**Screenshots**
This screenshot illustrates _**both**_ problems: message blocks words, and message extends offscreen.

![Messages block words 02](https://user-images.githubusercontent.com/22628444/93738655-fdf98d80-fbee-11ea-966c-56089da9e400.PNG)

**Comment by ZoeF99** [comment]
Data type "Interlinear Glossed Text" and its per line format "Unit per block (?)" are also hidden to the user in Mac 9.2.2

**Comment by hopesu21** [comment]
This bug exists in Windows as well.

![Screenshot (67)](https://user-images.githubusercontent.com/77072787/110923544-e06fcb80-82d5-11eb-9ce3-fa31751d1de8.png)
![Screenshot (68)](https://user-images.githubusercontent.com/77072787/110923562-e36abc00-82d5-11eb-95a3-9e23edf1a1a8.png)

**Comment by hopesu21** [comment]
Read mode tip message is no longer an issue. Some text will always be covered up but this one message was very prevalent.
