### ISSUE TITLE
Stacker gets confused by preexisting Stacks

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#607]
**Background**
If a user has already created some Stacks, using the automatic Stacker (for example, to create Turns) can create some unexpected results.    
The good news: Stacker does not simply overwrite preexisting Stacks.    
The bad news: Stacker does not simply overwrite preexisting Stacks.    

**To Reproduce**
1. Open SBC008. 
2. Make a few Stacks that included Units from 2 different Speakers (in other words, Stacks that do NOT equal a Turn). For example (in SBC008), create: 
- Stack 1 = lines 4-5 
- Stack 2 = lines 8-9
- Stack 3 = lines 14-15
- etc. (See the screenshot below)
3. From the Main menu, choose Stack > Create Stacks > Turn.
4. Examine the Stacks that result. Notice that:
-  while most Stacks are Turns (all by one Speaker), some Stacks include more than one speaker. 
- These are the pre-existing Stacks that were created in Step 2 above. 
- But even these Stacks are not preserved intact; they are mixed with the results of the automatic Turn marking.
5. An additional, perhaps unrelated, problem is suggested by the first line in the screenshot, which is not assigned to any Turn. Perhaps a Turn consisting of a single Unit at the beginning of a conversation gets ignored.

**Desired behavior**
1. When doing an auto-Stack, make sure to specify the StackType (for example StackType = Turn). The goal is to use the StackType value to ensure separation between the user's handmade Stacks (Plain Stacks) vs. the automatically generated Turn Stacks. Each is valid, but they should not be mixed together.
2. Alternatively, when doing an auto-Stack, check for whether there are pre-existing Stacks. Warn the user: 
"Stacks already exist. Overwrite the with new automatic Stacks?" [  ] Okay    [  ] Cancel

**Screenshots**
The following shows a problematic mix of hand-made Stacks with automatic (Turn) Stacks: 
- Stack 1 = lines 4-5 
- Stack 2 = lines 8-9
- Stack 3 = lines 14-15

![Turn stacker gets confused by previous Stacks 2](https://user-images.githubusercontent.com/22628444/93750290-e8db2980-fc03-11ea-96e2-de4f345de966.PNG)

**Related to**
#602

**Comment by johnwdubois** [comment]
A better message to the user:
"You have created 387 Stacks of the "Act Sequence" type. Do you want to overwrite them with new automatic Stacks?" (Cannot be undone)  [OK]  [Cancel]

**Comment by Georgio-Klironomos** [comment]
> 
> 
> A better message to the user:
> "You have created 387 Stacks of the "Act Sequence" type. Do you want to overwrite them with new automatic Stacks?" (Cannot be undone) [OK] [Cancel]

We can upgrade the message to this as soon as we have Stacktypes implemented into Rezonator. Outside of this upgrade, the message helps users understand how the Stacker operates.
