### ISSUE TITLE
Play Stack

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#613]
**What to do**
The following are all designed to do basically the same thing:
- The user makes a selection (selecting a Stack, Line, or Turn)
- The user presses SpaceBar to play the audio for the current selection.
The most important to start with is Play Stack.

_**Play Stack**_
This lets the user play the audio of the current Stack.
1. The user selects a Stack in the left pane of the Nav window.
2. The user presses SpaceBar. This plays the audio from the beginning of the Stack (`SelectionStart`) until the End of the Stack (`SelectionEnd`), and then stops.
3. If the user presses SpaceBar while the audio is playing, the audio stops. Press it again, and it starts again from the beginning (from `SelectionStart`).
4. To identify the correct times, step through the `UnitStart` and `UnitEnd` times, and calculate: 
- `SelectionStart` = `StackStart` = minimum `UnitStart` value among all Units in the current Stack
- `SelectionEnd` = `StackEnd` = maximum `UnitEnd` value among all Units in the current Stack (This will not necessarily the found in last line, because of speech overlaps)
5. By default, playing the audio in a Stack shouldn't change the timestamp of the playback bar (bottom of the screen).

**Additional development**

_**Play Line (Nav window)**_
This lets the user play the audio of the current Line. It's basically the same as above, but for Lines (which tend to correspond to Units).
1. User selects a Line (or Unit) in the left pane of the Nav window.
2. User presses SpaceBar. This plays the audio from the beginning of the Line (`LineStart`) until the End of the Line (`LineEnd`), and then stops.
3. If the user presses SpaceBar while the audio is playing, the audio stops. Press it again, and it starts again from the beginning (from `LineStart`).
4. If there is only one Unit in the Line, then: 
- `SelectionStart` = `LineStart` = `UnitStart`
- `SelectionEnd` = `LineEnd` = `UnitEnd`
5. If there is more than one Unit in the current Line, then check all the Units to calculate: 
- `SelectionStart` = minimum `UnitStart` value among all Units in the current Line
- `SelectionEnd` = maximum `UnitEnd` value among all Units in the current Line
6. By default, playing the audio in a Stack shouldn't change the timestamp of the playback bar (bottom of the screen).

_**Play Line (Main screen)**_
This lets the user select Line in the Main screen, in order to play its audio. 
1. In the Main screen, the user clicks on a Line number to select the Line.
2. The user presses SpaceBar to play the audio for the current Line (as above). 

_**Play Turn**_
This lets the user play the audio of the current Turn. It's basically the same as the above, but for Turns (as identified by Speaker labels).
1. On the Main screen, the user clicks on a Speaker label to select the Turn.
2. Identify the lines in the current Turn:
- the first line of the Turn (not necessarily the one the user clicked on; go higher if necessary)
- the last line of the Turn (go lower if necessary)
- everything in between
2. `SelectionStart` = minimum `unitStart`  value among all Units in the current Turn 
3. `SelectionEnd` = maximum `unitEnd`  value among all Units in the current Turn
4. The use presses SpaceBar to play the audio for the current Turn.

_**Play chain**_
This lets the user play the audio of the current Chain (Rez chain or Track chain). It's basically the same as the above, but for Chains.
1. In the Nav window, the user clicks on a Chain (Rez or Track) to select it.
2. Test all the Units in the current Chain to calculate: 
- `SelectionStart` = minimum `UnitStart` value among all Units in the current Chain
- `SelectionEnd` = maximum `UnitEnd` value among all Units in the current Chain
3. Pressing SpaceBar plays the audio for the Selection (as usual).

**Comment by Georgio-Klironomos** [comment]
This feature currently works for sequential stacks, and uses the bookmark mechanism within our Audio system. We still need to get it working for broken up stacks in a clean way.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois Play Stack is now functional for broken up stacks, and also updates the bookmarks when the currently focused stack is changes.

**Comment by Georgio-Klironomos** [comment]
Play Stack has been user tested thoroughly. It also now eliminates the Stack's audio bookmarks once the Stack is unfocused, as per requests from multiple users.
