### ISSUE TITLE
"Clear Search" is disruptive

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#616]
**Background**
"Clear Search" is disruptive, making the user lose their place in the discourse.

**What to do**
1. The "Clear Search" should simply remove the colored highlighting of Hits in the Main screen -- nothing more.
2. The Search screen results (Hits) can remain as they were - no need to "clear" this screen.

**Additional context**
When the user returns from the Search screen to the Main screen, they should retain the position in the discourse they were in, when they were in the Search screen. That is:
- The line they were focused on should remain visible. 
- Or, if they they were not focused on any line, the line at the top of the screen they were looking at should remain visible.

**Comment by Georgio-Klironomos** [comment]
@johnwdubois This solution is almost implemented as specified, along with the re-implementation of the highlight Search Row (without the highlight). Last thing we'll check is making sure the new "Search" and "Main" buttons in the new Menu work with this new functionality.

**Comment by Georgio-Klironomos** [comment]
The switch between the Search Screen and the Main Screen is now functional in the Menu Bar

**Comment by Georgio-Klironomos** [comment]
This change to "Clear Search" and how the user's lines are kept in focus has helped the Search screen become more intuitive.
