### ISSUE TITLE
Autosave disrupts Search screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#617]
**Bug**
Autosave disrupts Search screen: The Hit words that should be in the center column lose their place.

**To reproduce the problem**
1. Do a search, and look at the Search screen.
2. Wait for an AutoSave event to take place (or just take my word for it).
3. See how the Hits in Search screen are shifted to the leftmost column; they no longer occupy the middle column of the screen, as they should.

**What to do**
Make sure that the Hits in the Search screen continue to occupy the middle column of the screen, even after an AutoSave event. 

**Screenshot**
This is what should NOT happen after an AutoSave: the Hits no longer occupy the middle column:    

![autosave disrupts Search screen](https://user-images.githubusercontent.com/22628444/94287717-50c0a580-ff5f-11ea-9171-00326005c1a6.PNG)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois I found that our saving and loading was always setting the wordLeftMargin, even in the search screen, so I've made it more careful about when it resets the margin. Now saving no longer disrupts the search screen.
