### ISSUE TITLE
File description labels

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#624]
**Background**
The File description labels that Rezonator uses should be updated, to make them conform better to standard usage for modern software.

**What to do**

1. In the "Import" dialogue ("Import" > "Open data file"), change "Open data file" to "Import file".
2. For the "Import" dialogue, change the filename descriptions as follows:

Current label | New label
---  | ---
"REZ file"  |  "Rezonator (*.rez)"
"TXT file"  |  "Text (*.txt)"
"XML file"  |  "XML (*.xml)"
"CSV file"  |  "CSV table (*.csv)"
"JSON file"  |  "JSON (*.json)"
...  |  "All files (*\.\*)" 
2. Add a new filename option to the the "Import file" options listed above, as follows: "All files (\*.\*)" (Although this may be too permissive, it gives the user a chance to see which files are in the current directory.)
3. For the Export dialogue, change the filename description as follows:
"CSV file" => "CSV table (*.csv)"
4. For the "Save as" function (when implemented), use the filename description as follows: "Rezonator (*.rez)"
5. Wherever a file handling option (e.g. for opening or saving a file) presents "REZ file" as an option, use instead the following description: "Rezonator (*.rez)"

**Comment by gtroiani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rezonator](https://trello.com/c/1xFqHuft/40-rezonator)

**Comment by johnwdubois** [comment]
Looks like this one is mostly done.
