### ISSUE TITLE
User Language vs. Target Language

### ISSUE THREAD

**Issue by Georgio-Klironomos** [johnwdubois/rezonator#636]
**Background**
- Users need to be able to easily select a "User Language" for localization purposes. This determines which language is to be used to display menus, tooltips, messages, and dialogue boxes in Rezonator.
- In addition, they _may_ need to select a "Target Language". This is the language to be displayed in the Main screen. This setting is mostly needed for ensuring that  Rezonator displays the correct Reading Order for Right-To-Left (RTL) languages. (For most languages, this is not so important, because most languages have Left-To-Right [LTR] reading order, which is the Rezonator default.)

**What to do: User language**
1. In the Main menu, the user selects: Settings > Language. This shows two options:
- User language
- Target language
2. If the user selects "User language", a drop-down sub-menu appears, listing all of the currently available Localization languages.
3. The list of languages (`LocalizationLanguageList`) should probably be generated on the fly, by looking at all the languages available in the JSON localization file(s).  
4. When the user clicks on a language from this list, this sets the value of `UserLanguage`.
5. Once the user has selected a language as `UserLanguage`, this should override the setting for the operating system, and be remembered by Rezonator in the .ini file. 
6. If the user has not selected a language from the Settings menu. then the value for `UserLanguage` can be obtained from the settings for their operating system.
7. If the `UserLanguage` is Arabic, Hebrew, Farsi/Persian, or Urdu, set the value of `UserLanguageReadingOrderIsRTL` = TRUE. (See #125 )

**What to do: Target language**
1. Note that `UserLanguage` must be distinguished from `TargetLanguage`, which can be set independently. 
2. If the user selects Settings > Language > Target language, show the user the following message, and ask them to select one otpion:
- "Target language reading order is:
- (x) Left-To-Right (default)"
- ( ) Right-To-Left"
- [OK] [CANCEL]
3. If they select the RTL option, set the value of `TargetLanguageReadingOrderIsRTL` = TRUE, otherwise it is FALSE (default). (See #125 )

**Additional context**
1. _Future development:_ If the user selects Menu > Language > Target language, show them a dialogue box allowing them to type in the ISO code for the Target language. Remember this input as `TargetLanguage`.
2. As a model for the GML code for this function, it may be useful to look at the code for generating the list of available Fields in the Nav window.
3. Related to #125 .

**Comment by gtroiani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rezonator](https://trello.com/c/1xFqHuft/40-rezonator)

**Comment by kittynugget** [comment]
The language option is now available in the settings menu. For further development on the RtL and LtR issue a more precise ticket on handling the issue would be appreciated.

**Comment by johnwdubois** [comment]
The difference between user language and target language needs to be addressed.
1. The user language font should ONLY be used for the Menu, Help, and Tips.    
2. Don't use the user language font in the Main screen or the Nav window.     
3. Let the user specify a different language for the Target language, and set the font for the Main screen and the Nav window to use this font.
