### ISSUE TITLE
Search screen should default to Read mode

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#637]
**Background**
When the user does a search, we should maximize the value of the Nav window. Right now the most informative mode is Read mode, so this should be the default for the Search screen.

**Expected behavior**
1. When the user makes a Search, automatically put the Search screen into Read mode, by default.
2. As soon as a Search is made:
- place the user's focus on the first line in the list of Hits (in the central portion of the Search screen). 
- based on the focused line, the display of the the Nav window (at the top of the Search screen) should show information about the tokens in this line (using the "1-to-many" display in the right have of the Nav window).
3. When the user clicks anywhere on a line in the list of Hits in the Search screen, this line becomes focused, and the Nav window should automatically update with information about the tokens in this line (1-to-many display).
4. If the user presses the down arrow, the selection should move down to the next line in the Search screen, and the Nav window should update correspondingly. Similarly for up arrow.
5. Press and hold the down/up arrow to rapidly change the selection to the next/previous line, which should update the Nav window accordingly.
6. Rezonator should remember the current Mode value independently for (1) the Main screen, and (2) the Search screen . For example, if the user is doing Track mode in the Main screen, and then does a Search, the modes should be as follows:
- Main screen = Track mode
- Search screen = Read mode
- switching between the 2 modes should not modify the user's current settings (remembered independently for each screen)
7. If the user chooses a different mode in the Search screen, then this mode should be remembered for the current session (until the user changes it again).
8. By default (before the user has actively seleted any mode):
- Main screen = Read mode
- Search screen = Read mode
9. Don't show the "Read mode" warning in the Search screen.

**Future development**
In the long term, we can try to make sure that Track mode and Rez mode are as informative in the Nav window as the Read mode is.

**What is the estimated development time?**
3 hours

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] The highlight feature will be added to the other scrolling functions
- [x] Nav window will update to the location of the currently focused line

**Comment by Georgio-Klironomos** [comment]
The highlight row aspect of this ticket has been implemented, and will be user tested with this week's release of Rezonator.

**Comment by Georgio-Klironomos** [comment]
The highlight feature will be added to the other scrolling functions, and the Nav window will update to the location of the currently focused line.
