### ISSUE TITLE
Block Types (for Import)

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#638]
**Background**
When importing interlinear glossed text (IGT), it is important to recognize that there may be more then one Block Type (what was formerly known as Line Cluster).  It's important to know how many different Block Types there are; to show them to the user; and to remember them as part of the import schema.

**Screenshot**
The following images show pane designs for the top half of the Import screen. The section labeled Summary should occupy the upper left, while the section labeled Blocks should appear to the right of it. Note the unequal distribution of screen real estate: about 25% for the Summary, and 75% for the Blocks. The Exceptions section can appear immediately below the Blocks (if it's still useful).

![Block types for Import screen](https://user-images.githubusercontent.com/22628444/95017435-011a6200-0662-11eb-9fd9-e13916c931de.PNG)

**Expected behavior**
1. The first task is to figure out:
- how many different types of `BlockType` there are in this file
- what's in each `BlockType`
- how many instances of each `BlockType` there are in this file
2. Obviously, getting the `BlockType` right is critical for getting the entire Import process right.
3. When the user imports an IGT file, they should be shown a summary in the Import screen, listing each of the `BlockTypes` that appear in the file. The design of this display is shown in the above screenshot.
4. The upper right section of the Import screen should display a list of the `BlockTypes`: Block Type 1, 2, 3... (as seen above).
5. Mark the `DefaultBlockType`. This is the `BlockType` that appears first in the imported file (excluding the Title, which may be exceptional). Normally this is also the most frequent `BlockType` in the file.
6. List the `BlockType` in the following sequence:
- `DefaultBlockType` is first
- Then list remaining `BlockType` in descending order of frequency 
7. For each `BlockType`, display:
- Block count (number of instances of each `BlockType`)
- Lines per Block
- Marker list (for each `BlockType`)
- One example (normally chosen from the 5th instance, not the first, to get a more typical example)
8. Rezonator should remember the default `BlockType` etc. etc. as part of the (named) import Schema.
9. Numbers (= Count) should be right-justified for ease of reading.
10. Most gridlines in the above design are superfluous; omit them for a clean design.
11. A 5-line Block instance that contains no Markers "inherits" its Markers from the appropriate `DefaultBlockType` (i.e. the 5-line `BlockType` that DOES contain Markers). Whether the Markers are explicit or implicit (inherited), it counts as the same `BlockType`. Absence of markers does not imply a different `BlockType`.

**Blocks vs. Units**
There should be a clear differentiation between Blocks and Units, and UnitSequence will not always be equivalent to BlockSequence. Why?
1. Songs often have sections (verses) separated by `BlankLine` (= one or more "empty" lines, i.e. lines containing no _visible_ characters). These should be recognized as Blocks during the import process, but they will NOT become Units. Instead, these Blocks will become Stacks, and each Line in the imported file will become a Unit. (Once the Stacks have been created, the `BlankLine` between pairs of Stacks should be eliminated,)
2. IGT files may have not only a title marked by 3-hyphens before and after, but also section Headings marked in the same way. These Headings may appear anywhere in the middle of the discourse, and they carry meaning that applies to all the lines that follow them, up until the next Heading. So they need to be recognized as Blocks during the import process, and assigned a BlockSequence value that captures their correct position in the middle of the file. But they are not Units as such, and should not receive a UnitId or UnitSequence value. In most cases, they should define the start and end of a Stack, and their text string should be taken as the Title for that Stack.
3. The 3-hyphen convention for Title and Heading means that there is one exception to the `BlankLine` rule for delimiting Blocks. Even if there is no  `BlankLine` after the Title, this should be considered a separate Block. Normally the Title would receive the `BlockSequence` value of 1.

**Additional context**
The `DefaultBlockType` is important, because this defines the Schema that will be applied to Blocks that do not contain explicit Markers. It should be easy to identify the `DefaultBlockType` according to the conventions of Scription as described above. But if it is not, it may be useful to ask the user to confirm which `BlockType` is the default (by clicking on a radio button next to the relevant Block Type display).    

As Hieber makes clear in his post describing the Scription conventions, even a file that has no markers at all can be considered a legal Scription file, and treated as IGT. There are standard conventions for the correct Schema for such files: one convention for 2-line Blocks, a different convention for 3-line Blocks, etc. It's all spelled out in his article.

Related to #446 #458 and #264 .

**What is the estimated development time?**
An estimate in hours. Ex. 2.5 hours, 6 hours.

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] Construct Block Type Grid - 3hr
- [x] Interpret and understand files- 4 hr
- [x] Fill up grid based on Scription Files- 4 hr

**Comment by johnwdubois** [comment]
See the new section added above on "Block vs. Unit".

**Comment by Georgio-Klironomos** [comment]
The Block Grid is implemented and in use with the Scription Import.

**Comment by johnwdubois** [comment]
This is not fully built. For example: The Summary display with Block Count, etc.
The people who programmed it (T & B) should first discuss it with the requester (JWD).    
Only _after approval_, they (T & B) should be the ones to close it.
