### ISSUE TITLE
Import problems - Scription 1

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#640]
**Background**
The IGT import of Chitimacha goes seriously wrong, in may ways. The attempt to map one word of English to one word of Chitimacha is simply magical thinking. There are no 2 languages in the world that match 1-to-1 like this - ever! Rezonator should never try to implement such a 1-to-1 mapping.    

The first indication that something is seriously wrong is that the token counts are not even close: 241 "tokens" for English, and only 166 tokens for Chitimacha. The second is that starting in the middle of Unit 16, there are nothing but "undefined" tokens in Chitimacha.

**Screenshot**
1. In Unit 16, please notice 2 things:
- Supposedly there is a 1-to-1 mapping of Chitimacha words to English words. While such a thing might happen by chance here and there in a conversation, it will never happen throughout a whole discourse.
-  When Rezonator runs out of real Chitimacha words to map, it starts to invent "undefined" words. Not good.

![Import catastrophe - IGT Chitimacha 3](https://user-images.githubusercontent.com/22628444/95021468-d89e6200-0679-11eb-9c3a-9b1a6c242588.PNG)

This screenshot shows _some_ of the substantive changes that are needed to correct the situation (along with other changes that are simply modest  UI improvements):

![Corrections to import screen](https://user-images.githubusercontent.com/22628444/95021454-cde3cd00-0679-11eb-8cf9-400e36e7122a.PNG)

**Describe what to do for the development of this feature**
1. A linguist working on a little-known language like Chitimacha will NEVER start with English as the default token. The linguist is interested in the target language (Chitimacha), and that's the language that should have the default token.
2. A free translation (into English) is ALWAYS a Unit-level entity. If you see only one marker type that contains English, as in the present Chitimacha text, you can be almost sure that it's a free translation, which is NEVER a token-level item.
3. It's important to understand that the criteria are very rigorous for designating 2 or more lines as containing Tokens. The match between two Token Count values (or better yet, the `TokenRatio`) should be exact (1.0 or 100%). True, it might vary slightly, say between 0.98 and 1.02 if there are some mistakes in the data. But there shouldn't be more than a very slight difference from 1. The numbers here 166/241, for a `TokenRatio` of 0.69, which isn't even close. The conclusion: No way could both of these lines represent attributes of the same Tokens - they just don't match up.
3. In this file, the \trs marker is the "Token (default)". There are NO other token markers in this discourse. the \trs line will have to be sliced up (tokenized) to find the Tokens.
4. The \tln line is Unit level (only).
5. In some cases, we may need to recognize that is is useful to treat a Token-level marker (like \trs) as ALSO a Unit-level marker. In effect, \trs acts like a Unit/Token marker (i.e. both a Unit and Token). 
6. I believe we used to calculate additional metrics, like the Token Ratio. But these metrics have been eliminated from the Import screen. It's time to bring back the correct metrics, and use them.
7. Some takeaways:
- Rezonator must always find at least 1 Token-level marker, but there is no guarantee that there will be more than 1.
- Assuming the default Token marker has been identified (either algorithmically or by the user input), this should define the number of rows in the Token grid.
- The criterion for identifying a 2nd (or 3rd, 4th, etc.) Token-level marker must be applied very strictly, with something approaching a `TokenRatio` of 1.

**Additional context**
Related to #264 

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [x] Design new foolproof scription import - 4 hr
- [x] Discuss new design - 2 hr
- [x] Implement new design in GML- 3 hr
- [x] Test new Design with various unique Scription Files - 3 hr
- [x] Test all other supported imports - 3 hr

**Comment by Georgio-Klironomos** [comment]
The next step for this import is preventing import data of different token count from both being listed as Token level

**Comment by Georgio-Klironomos** [comment]
The solutions to these issues have been solved for IGT and Scription imports, thanks to Brady and Terry. Next step will be user testing with theze solutions

**Comment by johnwdubois** [comment]
Not solved yet. There's lots of work still to be done.
