### ISSUE TITLE
Right-justify should reverse Out-Of-Bounds zone, placing it at the right margin of Main screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#643]
**Background**
1. Selecting "Right-justify" should reverse the Out-Of-Bounds zone, placing it at the right margin of the Main screen (instead of the left margin).
2. I don't think we'll solve the alignment of Rez links in right-justified text until the Out-of-Bounds region is reversed, relative to the default (left-justified).

**What to do** 
1. A user may do one of the following: 
- User changes Justify from Right-Justify (Start-Justify) to Left-Justify (End-Justify), or 
- User imports data from a Target language whose TextDirection=RTL. (changing it from LTR (default) to RTL (Arabic, Hebrew...).
2. If one of these conditions is met, the location of the Out-Of-Bounds region should change from the left margin (default) to the right margin of the Main screen.
3. If both conditions are met, they in effect cancel each other out, and the Out-Of-Bounds region remains on the left.
4. By definition, no words should appear in the Out-Of-Bounds region. In particular, even if there is a Race-to-Infinity, it should never pull/push a word into the Out-Of-Bounds region.
5. The concept of "word gravity" (#235) applies: 
- in StartJustify, words tend to be pulled by "gravity" to the left (assuming an LTR language)
- in EndJustify, words tend to be pulled by "gravity" to the right (assuming an LTR language)

**Screenshot**
Pay attention to the location of the grey region in each of the following images. The gray region represents the location of the Out-of-Bounds region in Rezonator.    
     
![End Justify flips Out-Of-Bounds grey zone](https://user-images.githubusercontent.com/22628444/95734743-88805a80-0c8c-11eb-9ce2-c7f30dd84846.PNG)

**Further development**
Ideally, there will be 2 columns reserved on the right margin of the Main screen for displaying the line numbers and speaker labels (see screenshot above).

**Context**
For more images and a detailed explanation, see the discussion of RTL order in #125 and word gravity in #235 .

**Comment by johnwdubois** [comment]
I don't think we'll solve alignment of Rez links in right-justified text until the Out-of-Bounds region is reversed, relative to the default.

**Comment by terrydubois** [comment]
rtl grid view still needs to be done

**Comment by johnwdubois** [comment]
There may still be some pesky bugs with out-of-bounds, it seems.
