### ISSUE TITLE
Map imported data fields to Rezonator

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#65]
**Is your feature request related to a problem?**
We would like to people to be able to use Rezonator with a wide array of data sources, genres, corpora, and languages. For this we need to provide more flexibility in how Rezonator processes a wide range of existing data formats. 

**Describe the solution you'd like**
1. Allow users to automatically import an existing file format (CSV, txt, JSON, XML, etc.) into Rezonator. 
2. If the fields (column headers) do not exactly match the expected fields for Rezonator grids, allow the user to specify a mapping of unmatched fields to the appropriate field in a Rezonator grid. 
3. Allow users to save their mapping, and to assign a name to it, for future reuse.
4. Allow for graceful degradation: If there is no appropriate destination in the relevant Rezonator grid for an imported field, go ahead and import whatever matches, and tell the user what's missing.

**Test file**
1. Here is a useful test file: [**SBC001 excerpt (CSV)**](https://github.com/johnwdubois/rezonator/blob/master/Files/Grammar/word_info_v35_SBC001_01-97_depRel_JWD_REZ-TEST.csv). (This is a spreadsheet representing a brief excerpt of about 100 words from the start of SBC001.)    
2. The goal is to import this file into Rezonator, mapping its fields (columns) into the fields of the "Word" grid.  
3. One can even construct the Unit grid, based on this Word grid, as follows: 
- loop through the words, paying attention to the `uID` field 
- create a list of all the Words that share the same `uID`

**Future development**
1. Some sophisticated users may want to use [JSON schemas](https://github.com/johnwdubois/rezonator/wiki/4.-Resources#json) to define guidelines to be followed, for preparing their data for import into Rezonator.    
2. One alternative is to provide a converter that pre-processes data outside Rezonator, for later import into Rezonator. The idea would be to convert files to a format that Rezonator can interpret directly (e.g. JSON, CSV, XML, etc.).   
3. In the long run, it will be useful to create schemas for importing data from populuar formats, such as:   
- Elan
- [Scription](https://github.com/digitallinguistics/scription2dlx)    
(See the [Scription demo](https://medium.com/digital-linguistics/converter-scription-dlx-610fb947dc15)
- Exmaralda
- DLx
- etc.   

**Additional context**
See also #96.

**Comment by Georgio-Klironomos** [comment]
This may be an overlap with the Import Screen issue, If there's anything within this issue that is still relevant, let us know. Otherwise, we'll close the issue.

**Comment by johnwdubois** [comment]
You're right, this one is pretty well covered by other tickets we've completed. Ready to close.
