### ISSUE TITLE
Scroll bar and trackpad scrolling issue

### ISSUE THREAD

**Issue by laurenmin** [johnwdubois/rezonator#651]
**Issue**
Issue with mousewheel and trackpad scrolling after using Mac version of ctrl+ up/down 
arrows (command + up/down). Scroll bar keeps shifting to the top and arrow key unresponsive in the main screen. 

**To Reproduce**
1. Scroll through the main screen
2. Press command+up to scroll to the top. 
3. Scroll down. The scroll bar keeps shifting to the top and trackpad scrolling is unresponsive. Same goes for command+down (scroll bar keeps shifting to the bottom)

**Describe what to do for the desired behavior**
Scroll bar and trackpad scrolling should work normally after using command + up/down.

**Desktop:**
 - OS: MacOS
 - Version: 0.9.0.3

**Comment by Georgio-Klironomos** [comment]
@laurenmin This issue has been fixes, and the fix will appear on version 0.9.1.0
