### ISSUE TITLE
Menu bar not automatically shown when in full screen

### ISSUE THREAD

**Issue by angelina-yuan** [johnwdubois/rezonator#662]
**What is the background of this bug report?**
On a Mac, one can choose to automatically hide and show the menu bar – when this is selected, the user needs to move the mouse to the top of the screen and the menu bar would automatically drop down. However, when in full screen (entered by putting side-to-side with another app), Rezonator does not respond to this action (thus stuck in full screen).

**To Reproduce**
1. System Preferences > General > select "Automatically hide and show the menu bar" (pic 1)
2. Open any other app and enter fullscreen
3. Enter Mission Control by either pressing F3 or swipe up with three fingers on trackpad
4. Drag Rezonator's window to tile it side-to-side with the full-screen app (shown at the top of the screen) (pic 2)
5. Select Rezonator's window and move the cursor to the top of the screen to see the error; menu bar automatically drop down when the other app is selected (pic 3) but not for Rezonator (pic 4)

**Describe what to do for the desired behavior**
When the cursor touches the top of the screen, the menu bar would automatically drop down

**Screenshots**
pic 1:
<img width="668" alt="WX20201020-143430@2x" src="https://user-images.githubusercontent.com/72842685/96549005-73857600-12e1-11eb-96a8-70166c931496.png">
pic 2:
<img width="1440" alt="WechatIMG488" src="https://user-images.githubusercontent.com/72842685/96549090-94e66200-12e1-11eb-8e63-2514193eccdf.png">
pic 3:
<img width="1440" alt="WX20201020-140915@2x" src="https://user-images.githubusercontent.com/72842685/96549246-d119c280-12e1-11eb-85da-148b9ed21a94.png">
pic 4:
<img width="1440" alt="WX20201020-140907@2x" src="https://user-images.githubusercontent.com/72842685/96549305-e55dbf80-12e1-11eb-80dd-177793df5075.png">

**Desktop:**
 - OS: macOS 10.15.7
 - Rezonator Version: 0.9.0.3

**Comment by Georgio-Klironomos** [comment]
@angelina-yuan Thanks for pointing this out! Turns out this was just a checkbox we had unchecked within our IDE, so the next version of Rezonator will have this fixed!
