### ISSUE TITLE
Contents Window does not jump to the chosen Speaker Label in the Main Window

### ISSUE THREAD

**Issue by laurenmin** [johnwdubois/rezonator#667]
**What is the background of this bug report?**
The Contents Window correctly outlines the chosen line of dialogue in the Main Window, but the user has to scroll in the Contents Window to find the outlined dialogue. 

**To Reproduce**
1. Go to the Main Window
2.  Click on a Speaker Label that is past line 7

**Describe what to do for the desired behavior**
When I click on a Speaker Label in the main screen, I would expect the 
Contents Window to jump to that dialogue and show that dialogue in the Contents Window. Instead, I still have to scroll in the Contents Window to find the outlined dialogue. 

**Screenshots**
Below, I clicked on line 2's Speaker Label and the Contents Window shows the dialogue that was clicked.
<img width="494" alt="Screen Shot 2020-10-21 at 1 05 05 PM" src="https://user-images.githubusercontent.com/72825616/96776634-23201e00-139e-11eb-98c2-9ba5cccd8ffd.png">
Below, I clicked on line 7's Speaker Label but the Contents Window does not show the dialogue that's clicked. It would be nice if the Contents Window jumps to the line, like above. 
<img width="490" alt="Screen Shot 2020-10-21 at 1 08 07 PM" src="https://user-images.githubusercontent.com/72825616/96776884-7befb680-139e-11eb-9628-bc16cfeb4c9a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 0.9.0.3

**Comment by Georgio-Klironomos** [comment]
@laurenmin The fix to this issue is included in versions 0.9.0.5+, thanks for the ticket
