### ISSUE TITLE
Merging chains on MacOS not working

### ISSUE THREAD

**Issue by laurenmin** [johnwdubois/rezonator#669]
**What is the background of this bug report?**
Merging chains (CTRL+ Left Click) not working on Mac (neither Command+Left Click nor Control+Left Click)

**To Reproduce**
1. Focus on a chain
2. Control+Left Click on an unfocused chain you want combined
3. Command+Left Click on an unfocused chain 

**Describe what to do for the desired behavior**
Command+Left Click on a word in the unfocused chain should merge the two chains together, since Command is the Mac equivalent of Control. 

**Desktop (please complete the following information):**
 - OS: MacOS, High Sierra
 - Version 0.9.0.3

**Comment by hopesu21** [comment]
Could not reproduce in Mac.
