### ISSUE TITLE
Unable to Import files from an existing Rezonator session

### ISSUE THREAD

**Issue by laurenmin** [johnwdubois/rezonator#670]
**What is the background of this bug report?**
Can not open a new file from current Rezonator session. Pressing Cancel subsequently returns the user to the opening screen of Rezonator.

**To Reproduce**
1. Go to Menu Bar and click File
2. Click Import
3. Import file window pops up showing all SBC.rez files
4. Click on a file **no response
5. Click Cancel

**Describe what to do for the desired behavior**
Rezonator should be able to Import other SBC.rez files during a Rezonator session. If the user chooses to cancel, they should be taken to the current session and not back to the Rezonator opening screen. 

**Screenshots**
Can't click on the files
<img width="1280" alt="Screen Shot 2020-10-21 at 5 28 21 PM" src="https://user-images.githubusercontent.com/72825616/96804068-ddc21780-13c2-11eb-835d-570c9876c2dc.png">

**Desktop (please complete the following information):**
 - OS: MacOS, High Sierra
 - Version 0.9.0.3

**Comment by hopesu21** [comment]
Unable to reproduce.
