### ISSUE TITLE
CTRL-p should keep the user's place

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#674]
**What is the background of this bug report?**
User's should be able to quickly use "p" followed by "CTRl-p" to zero in on a particular Rez chain, without losing their place in the Main screen.

**To Reproduce**
1. In the Main screen, make some Rez chains around line 100 or so.
2. Press "p" to select the current Rez chain.
3. Press "CTRL-p" to filter on the current chain. Rezonator should show just the current Rez chain.
4. Press "CTRL-p" again to _unfilter_. It should stop zeroing in on the current chain. 
5. Notice that Rezonator goes to the wrong place in the file, thus losing the user's place in the conversation.

**Describe what to do for the desired behavior**
1. When the user presses "p", make sure this adds the current chain to pick list.
2. When the user presses "CTRL-p", make sure this focuses on the correct chain. The best option for this: zero in on the current chain (ignoring other chains that may have been focused).
3. When the user presses "CTRL-p" a second time, undo the filter on the current chain (that is, show the whole conversation). But make sure not to lose the user's place. If possible, keep the same view of the data from before the CTRL-p.

using the Filter option, make sure to maintain the user's place in the discourse.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**What is the estimated development time?**
An estimate in hours. Ex. 2.5 hours, 6 hours.

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [ ] Example Task - 1 hr
- [ ] Example Task- 2 hr
- [ ] Example Task- 3 hr
- [ ] Example Task - 4 hr

**Comment by Georgio-Klironomos** [comment]
@johnwdubois All instances of the user moving from the filter screen to the main screen now sets the user back in their original place, as intended. User testing will show if this works on other machines.
