### ISSUE TITLE
GridView grid list should be visible permanently

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#681]
**What to do**
1. The GridView grid list should be visible at all times. 
- The list that now appears as a dropdown should be permanently visible on the GridView screen. 
- In other words, the list does not disappear when you make a selection from it
- Make sure the list doesn't cover up (overlap with) the grid.
2. When the user clicks on an item from the list:
- highlight the selection in blue
- show the corresponding grid
- leave the other options visible (other grids) 
3. The code for moving from one grid to the next (via the [TAB] key) may be reused for the new way of selecting a grid (if this is useful).
4. Get rid of the Tabs (labeled with the grid name), which are now superfluous.

**Further development**
1. Sort the list of grids alphabetically (ascending by default, or descending as an option).
2. Allow the user to use the arrow keys to scroll down (or up) the list of grids. As you go down/up, the focus updates, and the corresponding grid is displayed.
3. If the list of grids becomes too long to fit on the screen, provide a scroll bar. The scroll bar should not display unless the list is too long.

**Screenshot**
As in the following screenshot, the list of grids at the left margin should remain visible always:

![GridView grid list should be always visible](https://user-images.githubusercontent.com/22628444/97811248-edbede80-1c81-11eb-8254-63f246b0eee9.PNG)

**Related to**
This in effect replaces #625.

**Comment by hopesu21** [comment]
@gtroiani This is what the gridview screen looks like for version 0.9.1.9 on Windows. 
![Screenshot (36)](https://user-images.githubusercontent.com/77072787/107018516-6340bc00-6755-11eb-9921-343cc39c1767.png)
