### ISSUE TITLE
Race to infinity

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#7]
**Describe the bug**
The "Race to Infinity" happens when a user make a Rez link, prompting Rezonator to attempt to align two words. Under certain circumstances, this causes the words to race off the screen to the right, with no end in sight.  This happens when the two links cross, making an X. 

NOTE: There are at least 4 strategies for resolving this problem. Strategy 1 can be implemented more easily than strategy 2, 3, or 4, and so should be implemented first. (See "Expected behavior" below.)

**To Reproduce**
1. Make two Rez chains, such that the line of one Rez link crosses the line of another Rez link, forming an X. 
(Look for the X before you click on the second word, because once it is clicked, it will disappear fast.) 
2. See error: Each word forces the repositioning of the other, in an endless loop. The words race off screen to the right, with no limit.
3. You can undo this effect by unchecking the "align" box. This is because no alignment is done in this mode. But we want to be able to align words to show resonance, so this is not satistfactory. 
4. Also, you can undo this effect by switching to the word shape from "block" to to "text". Again, this is because by default, no alignment is done in this mode. Again, unsatisfactory (but it is informative about the problem).
5. A race to infinity is also created when the user makes a Rez link between 2 words in the same line.

**Expected behavior**
We would like words to not disappear from the screen. There is a dilemma about how to do this -- it's not entirely clear what the expected "best behavior" should be. There is more than one strategy. We could call the most obvious strategies (in order of ease of implementation): (1) monitor, (2) cap and undo, (3) swap, and (4) prevent.

To describe the problem, we could say that word 1A links to 2B, and 1B links to 2A. (Numbers 1 and 2 represent 1st and 2nd line (or row), while letters A and B represent words in left-to-right column order.)

By contrast, an "easy" link is one that  doesn't cross: word 1A links to 2A, and 1B links to 2B, or 2C, or 2D.....  No problem arises.

To solve the problem, one strategy at a time:
1.  Monitor
For a start, put a monitor in place to identify when the race to infinity is happening. 
Create a list of "runners": the top 10 words, whose position has changed most often in the last 40 updates.
Or count the moves that happen without any additional user input (i.e. one user click produces a series of successive moves).
Or count when a word reaches display column 100.
Notice when the same words stay on the list for too many moves.

2. Cap and undo
Monitor the race to infinity; and after it happens, undo the effects. You can do this by removing the problematic link. 
(But what if that link is one we really want to make, because it's the right thing to do?)

3. Swap
Offer the user a chance to swap the location of two words in one of the lines. (For example, the 2 words "Do you" are swapped to produce "you {Do}". ) Mark one of the words as having moved, by writing TRUE in the "swap" column (or variable). Display the "swapped" status of the word to the user, e.g. by special font, or enclosing it in curly brackets.

4. Prevent 
Prevent the race to infinity from happening in the first place. 
This could be done by creating a "ghost" when the conditions for a race to infinity are identified (i.e. the race is about to start). The ghost word is aligned instead of the actual word. It's not so clear how to do this, for the more complex cases (multiple X's cascading across multiple lines).

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by terrydubois** [comment]
Use stretch flag in DynaWordGrid to identify "problem words" ... these can be visually represented by a red background bar in the Nav Window.
