### ISSUE TITLE
Provide language option on opening screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#717]
**Background**
Under some circumstances, the opening screen of Rezonator displays options in a language that the user doesn't speak. They may be confused by this. At present, Rezonator does not provide any option that would let the user  recover from this on the opening screen.

**To Reproduce**
1. Use a computer that has a language other than English specified for the operating system.
2. Start Rezonator.
3. Notice that the language of the opening screen is not English. It is whatever the default language for the operating system is. 
4. If the language is one that the user knows, everything is fine. If not, they may be confused, and need a way to recover.

**Screenshots**
This shows the opening screen on a computer whose default language is set to Hebrew (in the operating system):     
 
![Bug - Hebrew backwards](https://user-images.githubusercontent.com/22628444/101650043-30739380-3a44-11eb-9244-1911b317f4fe.PNG)

**What to do**
1. Provide a button that says "English" (in the lower right corner of the screen). 
- When the user hovers over the button, show the tip: "Set default language to English"
- Pressing this button should set the default language to English, overriding the operating system language.
2. In addition: On the opening screen, show a drop-down list that displays the current language (whether from settings or from the operating system).
- let the user select a language from the list of available languages.

**Comment by gtroiani** [comment]
The button is present but it seems to be working in the opposite way than intended in v. 0.9.1.7 (the one available on the website) for Windows: when I hover on the button and click to select the menu, I have to maintain the mouse button pressed to leave the menu visible. As soon as I release the left button on my mouse, the menu closes without allowing me to select the language. If I scroll up while pressing, there are no problems.

Could it be that there is an inverted Press/Release Key event in the code regulating that menu?
<img width="570" alt="loc button" src="https://user-images.githubusercontent.com/26060089/104788305-dc488700-5746-11eb-846a-26755dfc8f98.PNG">

**Comment by hopesu21** [comment]
@gtroiani On windows in Version 0.9.1.9 this issue appears to have been resolved. The default language for the computer is Mandarin Chinese. 
![Uploading 屏幕截图(40).png…]()

**Comment by gtroiani** [comment]
Thanks Hope!
