### ISSUE TITLE
Ugly font on Import screen

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#718]
**Bug**
The Import screen shows an ugly font, when the operating system language is not a language supported by Rezonator.

**What to do**
Make sure there is a fall-back or default font that will be used when the font required by the operating system is not available. This should be a good-looking font, presumably supporting English as the default language (such as Noto Sans).

**Screenshot**
The following screenshot was displayed on a computer whose default language is Hebrew (at a time when Hebrew was not an option supported by Rezonator). Noitce the ugly font.     

![Import screen - ugly font](https://user-images.githubusercontent.com/22628444/101652483-f657c100-3a46-11eb-83cf-d53f771e7a4f.PNG)

**Comment by hopesu21** [comment]
@gtroiani This issue appears to have been resolved on Windows. The font is no longer ugly but I did notice that example display for interlinear glossed text looks much uglier when minimalized. It looks a lot nicer when in full screen. 
![Screenshot (29)](https://user-images.githubusercontent.com/77072787/106962731-6c4d7100-66f4-11eb-9984-d8a88318e4bc.png)
![Screenshot (30)](https://user-images.githubusercontent.com/77072787/106962732-6d7e9e00-66f4-11eb-8d32-6c0d9a3d8614.png)

**Comment by danielagomez723** [comment]
@gtroiani This issue appears to have been resolved on Mac as well. Referencing what Hope pointed out, it seems as if the interlinear glossed text doesn't appear too different when in full screen compared to minimized on a Mac. 
<img width="1123" alt="Capture d’écran 2021-02-08 à 1 16 44 PM" src="https://user-images.githubusercontent.com/78384226/107282502-e68d3680-6a0f-11eb-8da5-a632a829e82d.png">
<img width="1440" alt="Capture d’écran 2021-02-08 à 1 15 45 PM" src="https://user-images.githubusercontent.com/78384226/107282514-eab95400-6a0f-11eb-8c26-db7e6d9263e1.png">

**Comment by gtroiani** [comment]
Thanks both for the input! @kittynugget unless this is something that you want to work on, I will close the issue
