### ISSUE TITLE
JAPANESE and CHINESE characters not showing up

### ISSUE THREAD

**Issue by kstanaka** [johnwdubois/rezonator#724]
**What is the background of this bug report?**
None of the JAPANESE and CHINESE characters show up for the Rezonator 0.9.1.3 version on a Mac. Only the font changes. (the font differs from the English version and becomes bold) 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advanced'
3. Select 'Developer'
4. Once you see a change, go back to 'Settings'
5. Click on 'Languages'
6. Select on either 'Japanese' or 'Chinese' to see the problem

**Describe what to do for the desired behavior**
All of the characters should show up. 

**Screenshots**
<img width="1280" alt="Screen Shot 2020-12-14 at 7 39 01 PM" src="https://user-images.githubusercontent.com/72840331/102168360-fa1f8500-3e44-11eb-88ad-4c630b9f7b8e.png">

<img width="500" alt="Screen Shot 2020-12-14 at 7 39 17 PM" src="https://user-images.githubusercontent.com/72840331/102168400-09063780-3e45-11eb-9df4-5ca539aa74ac.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur version 11.0.1
 - Resonator Version: 0.9.1.3

**Comment by hopesu21** [comment]
@gtroiani Hi Giorgia, unfortunately I do not have access to a Mac so I will just skip this for now.
