### ISSUE TITLE
Clique Tab in Nav window

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#73]
**Is your feature request related to a problem?**
Cliques are very important, and the user needs to be able to navigate easily between them; to see what is in a given Clique; and so on. Cliques are in effect a kind of Stack that is created automatically by Rezonator (based on the user's actions in making Rez chains). They should be displayed like Stacks. 

**Describe the solution you'd like**
1. Implement a Clique tab in the Nav window, modeled on the Stack tab.
2. The Clique tab should appear to the right of the Stack tab, and be labeled "Clique".
3. The 3 columns to the right should display exactly the same information as is displayed for a Stack.
- one row for each Unit in the unitID list for this Clique (as listed in the Clique table)
- first column is "uID"
- second column is "speaker"
- third column is "utterance"
4. For ease of implementation and code maintenance, use the same script that is used to display Stack information in the Nav window. 

**Additional context**
The Clique grid may be a challenge to create and maintain, because Cliques are assembled automatically by Rezonator. But once the Clique grid is populated, the Cliques in it are basically just Stacks . So for displaying a Clique, it's best to do as little as possible, just staying close to the code for displaying Stacks.

See also #11

**Comment by terrydubois** [comment]
Have CliqueDisplayGrid notice when CliqueGrid has row removed (from merge).

**Comment by terrydubois** [comment]
Add filter ability to Clique Tab.
