### ISSUE TITLE
Switching to Read mode loses the user's place

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#731]
**Background**
Switching to Read mode jumps to the beginning of the file, which loses the user's place

**To Reproduce**
1. In the Main screen, go to the end of the file.
2. Select Track or Rez mode.
3. Double click on a line number to make the Nav window match the line number location of the Main screen.
4. Switch to Read mode.
5. See that the Nav window jumps to the start of the file (losing the user's place.

**Describe what to do for the desired behavior**
Switching to Read mode should respect the user's place in the file, not jump to the beginning.

**Screenshots**
![Switching to read mode loses the users place](https://user-images.githubusercontent.com/22628444/103139864-7b9ad100-46e9-11eb-8cd2-d7c93fd418b2.PNG)

**Comment by hopesu21** [comment]
No longer an issue in 0.9.2.6
