### ISSUE TITLE
Quit the current chain when any function button is pressed

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#74]
**Is your feature request related to a problem?**
When the user tries to initiate a new action (via a button), or tries to start a new chain, it can be confusing to have the old chain continue. It should be easier to stop adding words to a chain, even when the user hasn't hit "Escape".

**Describe the solution you'd like**
1. Whenever the user clicks on a function button in the tool pane, treat this as Quitting the current chain. (This is the same as hitting "Escape", that is, stop adding words to the current chain.)
2. Depending on which button the user has clicked on, start a new chain (Rez chain, Track chain, or Stack).

**Describe alternatives you've considered**
Another way to make it easier to quit the current chain and start a new one is to implement the following keystroke shortcuts:
- "r" (start new Rez chain)
- "t" (start new Track chain)
- "k" (start new Stack)
Each of these should quit the old chain, before starting a new one. 

This is compatible with the above treatment of function buttons. (That is, both the button and the keystroke methods can be implemented. Both trigger the same action: quit the old chain, and start a new one.)

**Comment by terrydubois** [comment]
Whenever mouseover Nav Window, deactivate current chain.
