### ISSUE TITLE
Search screen switches from Read to Track mode when any word is selected

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#765]
**NOTE: This bug ticket is superseded by #843 , so please ignore it. Instead, Read mode should be avoided as much as possible, replaced by Track mode.**

**Bug**
1. In the Search screen, Rezonator switches from Read mode to Track mode, whenever any word is selected. It shouldn't.  
2. It also switches from Rez to Track under the same conditions. 
3. There is no way for the user to use the arrow keys to move through the data in Read mode.
4. There is no way for the user to click on a word to simply update the Nav window (in Read mode).
5. All of these need to be fixed.

**To Reproduce**
1. Open a Rez file, and do a search for the word "the". See the hits for "the". Notice that **Read** mode is automatically selected. (So far, so good.)
2. Use the scrollbar to scroll down a few pages through the hits on the screen. Everything seems to work okay.
3. Now click on a word (to update the Nav window to reflect where you are). 
4. See error:  **Track** mode is automatically selected.

**What to do for the desired behavior**
When the user clicks on a word in the Search screen:

1. Don't switch automatically from Read mode to Track mode.
2. Don't switch automatically from Rez mode to Track mode.
3. Don't automatically add a word to a Track chain when clicked.
4. Just let the user easily navigate in the Search screen, continually updating the Nav window to reflect where the user is (using Read mode).
5. Make Track chains only when the user actively selects the Track tool.
6. Make Rez chains only when the user actively selects the Rez tool.

**Screenshots**
![Search screen switches from Read to Track mode when any word is selected](https://user-images.githubusercontent.com/22628444/106418903-faf59000-645f-11eb-95fc-5103a7f5aac2.PNG)

**Comment by hopesu21** [comment]
Unable to search text for Chinese characters, searching for an English character changes the whole screen

![Screenshot (91)](https://user-images.githubusercontent.com/77072787/110934504-f0da7300-82e2-11eb-8d31-929a3f411a5f.png)

**Comment by hopesu21** [comment]
Still an issue as of version 0.9.2.6

**Comment by johnwdubois** [comment]
**NOTE: This bug ticket is superseded by #843 , so please ignore it. Instead, Read mode should be avoided as much as possible, replaced by Track mode.**
Closed.
