### ISSUE TITLE
When user language is Chinese, menu and help info disappears

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#768]
**Bug**
When the user language is set to Chinese, all menu options disappear. Help info disappears too.

**To Reproduce**
1. Set user language to Chinese.
2. See the problem: 
- Menu options are no longer visible
- Help display on right side shows no characters

**Describe what to do for the desired behavior**
After setting user language to Chinese:
- the display of menu options should be visible.
- the display of help information on the right side should be visible.

**Screenshots**
    
![In Chinese user language menu options disappear](https://user-images.githubusercontent.com/22628444/106428302-68f68300-6471-11eb-8154-c22c42c76a7f.PNG)

**Comment by hopesu21** [comment]
@gtroiani In version 0.9.1.9 on Windows this issue does not appear. 
![Uploading Screenshot (39).png…]()
