### ISSUE TITLE
Voids and the Break Test: Freeze the Race to Infinity

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#77]
**Describe the bug**
The Race to Infinity is a well-known problem, described in several locations. In certain configurations (for example, when Rez links cross), a feedback loop arises in which two words push and pull each other to the right -- a runaway process with no limit in sight.

**To Reproduce**
1. Turn off dev messages related to Break testing (so we can try a new approach).
2. Make two Rez chains that cross, as follows: 
- Connect a word in line 1 to a word in line 2
- Then connect a second word in line 1 to a second word in line 2, such that the lines for the two Rez links cross over each other. 
3. Watch the words disappear off the right side of the screen.
4. Notice the **_large gap of white space_** (empty cells) to the **_left_** of the two words that have disappeared.

**Expected behavior**
1. Turn off dev messages related to the Break test (so we can try a new approach).
2. Watch for Voids. 
3. A Void is defined as one or more empty cells between two words.
4. A Void is not necessarily a bad thing, if it is small. When it is large, or when it grows without limit, it may become a problem.
4. Voids occur next to words, and can be thought of as associated with a neighboring word.
5. For any given word, the Void value is measured to the left. The Void value is the number of empty cells occurring between this word and the immediate previous word to its left. 
6. For the first word in a line, the Void value is the number of empty cells between this word and the left margin (initially this should be 0).
7. Normally, every word in a transcription will begin with a Void value of zero. (That is, that is, it has no Void to its left, and in fact there are no Voids anywhere in the Discourse. This is before the user has created any Rez chains. Once Rez chains are created, they will very often create Voids, as soon as they are aligned.) 
8. When the user does anything that will cause any word to change its row (such as adding a word to a Rez chain), do the following:
9. For each word in the row, examine each pair of successive words (that is, pairs of words whose Place values [WordSeq valus] are N and N+1).
10. For each word pair, recalculate the Void value, as the number of empty cells between the two words.
11. That is, if a = display row of the first word, and b = display row of the second word, then Void = (b-a)-1.
12. Record the Void value for each word in the DynamicWord grid, in a column with the header "Void". (Initially this will be 0 for every word, but it can change.)
13. For each Line that contains a word that has been moved, calculate the VoidMax as the highest Void in the line. 
14. Also, calculate the VoidSum for each line (the total number of empty cells in the line).
15. Record the VoidMax and VoidSum values for each line in the Line grid (in columns with the headers VoidMax and VoidSum). (Initially these values will be 0 for every Line, but they can change.)
16. Declare a variable of VoidLimit, and set its value to some moderately large number (for a start, let's try VoidLimit = 25).
17. For any line where the VoidMax value reaches the VoidLimit (or higher), mark this line as having a Break.
18. Stop pushing/pulling in all words of the Break line.
18. For any Break line, draw a BreakFlag (for example, color the long stretch of empty cells in red).
19. Display an error message, giving the user the option to undo the last modified Rez link (or to unalign the  last modified Rez chain).

**Additional Context**
In the longer run, we can extend this approach to Cliques:
1. Calculate the VoidMax value for a whole Clique. 
2. To do this, check the VoidMax value for each line in the Clique, and keep the highest value as the VoidMax of the Clique.
3. If the VoidMax for a Clique goes over a predefined limit (VoidLimit), stop all push/pull actions for the relevant lines and words.
4. As described elsewhere, test each Rez chain in the Clique to see if it's causing the Break (VoidMax over the VoidLimit).
5. As described elsewhere, when a problematic Rez chain is identified, test each word to see if it's causing the Break.

**Comment by terrydubois** [comment]
Had break detection and stopped chains going out to infinity. Check again to make sure this is still happening.
