### ISSUE TITLE
Crash when clicking on first word in the line

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#78]
**Describe the bug**
When making a Rez chain, if you click on a word in the first column, Rezonator freezes completely. You can't even close the program; you have to use the Task Manager to quit.

**To Reproduce**
1. Open a file.
2. Click on any word in the first column.
3. See error: the program freezes.

**Expected behavior**
You should be able to click on words in the first column. 
1. I suspect this has to do with calculating the Void for words in the first column. 
2. It's not enough for the Void calculation to look for the word to the left of the current word. What if there is no word to the left?
3. Whenever you are dealing with the first word in the current line (i.e. when there is no word to the left), then the Void has to be calculated relative to the display column just before column 0, that is, column -1.
4. The Void for the first word is 0-(-1)-1 = 0, but only if it is in the first column (column 0). 
5. It's important to pay special attention to the first word also when it is in some other column (e.g. display column 5, because it has been pulled over by a Rez chain). The same calculation applies, relative to displayRow -1.

**Comment by terrydubois** [comment]
Main bug solved, however first word will still float out in space if not connected to other words.
