### ISSUE TITLE
IGT import fails when # appears as first character in a line

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#787]
**Bug**
1. IGT import fails when # appears as the first character in any line of the imported file.
2. "#" is a commonly used character in a discourse transcription, so it should be possible to import it without causing problems.
3. Given this conflict, the Scription convention for # as the first character of a line cannot be supported.     
Note that \\# can be used as a marker without causing any problems, because it has the backslash character \\. 

**How to reproduce**
1. Start with a plain text IGT file that is known to import correctly into Rezonator. 
2. Insert "#" as the first character in one or more lines of the transcription.
3. Import the file using IGT.
4. See the error message; and the import fails.

**What to do**
Make sure that importing succeeds even when # appears as the first character in a line of the imported file.

**Comment by AvivSamet** [comment]
Check the behavior when there is a tab or a space as the first character followed by a # as the second character.
