### ISSUE TITLE
QuickPick fails in Read mode

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#791]
**Bug**
It's impossible to focus a Track chain in Read mode, so this means you can't do a QuickPick in Read mode. Not good.

**To Reproduce**
1. Make a track chain.
2. Switch to Read mode.
3. Click on a word in the Main screen that is already in the Track chain. Nothing happens. (Not good.)
4. While the cursor is hovering over a word in the Track chain, press "p" to do a QuickPick. Nothing happens. (Also not good.)
5. Switch to Track mode. Repeat the 2 previous steps (3 and 4). Now you are able to focus the word, which focuses the Track chain it is in, which lets you do the QuickPick. But you shouldn't have to do all this just to enjoy the QuickPick function.

**Describe what to do for the desired behavior**
1. Allow the user to focus a Track chain in Read mode, in the usual way (by just clicking on a word). 
2. Once they have focused the Track chain of interest, let them do a QuickPick, in order to zoom in on the Track chain without leaving Read mode.

**Comment by hopesu21** [comment]
![Uploading Screenshot (92).png…]()
