### ISSUE TITLE
Can't add a word to both a Track and a Rez chain

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#798]
**Bug**
You can't add a word to both a Track and a Rez chain

**To Reproduce**
1. Make a Track chain with a few Tracks.
2. Now make a Rez chain with a few Rezzes.
3. Now try to a word from the Track chain to your current Rez chain.
4. All that happens is you switch focus to the Rez chain.

**Describe what to do for the desired behavior**
Make it easy for users to add a word to BOTH a Rez chain and a Track chain, with a single click.

**Comment by hopesu21** [comment]
Still an issue as of 0.9.2.6
