### ISSUE TITLE
Split Word function writes words in the wrong order

### ISSUE THREAD

**Issue by gtroiani** [johnwdubois/rezonator#802]
Users might want to split words into two pieces an to modify words directly into Rezonator, without having to change the original dataset. At the moment, when users split word into two, the new words show up in the opposite order that was given.

1. Open a file of any kind and select either Track or Rez Mode
2. Right click on any word to open the word menu
3. Select option "Split Word"
4. Type any two words and click "Ok"
5. See that words appear in the opposite order that was used to type them in

The order in which words are displayed by the Split Word feature should be reversed so that word 1 shows up in the text as antecedent to word 2.

<img width="960" alt="swapped words 1" src="https://user-images.githubusercontent.com/26060089/107976636-be04bf80-6f6e-11eb-87d7-79c3e6533b1a.PNG">

<img width="960" alt="swapped words" src="https://user-images.githubusercontent.com/26060089/107976638-be9d5600-6f6e-11eb-8e59-dcc6a5e276b7.PNG">

**Comment by johnwdubois** [comment]
Be sure to test this also with RTL languages (e.g. Hebrew).

**Comment by hopesu21** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/77072787/110934425-d99b8580-82e2-11eb-91ce-30bb1fe677d8.png)
