### ISSUE TITLE
Buttons jammed together on Tool bar

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#824]
**What is the background of this bug report?**
On a small screen, the tool bar buttons are all jammed together on the Tool bar.

**To Reproduce**
1. Use a computer with small, low-res screen.
2. See the buttons all jammed together.

**Describe what to do for the desired behavior**
Create a scroll bar for the toolbar, if there's not enough room for all the buttons to show in their proper size.

**Screenshots**
![Buttons jammed together on tool bar](https://user-images.githubusercontent.com/22628444/110499426-e2ccfc80-8100-11eb-9849-bbf64bfca92a.PNG)

**Comment by hopesu21** [comment]
![toolbar](https://user-images.githubusercontent.com/77072787/110928817-262f9280-82dc-11eb-964a-6117ff191a5f.jpg)
Other bug also appeared when attempting to reduplicate this bug. Will write separate ticket.

**Comment by hopesu21** [comment]
Tool bar is now more linear in latest version. When changing screen size or minimizing screen, help button is cut off but everything else is fine.
