### ISSUE TITLE
Automatic software updates

### ISSUE THREAD

**Issue by ZoeF99** [johnwdubois/rezonator#830]
**Background**
Users need to check updates on Rezonator website to access the newest version. The new Rezonator software has a version suffix and so does not overwrite the older software. Without deleting the older versions, users have a new software on their computer every time there is an update.

**Describe alternatives you've considered**

In setting, add options for update preference: get notifications when updates are available or automatically install updates.

1. Compile an update package that users can install upon current version.
2. Push notifications to users that new update is available for download

_or_
1. Hide version information in the file name so that updated version can overwrite the old version.
2. Push notifications to users that new version is available for download. Link the website in the notification.

**Comment by johnwdubois** [comment]
Should we use Firebase for this?
