### ISSUE TITLE
Go to line

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#84]
**Is your feature request related to a problem?**
In a conversation that may have 1,000 or more lines, it's important to be able to move quickly to a line that is of interest to you.

**Describe the solution you'd like**
1. When in the main screen, the user presses "g" to bring up a dialogue box (goToLine) with the message: "Go to line: _____ " 
2. The goToLine dialogue box takes integer input only.
3. When you type in a number and press enter, the cursor moves to the beginning of that line, and puts the line at the center row of the screen.
4. The dialogue box might remember the last line searched for, or keep a drop-down list of the most recent line searches.

**Describe alternatives you've considered**
The dialogue box could bring up a drop-down scrollable list containing all available line numbers, but most often this would be frustrating, because there are too many lines for this to be useful.

**Additional context**
In the long term, it would be nice to expand the "goTo" function depending on the context; for example, providing a relevant dialogue if you are in the Nav window, or focused on a Track chain, etc. This can wait till later. For now, the "g" keypress should always take you to a line in the main screen.

**Comment by johnwdubois** [comment]
The keystroke should be "g", not "j".

**Comment by terrydubois** [comment]
Should do nothing if user inputs anything other than integers.
