### ISSUE TITLE
Justify = {Left, Right, Center}; {Prose, Grid}

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#85]
**Dev Hours**
10 Hours

**Is your feature request related to a problem?**
The reader familiar with print or word processor presentation of text typically expects text to be justified in the same way (for example, left-justified with a ragged-right margin). 
But in Rezonator, the default justification varies according to which Mode the user is in:
- Read mode: left-justified, with Prose format 
- Rez mode: left-justified, with Grid format
- Search screen: center-justified, with Grid format
(The Grid format corresponds to the most typical  and distinctive Rezonator display format, with each word shown in its own cell, like a chess board.)
       But for some purposes, it may useful to offer different views of the same data. For example, it is useful to alternate the view of your transcription between the usual standard left-justified text, vs. the alternative view of right-justified text, or even "center-justified" text (centered on a key word).    

**Describe the solution you'd like**
1. When the user presses "j", this should toggle between available options for justification. 
2. There should be two distinct user-selectable features (parameters), which can be combined:
- `Justify` = {left, right, center}
- `Prose` = {prose, grid} (Alternative: `Prose` = {TRUE, FALSE})
3. Combining these features produces 6 possibilities:
- `Justify` = left, `Prose` = Prose
- `Justify` = left, `Prose` = Grid
- `Justify` = right, `Prose` = Prose
- `Justify` = right, `Prose` = Grid
- `Justify` = center, `Prose` = Prose
- `Justify` = center, `Prose`  = Grid
4. By default, the transcription in the main screen is `JustifyLeft` (with the first word of every line in the leftmost column of the screen view), in prose style (`Justify` = left, `Prose` = prose)
5. When the user presses "j", the transcription becomes grid-justified (`Justify` = left, `Prose` = grid).
6. When the user presses "j" again, the transcription becomes right-justified (with the **last** word of every line appearing in the **rightmost** column of the screen view); first in `Prose` format, then in `Grid` format.
7. Pressing "j" repeatedly cycles through the 6 formats listed above.

**How to implement**
1. To implement the above in Rezonator, it is necessary to map every token onto a column, which will change according to the user's decisions about justification (e.g. `Justify` = {left, right}).
2. First, implement `justifyRight`, because this requires a new approach.
3. One way to do this is to distinguish between `order` and `backOrder`
- `order` represents the enumeration of each token (word, laugh, cough, pause, endnote, etc.) from left to right, counting from the beginning of the Unit (e.g. Intonation Unit, or line) to the end of that Unit.
- `backOrder` represents the enumeration of each token (word, laugh, cough, pause, endnote, etc.) from right to left, counting from the **_end_** of the Unit (e.g. Intonation Unit, or line) to the **_start_** of that Unit. 
- By convention,  `backOrder` can be represented using negative integers (-1, -2, -3....), representing the last token, second-to-last token, etc.
4. Assuming there are 20 columns on the screen, the rightmost column is column 20. Then:
- Column 20 contains tokens for which `backOrder` -1 
- Column 19 contains tokens for which `backOrder` -2 
- Column 18 contains tokens for which `backOrder` -3 
- etc.
5. To allow fast switching between different Justification displays, each token (word, laugh, cough, pause, endnote, etc.) should store the value for both its `Order` and its `backOrder` .

**Center justification**
1. Center-justified is a type of justification that is relevant in some circumstances; it is already implemented as the default for the Search screen text display (`Justify` = center, `Prose` = Grid).
2. Center-justified may be implemented by setting Column 0 to be in the center of the screen. 
3. It may be useful to make the "Center-justified" option available also on the main screen. Or perhaps not -- this is a design discussion.
4. Where center-justified is available, it should be possible to combine it with the option to choose grid vs. prose. (Currently, the search screen does not implement the `Prose` = Prose option.)

**Icons**
For icons, take inspiration from Google's [Material Design icons](https://material.io/tools/icons/). Take a look at:
- format_align_left = left justification
- format_align_right = right justification
- format_align_center = center justification
- format_align_justify = justification aligned left and right (we don't use this currently)
- apps = cell justification (grid justification)

**Additional context**
At a more advanced level, justification is related to the concept of the "Spine" #94 (a kind of attractor that pulls words toward it).

**Comment by Georgio-Klironomos** [comment]
Right and center Justify work with unchained words, the next step would be to get it working with chained words. this might be best achieved after the link grid reconstruction.

**Comment by johnwdubois** [comment]
Right-justification works, so this ticket is finished. The fact that alignment fails in right-justified text calls for a separate ticket.
