### ISSUE TITLE
Non-ASCII Latin characters not displayed in v. 0.11

### ISSUE THREAD

**Issue by gtroiani** [johnwdubois/rezonator#865]
Only ASCII characters are displayed for latin-based scripts (both for the interface and for data imported by users). 

<img width="960" alt="ascii bug" src="https://user-images.githubusercontent.com/26060089/113585535-3425ba00-95e1-11eb-8053-8c4a938b5db3.PNG">

Version: 0.11
System: Windows
Notes: characters were displaying fine in versions 0.9

**Comment by johnwdubois** [comment]
Missing characters in widely used languages (Spanish, etc.). Needs fixed.

**Comment by gtroiani** [comment]
Cyrillic is also missing
