### ISSUE TITLE
Import schemas not working

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#908]
**What is the background of this bug report?**
The import screen doesn't change when I load an import schema.

**To Reproduce**
Import the csv attached and apply the import schema attached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.15.0.0
 
[20210623_rez.zip](https://github.com/johnwdubois/rezonator/files/6700447/20210623_rez.zip)

**Comment by johnwdubois** [comment]
I can confirm this bug -- I have repeatedly tweaked and saved a schema file, which is then not used even after I load it.
