### ISSUE TITLE
Parent-child inheritance of node ID’s

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#912]
**Questions**
1. How is it possible to have a bug of the kind found in importing Ryan’s Tibetan data? 
- #907 
2. Is the misplacement of Tokens relative to Units a symptom of a deeper flaw in the import process?
3. Are we still using “cheats” that rely on token Sequence instead of node ID inheritance?
4. How can we structure the inheritance of parent-child relationships during the import and splitting process, so that bugs of this kind can never arise? 
5. Relevant contexts include inheritance between:
- Unit and Token
- Morph and Word
- Unit and Doc
- etc.
6. Sketch out a prototype of a solution using Whimsical, with this mockup as a starting point for discussion:
- #911 

**Related to**
- #907 
- #911

**Comment by terrydubois** [comment]
Units need field for "Doc"
