### ISSUE TITLE
Quick Tag

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#915]
By default, the Quick Tag option should present a Field and all of the options from its Tagset, not just 1 pre-selected Tag.

**What to Do**
1. Let the user choose a default Field and a default Tag as they do now. But….
2. Instead of automatically applying the Tag to a token that is clicked on, simply:
- Show the Tag as a pre-selected option for the selected Field, along with all the other options for the tagset of this field.
- The user can then press enter to select the default Tag, or…
- The user can select a different Tag from the displayed options for this Field
3. To initiate the above process of applying a Quick Tag to a word, the user must press “t” (This requires a more conscious user action, similar to "z" for zero, so it’s safer.)

**Comment by terrydubois** [comment]
Finalize UX
show tag set
have user confirmation to tag
