### ISSUE TITLE
Clicking <0> gives the custom word window

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#925]
**What is the background of this bug report?**
When the user clicks <0> on the context menu, a <0> should be inserted. Currently, the custom word window pops up instead.

**To Reproduce**
1. Right click a word
2. Select add word, then <0>

**Describe what to do for the desired behavior**
A <0> should appear directly

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by terrydubois** [comment]
no blank strings allowed :(
