### ISSUE TITLE
Chunks within chunks no longer visible

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#926]
**What is the background of this bug report?**
In the past chunks within chunks remained visible. Now they are no longer visible. For example:

![image](https://user-images.githubusercontent.com/43101723/124877991-79f77300-df80-11eb-9d41-bc81ba9731ac.png)

Here, ཁྱེད་རང་ གི་ is a chunk but you can't see that.

**To Reproduce**
1. Create a big chunk
2. Create a small chunk within the big chunk

**Describe what to do for the desired behavior**
The small chunk should be visible inside the big chunk

**Comment by johnwdubois** [comment]
Find Georgio's code for this. Do not try to reinvent the wheel - it's complex, and it's already solved in GML.
