### ISSUE TITLE
Import SBCorpus as CSV

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#93]
**Dev Hours**
6 Hours

**What is needed**
It should be possible to import an entire corpus by importing a single file, creating a single large grid in Rezonator. The individual conversations in the corpus can then be split out from the larger file.

**Expected behavior: Quick version**
1. Import a **small** CSV file containing just 2 of the 60 discourses in the Santa Barbara Corpus.
2. This will allow for a quick test of 3 things:
- assigning UnitId and WordId to multiple discourses at once
- importing CSV file with new kinds of columns
- getting comfortable with the new data in the SBCorpus

**Expected behavior: Long version**
1. The import process should assign a unique UnitID to every unit (line) in the entire corpus. 
2. It should also assign a unique WordID to every word in the entire corpus.
3. In addition, a second ID for each Unit can be assigned to be unique per Discourse (i.e. starting at 1 at the beginning of each new conversation in the corpus.)
4. Similarly, a second ID for each word can be assigned to be unique per Discourse (i.e. starting at 1 at the beginning of each new conversation in the corpus.)
5. Keeping 2 sets of IDs for the units, and 2 sets of ID's for the words, will ensure that there is no need to modify ID values when loading several Discourses.
5. This approach should allow a choice between:
- loading the entire corpus at once (as a single .rez file, for the corpus)
- loading one discourse at a time (as a single .rez file, for the desired discourse)
- loading several discourses at a time (as a set of .rez files, for the desired list of discourses)
6. Alternatively, the user could just use the larger Corpus file, and specify which Discourses they want to work with from this corpus. These could then be filtered as a subset of the larger Corpus grid.

**Additional context**
A new version of the Santa Barbara Corpus (2nd edition) now exists, as a plain text CSV table, with one Word per row. This Word table also contains all the information needed for creating Units, etc.    
The new version contains lots of fields (columns) with information that we want to use. So: 
- Import the new Santa Barbara Corpus files to Rezonator, via new CSV table for Word
- Make use of all relevant information in the columns of the tables

**Comment by johnwdubois** [comment]
Check out the new edition of the SBC on Box: 
- SBC_dft_word_info_rez_test_v1_Excerpt_SBC001-002.csv (just the first two transcripts, good to practice with)
- SBC_dft_word_info_rez_test_v1.csv (full SBC corpus, very large)

**Comment by Georgio-Klironomos** [comment]
Next step for Terry is creating a col in the import screen for custom unitStart/unitEnd

**Comment by Georgio-Klironomos** [comment]
All major functionality is there as reported by Terry and Brady. If issues are found during testing, we'll create separate bug report tickets for them.

**Comment by johnwdubois** [comment]
If you haven't tested it, don't close it.

**Comment by Georgio-Klironomos** [comment]
More usability tests will be performed by Georgio, and @johnwdubois will also be testing this feature himself. (sorry for the @, I hope you're still taking Saturday off)

**Comment by Georgio-Klironomos** [comment]
@johnwdubois With the Import Schema built for SBC CSV's, we are able to bypass the level estimates for a quick and fully functional import. Level estimates will need to be improved in the future for other non-SBC CSV's, and we should make this a separate ticket as part of a future release.

**Comment by Georgio-Klironomos** [comment]
The SBCorpus import now has a fully functional schema included with the newest version of Rezonator. The Schema has been thoroughly tested, and with your approval @johnwdubois we can close this ticket.
