### ISSUE TITLE
Include linkers to document in token / unit nodes

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#937]
**What is the background of this feature request? Please describe.**
If we eventually want multiple documents displayed at the same time, we would need to represent which document each node belongs to.

**Describe what to do for the development of this feature**
Add a field to token and/or unit nodes pointing to the document ID.

**Comment by kayaulai** [comment]
Actually I don't seem to find the document ID in the tokens, for example:

				"28F597909C5D6": {
					"void": 1,
					"tokenOrder": 1,
					"searched": 0,
					"docTokenSeq": 11,
					"inChainsList": [],
					"inChunkList": [],
					"displayCol": 0,
					"pixelX": 349,
					"tagMap": {
						"lit": "འོ་ཙི",
						"Col 0": "10",
						"chunkLayer": "",
						"wordWylie": "a tsi",
						"word": "ཨ་ཙི"
					},
					"unit": "4AA96BFF3B33",
					"prevToken": "",
					"type": "token"
				},

Is this an issue?

**Comment by johnwdubois** [comment]
Please add docId to the tokens.
