### ISSUE TITLE
Autosave fix - Corrupt Rez file

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#943]
**What is the background of this bug report?**
A Rez file was corrupted for some reason. 

[three-parting-2569_new_corrupt.zip](https://github.com/johnwdubois/rezonator/files/6890897/three-parting-2569_new_corrupt.zip)

I'm not exactly what went wrong, but I think this was an autosave. I can't tell what's actually happening in the file.

**Comment by kittynugget** [comment]
autosave needs to be checked
