### ISSUE TITLE
Field input dialogue

### ISSUE THREAD

**Issue by kayaulai** [johnwdubois/rezonator#983]
**What is the background of this feature request? Please describe.**
Sometimes, some fields have an open-ended number of options, and the current drop-down menu option can become very cumbersome.

**Describe what to do for the development of this feature**
In the right-click menu, add an option to type the feature directly. The ideal situation would be typing directly in the table, but if not, then it may use the pop-up text input window that's already implemented.

**Comment by terrydubois** [comment]
From the "Allow users to type tag values directly" ticket: #890 

Background
Right now, when a field has a large number of possible tag values, it takes very long to scroll through the list to get to the bottom of it after adding a new item.

What to do
1, The user should be able to type in a tag value directly in the relevant field (=column in the Nav window), without having to scroll.
2, Alternatively, the user should be able to use a popup to type in the tag value.
